//! Policy loading and exception recording (kernel layer): the machine and
//! project policy chain, the exception kinds a sync may wave through, and
//! the collision checks the store consults at commit time.

use crate::kernel::store::Store;
use serde::{Deserialize, Serialize};
use std::collections::BTreeSet;
use std::fs;
use std::io;
use std::path::Path;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Mutex, OnceLock};

/// A requirement was skipped because it is project-local or a direct reference.
pub const REQUIREMENT_SKIPPED: &str = "requirement-skipped";
/// Two wheels shipped the same path; the later wheel won.
pub const FILE_COLLISION: &str = "file-collision";
/// An install lifecycle script failed but its extracted package was retained.
pub const INSTALL_SCRIPT_FAILED: &str = "install-script-failed";
/// A legacy SHA-1 lock integrity was accepted and verified.
pub const WEAK_INTEGRITY: &str = "weak-integrity";
/// A mutable projection was created without attesting its runtime contents.
pub const UNATTESTED_MUTABLE_STATE: &str = "unattested-mutable-state";
/// A requested toolchain component is not available in the pinned toolchain.
pub const TOOLCHAIN_COMPONENT_UNAVAILABLE: &str = "toolchain-component-unavailable";
/// A future git dependency was accepted without registry provenance.
pub const GIT_DEPENDENCY: &str = "git-dependency";
/// An optional dependency/group was not requested by the user.
pub const SKIPPED_OPTIONAL: &str = "skipped_optional";
/// A manifest named a private index or an index-like option.
pub const UNATTESTED_INDEX: &str = "unattested_index";
/// A lock's content digest did not match its source manifest.
pub const LOCK_DISAGREEMENT: &str = "lock_disagreement";
/// A Cargo.lock was generated by the store Cargo rather than shipped by the
/// source archive.
pub const UNATTESTED_CARGO_LOCK: &str = "unattested_cargo_lock";
/// An install-time download was skipped; the artifact is not in the closure.
pub const ARTIFACT_NOT_PROVISIONED: &str = "artifact_not_provisioned";
/// blanket downloaded and verified an install-time artifact itself; the
/// checksum source is upstream's own manifest (trust-on-first-use).
pub const ARTIFACT_PROVISIONED: &str = "artifact_provisioned";
/// A package that ships prebuilt binaries was compiled from source instead.
pub const BUILT_FROM_SOURCE: &str = "built_from_source";

pub const KINDS: &[&str] = &[
    REQUIREMENT_SKIPPED,
    FILE_COLLISION,
    INSTALL_SCRIPT_FAILED,
    WEAK_INTEGRITY,
    UNATTESTED_MUTABLE_STATE,
    TOOLCHAIN_COMPONENT_UNAVAILABLE,
    GIT_DEPENDENCY,
    SKIPPED_OPTIONAL,
    UNATTESTED_INDEX,
    LOCK_DISAGREEMENT,
    UNATTESTED_CARGO_LOCK,
    ARTIFACT_NOT_PROVISIONED,
    ARTIFACT_PROVISIONED,
    BUILT_FROM_SOURCE,
];

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Exception {
    pub kind: String,
    pub subject: String,
    pub detail: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Policy {
    #[serde(default)]
    pub strict: bool,
    #[serde(default)]
    pub deny: BTreeSet<String>,
}

static POLICY: OnceLock<Policy> = OnceLock::new();

#[derive(Debug)]
struct Frame {
    id: u64,
    owner: std::thread::ThreadId,
    ecosystem: String,
    exceptions: Vec<Exception>,
    claimed: bool,
    published: bool,
}

static FRAMES: OnceLock<Mutex<Vec<Frame>>> = OnceLock::new();
static NEXT_FRAME_ID: AtomicU64 = AtomicU64::new(1);

fn frames() -> &'static Mutex<Vec<Frame>> {
    FRAMES.get_or_init(|| Mutex::new(Vec::new()))
}

fn with_frames<R>(f: impl FnOnce(&mut Vec<Frame>) -> R) -> R {
    f(&mut frames().lock().unwrap_or_else(|error| error.into_inner()))
}

/// Parse one policy file, refusing unknown keys and unknown deny kinds.
pub fn parse_file(path: &Path, text: &str) -> io::Result<Policy> {
    let policy: Policy = toml::from_str(text).map_err(|e| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("parse {}: {e}", path.display()),
        )
    })?;
    let unknown: Vec<&str> = policy
        .deny
        .iter()
        .map(String::as_str)
        .filter(|kind| !KINDS.contains(kind))
        .collect();
    if !unknown.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!(
                "{}: unknown deny kind(s): {}; valid kinds: {}",
                path.display(),
                unknown.join(", "),
                KINDS.join(", ")
            ),
        ));
    }
    Ok(policy)
}

fn merge_file(policy: &mut Policy, path: &Path, required: bool) -> io::Result<()> {
    let text = match fs::read_to_string(path) {
        Ok(text) => text,
        Err(e) if e.kind() == io::ErrorKind::NotFound && !required => return Ok(()),
        Err(e) => {
            return Err(io::Error::new(
                e.kind(),
                format!("read {}: {e}", path.display()),
            ))
        }
    };
    let other = parse_file(path, &text)?;
    union(policy, &other);
    Ok(())
}

/// Union `other` into `policy`. Union only tightens: the result denies
/// everything `policy` denied plus everything `other` denies, and is strict
/// if either is. Used by `blanket audit --policy`, so a file handed to the
/// gate can never loosen the machine or project policy.
pub fn union(policy: &mut Policy, other: &Policy) {
    policy.strict |= other.strict;
    policy.deny.extend(other.deny.iter().cloned());
}

/// Load the user and project policies once, unioning all deny entries.
pub fn load(project_dir: &Path, cli_strict: bool) -> io::Result<Policy> {
    let mut policy = Policy::default();
    if let Some(path) = std::env::var_os("BLANKET_POLICY") {
        merge_file(&mut policy, Path::new(&path), true)?;
    } else if let Some(home) = std::env::var_os("HOME") {
        merge_file(
            &mut policy,
            &Path::new(&home).join(".blanket/policy.toml"),
            false,
        )?;
    }
    // Every ancestor's project policy applies (union only tightens), so a
    // workspace-root policy governs builds started in a member directory
    // without blanket having to know each ecosystem's rooting rule.
    for dir in project_dir.ancestors() {
        merge_file(&mut policy, &dir.join(".blanket/policy.toml"), false)?;
    }
    policy.strict |= cli_strict || std::env::var("BLANKET_STRICT").as_deref() == Ok("1");
    Ok(policy)
}

/// Initialize the process policy. Repeated calls keep the first loaded policy.
pub fn init(project_dir: &Path, cli_strict: bool) -> io::Result<()> {
    if POLICY.get().is_none() {
        let _ = POLICY.set(load(project_dir, cli_strict)?);
    }
    Ok(())
}

fn current() -> &'static Policy {
    POLICY.get_or_init(Policy::default)
}

/// Whether `policy` refuses an exception of `kind`.
pub fn denied(policy: &Policy, kind: &str) -> bool {
    policy.strict || policy.deny.contains(kind)
}

pub fn record_with(policy: &Policy, kind: &str, subject: &str, detail: &str) -> io::Result<()> {
    with_frames(|frames| {
        let Some(frame) = frames.last_mut() else {
            return Err(io::Error::other(
                "exception recorded outside any attribution",
            ));
        };
        // Records belong to the thread that opened the innermost frame. A
        // worker thread recording into another realization's frame would be
        // claimed by that realization's closure.
        if frame.owner != std::thread::current().id() {
            return Err(io::Error::other(format!(
                "exception {kind} recorded from a thread that does not own the {} attribution",
                frame.ecosystem
            )));
        }
        if denied(policy, kind) {
            return Err(io::Error::new(
                io::ErrorKind::PermissionDenied,
                format!(
                    "policy denies {kind}: {subject}: {detail} (see .blanket/policy.toml / BLANKET_STRICT)"
                ),
            ));
        }
        eprintln!("blanket: exception {kind}: {subject}: {detail}");
        frame.exceptions.push(Exception {
            kind: kind.into(),
            subject: subject.into(),
            detail: detail.into(),
        });
        Ok(())
    })
}

pub fn record(kind: &str, subject: &str, detail: &str) -> io::Result<()> {
    record_with(current(), kind, subject, detail)
}

fn format_exception_list(exceptions: &[Exception]) -> String {
    exceptions
        .iter()
        .map(|exception| {
            format!(
                "{}: {}: {}",
                exception.kind, exception.subject, exception.detail
            )
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// A value that owns one frame in the process-global attribution stack.
#[must_use = "an attribution must be held across the realization it owns"]
#[derive(Debug)]
pub struct Attribution {
    id: u64,
    ecosystem: String,
    active: bool,
}

impl Attribution {
    /// Open a realization frame. A different thread may not open over the
    /// current innermost frame because records are process-global.
    pub fn open(ecosystem: &str) -> io::Result<Self> {
        let owner = std::thread::current().id();
        with_frames(|frames| {
            if let Some(frame) = frames.last() {
                if frame.owner != owner {
                    return Err(io::Error::new(
                        io::ErrorKind::WouldBlock,
                        format!(
                            "another thread owns the innermost attribution for {}; {ecosystem} cannot open",
                            frame.ecosystem
                        ),
                    ));
                }
            }
            let id = NEXT_FRAME_ID.fetch_add(1, Ordering::Relaxed);
            frames.push(Frame {
                id,
                owner,
                ecosystem: ecosystem.to_string(),
                exceptions: Vec::new(),
                claimed: false,
                published: false,
            });
            Ok(Self {
                id,
                ecosystem: ecosystem.to_string(),
                active: true,
            })
        })
    }

    /// Open a child realization owned by this token's thread. Records while
    /// it is open belong to the child and cannot be claimed by the parent.
    pub fn nested(&mut self, ecosystem: &str) -> io::Result<Self> {
        let owner = std::thread::current().id();
        with_frames(|frames| {
            let Some(parent) = frames.last() else {
                return Err(io::Error::other(
                    "cannot nest attribution without an open frame",
                ));
            };
            if parent.id != self.id {
                return Err(io::Error::other(
                    "cannot nest attribution while another child frame is open",
                ));
            }
            if parent.owner != owner {
                return Err(io::Error::new(
                    io::ErrorKind::WouldBlock,
                    "cannot nest attribution from another thread",
                ));
            }
            let id = NEXT_FRAME_ID.fetch_add(1, Ordering::Relaxed);
            frames.push(Frame {
                id,
                owner,
                ecosystem: ecosystem.to_string(),
                exceptions: Vec::new(),
                claimed: false,
                published: false,
            });
            Ok(Self {
                id,
                ecosystem: ecosystem.to_string(),
                active: true,
            })
        })
    }

    pub fn ecosystem(&self) -> &str {
        &self.ecosystem
    }

    /// The exceptions recorded into this frame so far, without claiming
    /// them. For diagnostics and tests; publication goes through `claim`.
    pub fn recorded(&self) -> Vec<Exception> {
        with_frames(|frames| {
            frames
                .iter()
                .find(|frame| frame.id == self.id)
                .map(|frame| frame.exceptions.clone())
                .unwrap_or_default()
        })
    }

    /// Claim the innermost frame for one closure. Only the comforter writer
    /// calls this at the publication boundary; a claimed frame must then be
    /// published or it cannot finish.
    pub(crate) fn claim(&mut self, ecosystem: &str) -> io::Result<Vec<Exception>> {
        with_frames(|frames| {
            let Some(frame) = frames.last_mut() else {
                return Err(io::Error::other(
                    "closure publication outside any attribution",
                ));
            };
            if frame.id != self.id {
                return Err(io::Error::other(
                    "cannot claim attribution while a child frame is open",
                ));
            }
            if ecosystem != self.ecosystem || ecosystem != frame.ecosystem {
                return Err(io::Error::other(format!(
                    "attribution ecosystem mismatch: token is {}, closure is {ecosystem}",
                    self.ecosystem
                )));
            }
            if frame.claimed {
                return Err(io::Error::other(format!(
                    "the {ecosystem} attribution was already claimed"
                )));
            }
            frame.claimed = true;
            Ok(std::mem::take(&mut frame.exceptions))
        })
    }

    /// Mark a successfully written closure. Claiming happens before the
    /// write, so a failed write loses the claimed exceptions with the frame.
    pub(crate) fn mark_published(&mut self) -> io::Result<()> {
        with_frames(|frames| {
            let Some(frame) = frames.last_mut() else {
                return Err(io::Error::other("attribution frame is no longer open"));
            };
            if frame.id != self.id || !frame.claimed {
                return Err(io::Error::other(
                    "attribution cannot be published before its closure is claimed",
                ));
            }
            frame.published = true;
            Ok(())
        })
    }

    pub fn finish(mut self, expect_publication: bool) -> io::Result<()> {
        let result = with_frames(|frames| {
            let Some(index) = frames.iter().position(|frame| frame.id == self.id) else {
                return Err(io::Error::other("attribution frame is no longer open"));
            };
            if index + 1 != frames.len() {
                let result = Err(io::Error::other(
                    "attribution cannot finish while a child frame is open",
                ));
                frames.remove(index);
                return result;
            }
            let frame = frames.last().expect("frame index is valid");
            let result = if frame.claimed && !frame.published {
                Err(io::Error::other(format!(
                    "{} realization claimed its exceptions but the closure write did not complete",
                    self.ecosystem
                )))
            } else if expect_publication && !frame.published {
                Err(io::Error::other(format!(
                    "{} realization reported success but published no closure",
                    self.ecosystem
                )))
            } else if !frame.exceptions.is_empty() {
                Err(io::Error::other(format!(
                    "{} realization ended with {} exception(s) never claimed by a closure: {}",
                    self.ecosystem,
                    frame.exceptions.len(),
                    format_exception_list(&frame.exceptions)
                )))
            } else {
                Ok(())
            };
            frames.pop();
            result
        });
        self.active = false;
        result
    }

    pub fn discard(mut self) {
        with_frames(|frames| {
            if let Some(index) = frames.iter().position(|frame| frame.id == self.id) {
                frames.remove(index);
            }
        });
        self.active = false;
    }
}

impl Drop for Attribution {
    fn drop(&mut self) {
        if !self.active {
            return;
        }
        // Error and panic cleanup. The success path must call finish or
        // discard explicitly, so it cannot silently bypass publication.
        with_frames(|frames| {
            if let Some(index) = frames.iter().position(|frame| frame.id == self.id) {
                frames.remove(index);
            }
        });
    }
}

#[cfg(test)]
pub(crate) fn pending() -> Vec<Exception> {
    with_frames(|frames| {
        frames
            .last()
            .map(|frame| frame.exceptions.clone())
            .unwrap_or_default()
    })
}

#[cfg(test)]
pub(crate) fn drain() -> Vec<Exception> {
    with_frames(|frames| {
        frames
            .last_mut()
            .map(|frame| std::mem::take(&mut frame.exceptions))
            .unwrap_or_default()
    })
}

#[cfg(test)]
pub(crate) fn clear() {
    with_frames(|frames| {
        if let Some(frame) = frames.last_mut() {
            frame.exceptions.clear();
        }
    });
}

/// Exceptions that change the bytes of the object being built.
pub fn object_exceptions() -> Vec<Exception> {
    with_frames(|frames| {
        frames.last().map_or_else(Vec::new, |frame| {
            frame
                .exceptions
                .iter()
                .filter(|e| {
                    matches!(
                        e.kind.as_str(),
                        FILE_COLLISION
                            | INSTALL_SCRIPT_FAILED
                            | GIT_DEPENDENCY
                            | UNATTESTED_CARGO_LOCK
                    )
                })
                .cloned()
                .collect()
        })
    })
}

/// Refuse a cached object when its recorded exceptions are denied now.
pub fn check_cached(store: &Store, id: &str) -> io::Result<()> {
    let activity = store.activity(crate::kernel::activity::ActivityMode::Shared)?;
    check_cached_with_activity(store, &activity, id)
}

pub fn check_cached_with_activity(
    store: &Store,
    activity: &crate::kernel::activity::StoreActivity,
    id: &str,
) -> io::Result<()> {
    store.require_activity(activity, "cached policy check")?;
    let exceptions = store.exceptions(id)?;
    check_exception_set(id, &exceptions)?;
    for exception in &exceptions {
        record(&exception.kind, &exception.subject, &exception.detail)?;
    }
    Ok(())
}

pub(crate) fn check_exception_set(id: &str, exceptions: &[Exception]) -> io::Result<()> {
    if exceptions.is_empty() {
        return Ok(());
    }
    let denied_kinds: Vec<&str> = exceptions
        .iter()
        .filter(|e| denied(current(), &e.kind))
        .map(|e| e.kind.as_str())
        .collect();
    if denied_kinds.is_empty() {
        return Ok(());
    }
    Err(io::Error::new(
        io::ErrorKind::PermissionDenied,
        format!(
            "cached object {id} carries exception(s): {}; blanket sync --fresh will not help; rebuild the object under a permissive policy or fix the cause",
            denied_kinds.join(", ")
        ),
    ))
}

/// Tests that read or set `HOME` / `BLANKET_POLICY` hold this lock: the
/// environment is process-global, so a test that mutates it would otherwise
/// redirect a concurrent `load` (the same hazard as `store::STORE_ENV_LOCK`).
#[cfg(test)]
pub(crate) fn test_env_lock() -> std::sync::MutexGuard<'static, ()> {
    static LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());
    LOCK.lock().unwrap_or_else(|poisoned| poisoned.into_inner())
}

/// Tests that open an `Attribution` frame here, then start from an empty
/// pending list. When a test also needs the environment, supervision, and
/// store guards, acquire them in this order: env, supervision, store,
/// attribution.
///
/// Every test that records or opens a token uses this same lock. The frame
/// stack itself remains the production implementation in test builds.
#[cfg(test)]
pub(crate) fn attribution_test_lock() -> std::sync::MutexGuard<'static, ()> {
    static LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());
    let guard = LOCK.lock().unwrap_or_else(|poisoned| poisoned.into_inner());
    clear();
    guard
}

#[cfg(test)]
pub(crate) fn exception_guard() -> std::sync::MutexGuard<'static, ()> {
    attribution_test_lock()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_policy_and_rejects_unknown_keys() {
        let policy = toml::from_str::<Policy>(
            r#"strict = true
deny = ["git-dependency"]"#,
        )
        .unwrap();
        assert!(policy.strict);
        assert!(policy.deny.contains("git-dependency"));
        assert!(toml::from_str::<Policy>("wat = true").is_err());
        let error = parse_file(Path::new("policy.toml"), "deny = [\"typo\"]").unwrap_err();
        assert!(error.to_string().contains("valid kinds:"));
    }

    #[test]
    fn union_semantics_adds_all_deny_entries() {
        let mut merged = Policy::default();
        for text in [r#"deny = ["x"]"#, r#"deny = ["y"]"#] {
            let other = toml::from_str::<Policy>(text).unwrap();
            merged.strict |= other.strict;
            merged.deny.extend(other.deny);
        }
        assert!(denied(&merged, "x"));
        assert!(denied(&merged, "y"));
    }

    #[test]
    fn record_denied_and_allowed() {
        let _guard = exception_guard();
        let attribution = Attribution::open("test").unwrap();
        assert!(record_with(
            &Policy {
                strict: true,
                deny: BTreeSet::new()
            },
            "x",
            "s",
            "d"
        )
        .is_err());
        record_with(&Policy::default(), "x", "s", "d").unwrap();
        assert_eq!(drain().len(), 1);
        attribution.discard();
    }

    #[test]
    fn attribution_state_machine_is_explicit() {
        let _guard = attribution_test_lock();
        assert!(record_with(&Policy::default(), "x", "s", "d").is_err());
        let mut parent = Attribution::open("cargo").unwrap();
        record_with(&Policy::default(), "x", "parent", "d").unwrap();
        let mut child = parent.nested("node").unwrap();
        record_with(&Policy::default(), "y", "child", "d").unwrap();
        assert!(parent
            .claim("cargo")
            .unwrap_err()
            .to_string()
            .contains("child"));
        assert!(child.claim("cargo").is_err());
        assert_eq!(child.claim("node").unwrap().len(), 1);
        child.mark_published().unwrap();
        child.finish(true).unwrap();
        assert_eq!(parent.claim("cargo").unwrap().len(), 1);
        parent.mark_published().unwrap();
        parent.finish(true).unwrap();
    }

    #[test]
    fn finish_requires_publication_and_discard_drops_a_frame() {
        let _guard = attribution_test_lock();
        let attribution = Attribution::open("python").unwrap();
        let error = attribution.finish(true).unwrap_err();
        assert!(error.to_string().contains("published no closure"));
        let attribution = Attribution::open("dependency-edit").unwrap();
        record_with(&Policy::default(), "x", "s", "d").unwrap();
        attribution.discard();
        let next = Attribution::open("node").unwrap();
        next.discard();
    }

    #[test]
    fn finish_reports_exceptions_that_no_closure_claimed() {
        let _guard = attribution_test_lock();
        let attribution = Attribution::open("python").unwrap();
        record_with(&Policy::default(), "x", "s", "d").unwrap();
        let error = attribution.finish(false).unwrap_err();
        assert!(error.to_string().contains("x: s: d"));
        Attribution::open("node").unwrap().discard();
    }

    #[test]
    fn dropping_an_attribution_discards_its_frame() {
        let _guard = attribution_test_lock();
        {
            let _attribution = Attribution::open("python").unwrap();
            record_with(&Policy::default(), "x", "s", "d").unwrap();
        }
        assert!(pending().is_empty());
        Attribution::open("node").unwrap().discard();
    }

    #[test]
    fn wrong_ecosystem_and_second_claim_are_rejected() {
        let _guard = attribution_test_lock();
        let mut attribution = Attribution::open("python").unwrap();
        assert!(attribution.claim("node").is_err());
        assert!(attribution.claim("python").unwrap().is_empty());
        attribution.mark_published().unwrap();
        assert!(attribution.claim("python").is_err());
        attribution.finish(true).unwrap();
    }

    #[test]
    fn a_second_thread_cannot_open_over_the_innermost_frame() {
        let _guard = attribution_test_lock();
        let (opened_tx, opened_rx) = std::sync::mpsc::channel::<()>();
        let (release_tx, release_rx) = std::sync::mpsc::channel::<()>();
        let owner = std::thread::spawn(move || {
            let scope = Attribution::open("python").unwrap();
            opened_tx.send(()).unwrap();
            release_rx.recv().unwrap();
            drop(scope);
        });
        opened_rx.recv().unwrap();
        let error = Attribution::open("node").unwrap_err();
        assert_eq!(error.kind(), io::ErrorKind::WouldBlock);
        release_tx.send(()).unwrap();
        owner.join().unwrap();
        Attribution::open("node").unwrap().discard();
    }

    #[test]
    fn drain_clears() {
        let _guard = exception_guard();
        let attribution = Attribution::open("test").unwrap();
        record_with(&Policy::default(), "x", "s", "d").unwrap();
        assert_eq!(drain().len(), 1);
        assert!(drain().is_empty());
        attribution.discard();
    }

    #[test]
    fn a_second_thread_cannot_record_into_the_innermost_frame() {
        let _guard = exception_guard();
        let attribution = Attribution::open("thread-owner").unwrap();
        let error =
            std::thread::spawn(|| record_with(&Policy::default(), "thread-shared", "s", "d"))
                .join()
                .unwrap()
                .unwrap_err();
        assert!(error.to_string().contains("does not own"), "{error}");
        assert!(pending().is_empty());
        assert!(attribution.recorded().is_empty());
        attribution.discard();
    }

    #[test]
    fn a_claimed_frame_cannot_finish_without_publication() {
        let _guard = attribution_test_lock();
        let mut attribution = Attribution::open("node").unwrap();
        record_with(&Policy::default(), "x", "s", "d").unwrap();
        assert_eq!(attribution.recorded().len(), 1);
        assert_eq!(attribution.claim("node").unwrap().len(), 1);
        let error = attribution.finish(false).unwrap_err();
        assert!(error.to_string().contains("did not complete"), "{error}");
        assert!(pending().is_empty());
        Attribution::open("python").unwrap().discard();
    }

    #[test]
    fn loads_user_and_project_policy_union_from_files() {
        let root = std::env::temp_dir().join(format!(
            "blanket-policy-test-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        let home = root.join("home");
        let project = root.join("project");
        fs::create_dir_all(home.join(".blanket")).unwrap();
        fs::create_dir_all(project.join(".blanket")).unwrap();
        fs::write(
            home.join(".blanket/policy.toml"),
            "deny = [\"git-dependency\"]\n",
        )
        .unwrap();
        fs::write(
            project.join(".blanket/policy.toml"),
            "strict = true\ndeny = [\"file-collision\"]\n",
        )
        .unwrap();
        let _env = test_env_lock();
        let old_home = std::env::var_os("HOME");
        let old_policy = std::env::var_os("BLANKET_POLICY");
        std::env::set_var("HOME", &home);
        std::env::remove_var("BLANKET_POLICY");
        let loaded = load(&project, false).unwrap();
        // Ancestor rule: a workspace member inherits the root's policy.
        let member = project.join("crates/member");
        fs::create_dir_all(&member).unwrap();
        let from_member = load(&member, false).unwrap();
        match old_home {
            Some(value) => std::env::set_var("HOME", value),
            None => std::env::remove_var("HOME"),
        }
        match old_policy {
            Some(value) => std::env::set_var("BLANKET_POLICY", value),
            None => std::env::remove_var("BLANKET_POLICY"),
        }
        assert!(loaded.strict);
        assert!(loaded.deny.contains(FILE_COLLISION));
        assert!(loaded.deny.contains(GIT_DEPENDENCY));
        let _ = fs::remove_dir_all(root);
        assert!(from_member.strict);
        assert!(from_member.deny.contains("file-collision"));
        assert!(from_member.deny.contains("git-dependency"));
    }
}
