//! Policy loading and exception recording (kernel layer): the machine and
//! project policy chain, the exception kinds a sync may wave through, and
//! the collision checks the store consults at commit time.

use crate::kernel::store::Store;
use serde::{Deserialize, Serialize};
use std::collections::BTreeSet;
use std::fs;
use std::io;
use std::path::Path;
#[cfg(not(test))]
use std::sync::Mutex;
use std::sync::OnceLock;

/// A requirement was skipped because it is project-local or a direct reference.
pub const REQUIREMENT_SKIPPED: &str = "requirement-skipped";
/// Two wheels shipped the same path; the later wheel won.
pub const FILE_COLLISION: &str = "file-collision";
/// An install lifecycle script failed but its extracted package was retained.
pub const INSTALL_SCRIPT_FAILED: &str = "install-script-failed";
/// A legacy SHA-1 lock integrity was accepted and verified.
pub const WEAK_INTEGRITY: &str = "weak-integrity";
/// A mutable projection was created without attesting its runtime contents.
pub const UNATTESTED_MUTABLE_STATE: &str = "unattested-mutable-state";
/// A requested toolchain component is not available in the pinned toolchain.
pub const TOOLCHAIN_COMPONENT_UNAVAILABLE: &str = "toolchain-component-unavailable";
/// A future git dependency was accepted without registry provenance.
pub const GIT_DEPENDENCY: &str = "git-dependency";
/// An optional dependency/group was not requested by the user.
pub const SKIPPED_OPTIONAL: &str = "skipped_optional";
/// A manifest named a private index or an index-like option.
pub const UNATTESTED_INDEX: &str = "unattested_index";
/// A lock's content digest did not match its source manifest.
pub const LOCK_DISAGREEMENT: &str = "lock_disagreement";
/// A Cargo.lock was generated by the store Cargo rather than shipped by the
/// source archive.
pub const UNATTESTED_CARGO_LOCK: &str = "unattested_cargo_lock";
/// An install-time download was skipped; the artifact is not in the closure.
pub const ARTIFACT_NOT_PROVISIONED: &str = "artifact_not_provisioned";
/// blanket downloaded and verified an install-time artifact itself; the
/// checksum source is upstream's own manifest (trust-on-first-use).
pub const ARTIFACT_PROVISIONED: &str = "artifact_provisioned";
/// A package that ships prebuilt binaries was compiled from source instead.
pub const BUILT_FROM_SOURCE: &str = "built_from_source";

pub const KINDS: &[&str] = &[
    REQUIREMENT_SKIPPED,
    FILE_COLLISION,
    INSTALL_SCRIPT_FAILED,
    WEAK_INTEGRITY,
    UNATTESTED_MUTABLE_STATE,
    TOOLCHAIN_COMPONENT_UNAVAILABLE,
    GIT_DEPENDENCY,
    SKIPPED_OPTIONAL,
    UNATTESTED_INDEX,
    LOCK_DISAGREEMENT,
    UNATTESTED_CARGO_LOCK,
    ARTIFACT_NOT_PROVISIONED,
    ARTIFACT_PROVISIONED,
    BUILT_FROM_SOURCE,
];

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Exception {
    pub kind: String,
    pub subject: String,
    pub detail: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Policy {
    #[serde(default)]
    pub strict: bool,
    #[serde(default)]
    pub deny: BTreeSet<String>,
}

static POLICY: OnceLock<Policy> = OnceLock::new();
// Production realization is single-threaded and the queue is deliberately
// process-wide so nested tailor calls can contribute to one closure.
#[cfg(not(test))]
static RECORDED: OnceLock<Mutex<Vec<Exception>>> = OnceLock::new();

#[cfg(not(test))]
fn recorded() -> &'static Mutex<Vec<Exception>> {
    RECORDED.get_or_init(|| Mutex::new(Vec::new()))
}

// Unit tests run many independent realizations in parallel. A test-only
// thread-local queue prevents one test's exception from being drained by
// another while preserving the production queue and closure semantics.
#[cfg(test)]
thread_local! {
    static RECORDED: std::cell::RefCell<Vec<Exception>> = const { std::cell::RefCell::new(Vec::new()) };
}

fn with_recorded<R>(f: impl FnOnce(&mut Vec<Exception>) -> R) -> R {
    #[cfg(not(test))]
    {
        f(&mut recorded().lock().unwrap_or_else(|e| e.into_inner()))
    }
    #[cfg(test)]
    {
        RECORDED.with(|recorded| f(&mut recorded.borrow_mut()))
    }
}

/// Parse one policy file, refusing unknown keys and unknown deny kinds.
pub fn parse_file(path: &Path, text: &str) -> io::Result<Policy> {
    let policy: Policy = toml::from_str(text).map_err(|e| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("parse {}: {e}", path.display()),
        )
    })?;
    let unknown: Vec<&str> = policy
        .deny
        .iter()
        .map(String::as_str)
        .filter(|kind| !KINDS.contains(kind))
        .collect();
    if !unknown.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!(
                "{}: unknown deny kind(s): {}; valid kinds: {}",
                path.display(),
                unknown.join(", "),
                KINDS.join(", ")
            ),
        ));
    }
    Ok(policy)
}

fn merge_file(policy: &mut Policy, path: &Path, required: bool) -> io::Result<()> {
    let text = match fs::read_to_string(path) {
        Ok(text) => text,
        Err(e) if e.kind() == io::ErrorKind::NotFound && !required => return Ok(()),
        Err(e) => {
            return Err(io::Error::new(
                e.kind(),
                format!("read {}: {e}", path.display()),
            ))
        }
    };
    let other = parse_file(path, &text)?;
    union(policy, &other);
    Ok(())
}

/// Union `other` into `policy`. Union only tightens: the result denies
/// everything `policy` denied plus everything `other` denies, and is strict
/// if either is. Used by `blanket audit --policy`, so a file handed to the
/// gate can never loosen the machine or project policy.
pub fn union(policy: &mut Policy, other: &Policy) {
    policy.strict |= other.strict;
    policy.deny.extend(other.deny.iter().cloned());
}

/// Load the user and project policies once, unioning all deny entries.
pub fn load(project_dir: &Path, cli_strict: bool) -> io::Result<Policy> {
    let mut policy = Policy::default();
    if let Some(path) = std::env::var_os("BLANKET_POLICY") {
        merge_file(&mut policy, Path::new(&path), true)?;
    } else if let Some(home) = std::env::var_os("HOME") {
        merge_file(
            &mut policy,
            &Path::new(&home).join(".blanket/policy.toml"),
            false,
        )?;
    }
    // Every ancestor's project policy applies (union only tightens), so a
    // workspace-root policy governs builds started in a member directory
    // without blanket having to know each ecosystem's rooting rule.
    for dir in project_dir.ancestors() {
        merge_file(&mut policy, &dir.join(".blanket/policy.toml"), false)?;
    }
    policy.strict |= cli_strict || std::env::var("BLANKET_STRICT").as_deref() == Ok("1");
    Ok(policy)
}

/// Initialize the process policy. Repeated calls keep the first loaded policy.
pub fn init(project_dir: &Path, cli_strict: bool) -> io::Result<()> {
    if POLICY.get().is_none() {
        let _ = POLICY.set(load(project_dir, cli_strict)?);
    }
    Ok(())
}

fn current() -> &'static Policy {
    POLICY.get_or_init(Policy::default)
}

/// Whether `policy` refuses an exception of `kind`.
pub fn denied(policy: &Policy, kind: &str) -> bool {
    policy.strict || policy.deny.contains(kind)
}

pub fn record_with(policy: &Policy, kind: &str, subject: &str, detail: &str) -> io::Result<()> {
    if denied(policy, kind) {
        return Err(io::Error::new(
            io::ErrorKind::PermissionDenied,
            format!(
                "policy denies {kind}: {subject}: {detail} (see .blanket/policy.toml / BLANKET_STRICT)"
            ),
        ));
    }
    eprintln!("blanket: exception {kind}: {subject}: {detail}");
    with_recorded(|recorded| {
        recorded.push(Exception {
            kind: kind.into(),
            subject: subject.into(),
            detail: detail.into(),
        })
    });
    Ok(())
}

pub fn record(kind: &str, subject: &str, detail: &str) -> io::Result<()> {
    record_with(current(), kind, subject, detail)
}

/// Return and clear all exceptions recorded by this process.
pub fn drain() -> Vec<Exception> {
    with_recorded(std::mem::take)
}

/// Inspect the pending exceptions for diagnostics and tests.
///
/// Closure publication must use `claim_for_closure`, which checks the active
/// attribution scope and owning thread before draining the queue.
pub fn pending() -> Vec<Exception> {
    with_recorded(|recorded| recorded.clone())
}

/// Clear pending exceptions for diagnostics and test cleanup.
///
/// Production closure publication must use `claim_for_closure` so ownership
/// and attribution are enforced at the publication boundary.
pub fn clear() {
    with_recorded(|recorded| recorded.clear())
}

/// Ownership of the pending-exception queue for the span of one ecosystem's
/// realization. Held by `commands::sync` across the whole `Tailor::sync`
/// call; see `begin_attribution`.
///
/// The guard is what makes attribution sound, so it must outlive the
/// realization it names: binding it to `_` would drop it immediately and
/// reopen the hole.
#[must_use = "the attribution scope must be held across the realization it owns"]
#[derive(Debug)]
pub struct AttributionScope {
    ecosystem: String,
    // Dropped after `Drop::drop` runs, so the queue is cleared while this
    // process still owns it.
    _serial: std::sync::MutexGuard<'static, ()>,
}

impl AttributionScope {
    /// The ecosystem this scope attributes exceptions to.
    pub fn ecosystem(&self) -> &str {
        &self.ecosystem
    }

    /// Finish a successful realization after its closure has been published.
    ///
    /// This is the success path. A non-empty queue means the tailor either
    /// published no closure or recorded an exception after publication, so
    /// report the unclaimed exceptions. Consuming `self` then runs `Drop`,
    /// which releases ownership and clears the queue even on that error path.
    pub fn finish(self) -> io::Result<()> {
        let pending = pending();
        if pending.is_empty() {
            return Ok(());
        }
        Err(io::Error::other(format!(
            "{} realization ended with {} exception(s) never claimed by a closure: {}",
            self.ecosystem,
            pending.len(),
            format_exception_list(&pending)
        )))
    }

    /// Explicitly discard exceptions that belong to an operation with no
    /// closure, such as a dependency-file edit.
    pub fn discard(self) {
        clear();
    }
}

impl Drop for AttributionScope {
    fn drop(&mut self) {
        // Cleanup for error and panic paths. Successful realizations call
        // `finish`, and operations with no closure call `discard`.
        clear();
        clear_attribution_owner();
    }
}

fn attribution_lock() -> &'static std::sync::Mutex<()> {
    static LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());
    &LOCK
}

fn attribution_owner() -> &'static std::sync::Mutex<Option<std::thread::ThreadId>> {
    static OWNER: std::sync::Mutex<Option<std::thread::ThreadId>> = std::sync::Mutex::new(None);
    &OWNER
}

fn clear_attribution_owner() {
    let mut owner = attribution_owner()
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner());
    *owner = None;
}

fn format_exception_list(exceptions: &[Exception]) -> String {
    exceptions
        .iter()
        .map(|exception| {
            format!(
                "{}: {}: {}",
                exception.kind, exception.subject, exception.detail
            )
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Take ownership of the pending-exception queue for `ecosystem`'s
/// realization, refusing if anyone else already owns it or if the queue is
/// not empty.
///
/// The queue is process-wide and a closure claims all of it through
/// `claim_for_closure`. Attribution is therefore only sound while exactly one
/// ecosystem is realizing. `blanket audit` reads that attribution as
/// authority, so a silent cross-attribution is a correctness hole, not a
/// cosmetic one (FOLLOW-UPS H6).
///
/// Checking for an empty queue alone could not deliver that: two realizations
/// could both observe an empty queue and then record into it, and a closure
/// could claim exceptions from a different realization. The mutex is what
/// makes the check mean something; the emptiness check is what catches a leak
/// from whatever ran before.
///
/// Contention is a named `WouldBlock` error rather than a wait, the same
/// convention `supervise::Session::new` uses for process-wide signal
/// dispositions: no production path realizes two ecosystems at once, so
/// contention is a programming error to report, never a race to absorb.
///
/// This is a real runtime check rather than a `debug_assert!` because the
/// failure is invisible in the release build users actually run.
pub fn begin_attribution(ecosystem: &str) -> io::Result<AttributionScope> {
    let serial = match attribution_lock().try_lock() {
        Ok(guard) => guard,
        // A poisoned lock means a previous scope's owner panicked. `Drop`
        // cleared the queue on the way out either way, so adopt the guard
        // rather than refusing every later realization in this process.
        Err(std::sync::TryLockError::Poisoned(error)) => error.into_inner(),
        Err(std::sync::TryLockError::WouldBlock) => {
            return Err(io::Error::new(
                io::ErrorKind::WouldBlock,
                format!(
                    "another ecosystem's attribution scope is already open in this \
                     process, so {ecosystem} cannot start realizing: the pending \
                     exception queue is process-wide and one closure claims all of it"
                ),
            ));
        }
    };
    let leaked = pending();
    if !leaked.is_empty() {
        return Err(io::Error::other(format!(
            "{} exception(s) were still queued when {ecosystem} realization began; \
             the {ecosystem} closure would claim exceptions it did not cause: {}",
            leaked.len(),
            format_exception_list(&leaked)
        )));
    }
    *attribution_owner()
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner()) = Some(std::thread::current().id());
    Ok(AttributionScope {
        ecosystem: ecosystem.to_string(),
        _serial: serial,
    })
}

/// Claim all exceptions for the closure being published by the active
/// realization. This is the only production publication boundary: it refuses
/// a missing scope or a caller on a different thread, then returns and clears
/// the queue for the owning scope.
pub fn claim_for_closure() -> io::Result<Vec<Exception>> {
    let current = std::thread::current().id();
    let owner = attribution_owner()
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner());
    match owner.as_ref() {
        None => {
            return Err(io::Error::other(
                "closure publication outside an attribution scope: no scope is active",
            ));
        }
        Some(owner) if *owner != current => {
            return Err(io::Error::other(
                "closure publication outside an attribution scope: the active scope belongs to another thread",
            ));
        }
        Some(_) => {}
    }
    drop(owner);
    Ok(drain())
}

/// Exceptions that change the bytes of the object being built.
pub fn object_exceptions() -> Vec<Exception> {
    with_recorded(|recorded| {
        recorded
            .iter()
            .filter(|e| {
                matches!(
                    e.kind.as_str(),
                    FILE_COLLISION | INSTALL_SCRIPT_FAILED | GIT_DEPENDENCY | UNATTESTED_CARGO_LOCK
                )
            })
            .cloned()
            .collect()
    })
}

/// Refuse a cached object when its recorded exceptions are denied now.
pub fn check_cached(store: &Store, id: &str) -> io::Result<()> {
    let activity = store.activity(crate::kernel::activity::ActivityMode::Shared)?;
    check_cached_with_activity(store, &activity, id)
}

pub fn check_cached_with_activity(
    store: &Store,
    activity: &crate::kernel::activity::StoreActivity,
    id: &str,
) -> io::Result<()> {
    store.require_activity(activity, "cached policy check")?;
    let exceptions = store.exceptions(id)?;
    check_exception_set(id, &exceptions)?;
    for exception in &exceptions {
        record(&exception.kind, &exception.subject, &exception.detail)?;
    }
    Ok(())
}

pub(crate) fn check_exception_set(id: &str, exceptions: &[Exception]) -> io::Result<()> {
    if exceptions.is_empty() {
        return Ok(());
    }
    let denied_kinds: Vec<&str> = exceptions
        .iter()
        .filter(|e| denied(current(), &e.kind))
        .map(|e| e.kind.as_str())
        .collect();
    if denied_kinds.is_empty() {
        return Ok(());
    }
    Err(io::Error::new(
        io::ErrorKind::PermissionDenied,
        format!(
            "cached object {id} carries exception(s): {}; blanket sync --fresh will not help; rebuild the object under a permissive policy or fix the cause",
            denied_kinds.join(", ")
        ),
    ))
}

/// Tests that read or set `HOME` / `BLANKET_POLICY` hold this lock: the
/// environment is process-global, so a test that mutates it would otherwise
/// redirect a concurrent `load` (the same hazard as `store::STORE_ENV_LOCK`).
#[cfg(test)]
pub(crate) fn test_env_lock() -> std::sync::MutexGuard<'static, ()> {
    static LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());
    LOCK.lock().unwrap_or_else(|poisoned| poisoned.into_inner())
}

/// Tests that open an `AttributionScope` queue here, then start from an empty
/// pending list. When a test also needs the environment, supervision, and
/// store guards, acquire them in this order: env, supervision, store,
/// attribution.
///
/// `begin_attribution` reports contention as an error instead of waiting, so
/// two overlapping tests would fail each other rather than serialize. This is
/// deliberately not the tests' own `exception_guard`: the scope lock is a
/// production primitive and attribution tests live in more than one module
/// (`kernel::policy` and `commands::deps`), so they need one lock they can
/// all name.
#[cfg(test)]
pub(crate) fn attribution_test_lock() -> std::sync::MutexGuard<'static, ()> {
    static LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());
    let guard = LOCK.lock().unwrap_or_else(|poisoned| poisoned.into_inner());
    clear();
    guard
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The pending-exception list is process-global, so the tests that assert
    /// on its contents must not overlap — with each other or with any other
    /// test that records. Same guard the npm_scripts integration tests use:
    /// take the lock, then start from an empty list.
    fn exception_guard() -> std::sync::MutexGuard<'static, ()> {
        static LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());
        let guard = LOCK.lock().unwrap_or_else(|poisoned| poisoned.into_inner());
        clear();
        guard
    }

    #[test]
    fn parses_policy_and_rejects_unknown_keys() {
        let policy = toml::from_str::<Policy>(
            r#"strict = true
deny = ["git-dependency"]"#,
        )
        .unwrap();
        assert!(policy.strict);
        assert!(policy.deny.contains("git-dependency"));
        assert!(toml::from_str::<Policy>("wat = true").is_err());
        let error = parse_file(Path::new("policy.toml"), "deny = [\"typo\"]").unwrap_err();
        assert!(error.to_string().contains("valid kinds:"));
    }

    #[test]
    fn union_semantics_adds_all_deny_entries() {
        let mut merged = Policy::default();
        for text in [r#"deny = ["x"]"#, r#"deny = ["y"]"#] {
            let other = toml::from_str::<Policy>(text).unwrap();
            merged.strict |= other.strict;
            merged.deny.extend(other.deny);
        }
        assert!(denied(&merged, "x"));
        assert!(denied(&merged, "y"));
    }

    #[test]
    fn record_denied_and_allowed() {
        let _guard = exception_guard();
        assert!(record_with(
            &Policy {
                strict: true,
                deny: BTreeSet::new()
            },
            "x",
            "s",
            "d"
        )
        .is_err());
        record_with(&Policy::default(), "x", "s", "d").unwrap();
        assert_eq!(drain().len(), 1);
    }

    /// Clears the pending list on every exit path, a panic included. A test
    /// that left an exception queued would hand it to the next test on this
    /// thread, and the guard under test is exactly the thing that turns a
    /// stray queued exception into a failure.
    struct ClearOnDrop;
    impl Drop for ClearOnDrop {
        fn drop(&mut self) {
            clear();
        }
    }

    /// Attribution of an exception to a closure depends on the queue being
    /// empty when each ecosystem starts realizing; `commands::sync` opens a
    /// scope per ecosystem so a future concurrent sync cannot cross-attribute
    /// in silence (FOLLOW-UPS H6).
    #[test]
    fn pending_exceptions_refuse_the_next_ecosystem_realization() {
        let _guard = attribution_test_lock();
        let _clear = ClearOnDrop;
        record_with(
            &Policy::default(),
            INSTALL_SCRIPT_FAILED,
            "left-pad@1.3.0",
            "postinstall exited 1",
        )
        .unwrap();
        let error = begin_attribution("cargo").unwrap_err();
        assert_eq!(error.kind(), io::ErrorKind::Other);
        let text = error.to_string();
        assert!(text.contains(INSTALL_SCRIPT_FAILED), "{text}");
        assert!(text.contains("left-pad@1.3.0"), "{text}");
        assert!(text.contains("cargo"), "{text}");
    }

    #[test]
    fn finish_succeeds_after_a_closure_claims_every_exception() {
        let _guard = attribution_test_lock();
        let _clear = ClearOnDrop;
        assert!(pending().is_empty());
        let scope = begin_attribution("python").unwrap();
        assert_eq!(scope.ecosystem(), "python");
        assert!(claim_for_closure().unwrap().is_empty());
        scope.finish().unwrap();
        let next = begin_attribution("node").unwrap();
        next.discard();
    }

    #[test]
    fn finish_reports_unclaimed_exceptions_and_clears_them() {
        let _guard = attribution_test_lock();
        let _clear = ClearOnDrop;
        let scope = begin_attribution("python").unwrap();
        record_with(
            &Policy::default(),
            SKIPPED_OPTIONAL,
            "[dependency-groups]",
            "excluded by default",
        )
        .unwrap();
        let error = scope.finish().unwrap_err();
        let text = error.to_string();
        assert!(
            text.contains(
                "python realization ended with 1 exception(s) never claimed by a closure"
            ),
            "{text}"
        );
        assert!(text.contains(SKIPPED_OPTIONAL), "{text}");
        assert!(text.contains("[dependency-groups]"), "{text}");
        assert!(pending().is_empty());
        let next = begin_attribution("node").unwrap();
        next.discard();
    }

    #[test]
    fn discard_clears_exceptions_for_an_operation_without_a_closure() {
        let _guard = attribution_test_lock();
        let _clear = ClearOnDrop;
        let scope = begin_attribution("dependency-edit").unwrap();
        record_with(
            &Policy::default(),
            SKIPPED_OPTIONAL,
            "dependency-edit",
            "fixture",
        )
        .unwrap();
        scope.discard();
        assert!(pending().is_empty());
        let next = begin_attribution("node").unwrap();
        next.discard();
    }

    /// Closure publication is the only production code that clears the queue,
    /// so a tailor that records an allowed exception and then fails would
    /// leave it behind for the next ecosystem. `Drop` is the cleanup that
    /// covers the error and panic paths (Sol review, should #3).
    #[test]
    fn dropping_a_scope_clears_exceptions_the_closure_never_claimed() {
        let _guard = attribution_test_lock();
        let _clear = ClearOnDrop;
        let scope = begin_attribution("python").unwrap();
        record_with(
            &Policy::default(),
            SKIPPED_OPTIONAL,
            "[dependency-groups]",
            "excluded by default",
        )
        .unwrap();
        assert_eq!(pending().len(), 1);
        drop(scope);
        assert!(
            pending().is_empty(),
            "a scope that ended without a closure write left its exceptions queued"
        );
        // And the next ecosystem can therefore start.
        let _next = begin_attribution("node").unwrap();
    }

    #[test]
    fn closure_claim_requires_an_active_scope_on_the_calling_thread() {
        let _guard = attribution_test_lock();
        let _clear = ClearOnDrop;
        let error = claim_for_closure().unwrap_err();
        assert!(error
            .to_string()
            .contains("closure publication outside an attribution scope"));

        let scope = begin_attribution("python").unwrap();
        record_with(
            &Policy::default(),
            SKIPPED_OPTIONAL,
            "thread-check",
            "fixture",
        )
        .unwrap();
        let error = std::thread::spawn(claim_for_closure)
            .join()
            .unwrap()
            .unwrap_err();
        assert!(error
            .to_string()
            .contains("closure publication outside an attribution scope"));
        let claimed = claim_for_closure().unwrap();
        assert_eq!(claimed.len(), 1);
        scope.finish().unwrap();
    }

    /// The emptiness check alone could not stop two realizations from both
    /// observing an empty queue and then recording into it. The scope is
    /// exclusive, and contention is a named error rather than a wait — the
    /// same convention `supervise::Session::new` uses (Sol review, blocker
    /// #2).
    #[test]
    fn a_second_attribution_scope_is_refused_while_the_first_is_open() {
        let _guard = attribution_test_lock();
        let _clear = ClearOnDrop;
        let (opened_tx, opened_rx) = std::sync::mpsc::channel::<()>();
        let (release_tx, release_rx) = std::sync::mpsc::channel::<()>();
        // The scope holds a `MutexGuard`, so it is `!Send`: the owning thread
        // has to build it and drop it itself.
        let owner = std::thread::spawn(move || {
            let scope = begin_attribution("python").unwrap();
            opened_tx.send(()).unwrap();
            release_rx.recv().unwrap();
            drop(scope);
        });
        opened_rx.recv().unwrap();
        let error = begin_attribution("node").unwrap_err();
        assert_eq!(error.kind(), io::ErrorKind::WouldBlock);
        let text = error.to_string();
        assert!(text.contains("attribution scope"), "{text}");
        assert!(text.contains("node"), "{text}");
        release_tx.send(()).unwrap();
        owner.join().unwrap();
        // Once the first scope is gone the next ecosystem may start.
        let _next = begin_attribution("node").unwrap();
    }

    #[test]
    fn drain_clears() {
        let _guard = exception_guard();
        record_with(&Policy::default(), "x", "s", "d").unwrap();
        assert_eq!(drain().len(), 1);
        assert!(drain().is_empty());
    }

    #[test]
    fn recorded_exceptions_do_not_cross_test_threads() {
        let _guard = exception_guard();
        std::thread::spawn(|| {
            record_with(&Policy::default(), "thread-only", "s", "d").unwrap();
            assert_eq!(drain().len(), 1);
        })
        .join()
        .unwrap();
        assert!(pending().is_empty());
    }

    #[test]
    fn loads_user_and_project_policy_union_from_files() {
        let root = std::env::temp_dir().join(format!(
            "blanket-policy-test-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        let home = root.join("home");
        let project = root.join("project");
        fs::create_dir_all(home.join(".blanket")).unwrap();
        fs::create_dir_all(project.join(".blanket")).unwrap();
        fs::write(
            home.join(".blanket/policy.toml"),
            "deny = [\"git-dependency\"]\n",
        )
        .unwrap();
        fs::write(
            project.join(".blanket/policy.toml"),
            "strict = true\ndeny = [\"file-collision\"]\n",
        )
        .unwrap();
        let _env = test_env_lock();
        let old_home = std::env::var_os("HOME");
        let old_policy = std::env::var_os("BLANKET_POLICY");
        std::env::set_var("HOME", &home);
        std::env::remove_var("BLANKET_POLICY");
        let loaded = load(&project, false).unwrap();
        // Ancestor rule: a workspace member inherits the root's policy.
        let member = project.join("crates/member");
        fs::create_dir_all(&member).unwrap();
        let from_member = load(&member, false).unwrap();
        match old_home {
            Some(value) => std::env::set_var("HOME", value),
            None => std::env::remove_var("HOME"),
        }
        match old_policy {
            Some(value) => std::env::set_var("BLANKET_POLICY", value),
            None => std::env::remove_var("BLANKET_POLICY"),
        }
        assert!(loaded.strict);
        assert!(loaded.deny.contains(FILE_COLLISION));
        assert!(loaded.deny.contains(GIT_DEPENDENCY));
        let _ = fs::remove_dir_all(root);
        assert!(from_member.strict);
        assert!(from_member.deny.contains("file-collision"));
        assert!(from_member.deny.contains("git-dependency"));
    }
}
