//! Policy loading and exception recording (kernel layer): the machine and
//! project policy chain, the exception kinds a sync may wave through, and
//! the collision checks the store consults at commit time.

use crate::kernel::signing::{self, KeySet};
use crate::kernel::store::Store;
use serde::{Deserialize, Serialize};
use std::collections::BTreeSet;
use std::fs;
use std::io;
#[cfg(unix)]
use std::os::unix::fs::MetadataExt;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Mutex, OnceLock};

/// A requirement was skipped because it is project-local or a direct reference.
pub const REQUIREMENT_SKIPPED: &str = "requirement-skipped";
/// Two wheels shipped the same path; the later wheel won.
pub const FILE_COLLISION: &str = "file-collision";
/// An install lifecycle script failed but its extracted package was retained.
pub const INSTALL_SCRIPT_FAILED: &str = "install-script-failed";
/// A legacy SHA-1 lock integrity was accepted and verified.
pub const WEAK_INTEGRITY: &str = "weak-integrity";
/// A mutable projection was created without attesting its runtime contents.
pub const UNATTESTED_MUTABLE_STATE: &str = "unattested-mutable-state";
/// A requested toolchain component is not available in the pinned toolchain.
pub const TOOLCHAIN_COMPONENT_UNAVAILABLE: &str = "toolchain-component-unavailable";
/// A future git dependency was accepted without registry provenance.
pub const GIT_DEPENDENCY: &str = "git-dependency";
/// An optional dependency/group was not requested by the user.
pub const SKIPPED_OPTIONAL: &str = "skipped_optional";
/// A manifest named a private index or an index-like option.
pub const UNATTESTED_INDEX: &str = "unattested_index";
/// A lock's content digest did not match its source manifest.
pub const LOCK_DISAGREEMENT: &str = "lock_disagreement";
/// A Cargo.lock was generated by the store Cargo rather than shipped by the
/// source archive.
pub const UNATTESTED_CARGO_LOCK: &str = "unattested_cargo_lock";
/// An install-time download was skipped; the artifact is not in the closure.
pub const ARTIFACT_NOT_PROVISIONED: &str = "artifact_not_provisioned";
/// tog downloaded and verified an install-time artifact itself; the
/// checksum source is upstream's own manifest (trust-on-first-use).
pub const ARTIFACT_PROVISIONED: &str = "artifact_provisioned";
/// A package that ships prebuilt binaries was compiled from source instead.
pub const BUILT_FROM_SOURCE: &str = "built_from_source";

pub const KINDS: &[&str] = &[
    REQUIREMENT_SKIPPED,
    FILE_COLLISION,
    INSTALL_SCRIPT_FAILED,
    WEAK_INTEGRITY,
    UNATTESTED_MUTABLE_STATE,
    TOOLCHAIN_COMPONENT_UNAVAILABLE,
    GIT_DEPENDENCY,
    SKIPPED_OPTIONAL,
    UNATTESTED_INDEX,
    LOCK_DISAGREEMENT,
    UNATTESTED_CARGO_LOCK,
    ARTIFACT_NOT_PROVISIONED,
    ARTIFACT_PROVISIONED,
    BUILT_FROM_SOURCE,
];

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Exception {
    pub kind: String,
    pub subject: String,
    pub detail: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Policy {
    #[serde(default)]
    pub strict: bool,
    #[serde(default)]
    pub deny: BTreeSet<String>,
    /// The `[signing]` table. In a parsed file it is what that scope
    /// declared; in a merged chain it is the effective trusted set, `None`
    /// while no machine-scope policy has introduced one. Absent and empty
    /// are different states: absent means "not configured" (an operator
    /// mistake for `tog audit`), empty means "trust nobody".
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub signing: Option<Signing>,
}

/// The `[signing]` policy table: the public keys whose closure signatures
/// `tog audit` accepts. Every other command parses it and ignores it.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Signing {
    /// `ed25519:<64 hex>` entries, decoded and deduplicated on the key
    /// bytes. Required: a `[signing]` table that says nothing is refused.
    pub trusted: KeySet,
}

static POLICY: OnceLock<Policy> = OnceLock::new();

#[derive(Debug)]
struct Frame {
    id: u64,
    owner: std::thread::ThreadId,
    ecosystem: String,
    exceptions: Vec<Exception>,
    claimed: bool,
    published: bool,
}

static FRAMES: OnceLock<Mutex<Vec<Frame>>> = OnceLock::new();
static NEXT_FRAME_ID: AtomicU64 = AtomicU64::new(1);

fn frames() -> &'static Mutex<Vec<Frame>> {
    FRAMES.get_or_init(|| Mutex::new(Vec::new()))
}

fn with_frames<R>(f: impl FnOnce(&mut Vec<Frame>) -> R) -> R {
    f(&mut frames().lock().unwrap_or_else(|error| error.into_inner()))
}

/// Parse one policy file, refusing unknown keys and unknown deny kinds.
pub fn parse_file(path: &Path, text: &str) -> io::Result<Policy> {
    let policy: Policy = toml::from_str(text).map_err(|e| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("parse {}: {e}", path.display()),
        )
    })?;
    let unknown: Vec<&str> = policy
        .deny
        .iter()
        .map(String::as_str)
        .filter(|kind| !KINDS.contains(kind))
        .collect();
    if !unknown.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!(
                "{}: unknown deny kind(s): {}; valid kinds: {}",
                path.display(),
                unknown.join(", "),
                KINDS.join(", ")
            ),
        ));
    }
    Ok(policy)
}

fn merge_file(
    policy: &mut Policy,
    sources: &mut Vec<PolicySource>,
    path: &Path,
    required: bool,
    origin: SourceOrigin,
) -> io::Result<bool> {
    let text = match fs::read_to_string(path) {
        Ok(text) => text,
        Err(e) if e.kind() == io::ErrorKind::NotFound && !required => return Ok(false),
        Err(e) => {
            return Err(io::Error::new(
                e.kind(),
                format!("read {}: {e}", path.display()),
            ))
        }
    };
    let other = parse_file(path, &text)?;
    merge(policy, &other, origin);
    // Only a file that existed and was merged is a source; the optional
    // files that were not there contributed nothing to attribute.
    sources.push(PolicySource::from_file(origin, path, &other));
    Ok(true)
}

#[cfg(unix)]
type PathIdentity = (u64, u64);

#[cfg(not(unix))]
type PathIdentity = PathBuf;

/// Identify an existing path by its filesystem identity. This catches hard
/// links and bind mounts that do not share a pathname.
#[cfg(unix)]
fn path_identity(path: &Path) -> Option<PathIdentity> {
    fs::metadata(path)
        .ok()
        .map(|metadata| (metadata.dev(), metadata.ino()))
}

/// Identify a path by its canonical spelling on platforms without Unix file
/// identity fields.
#[cfg(not(unix))]
fn path_identity(path: &Path) -> Option<PathIdentity> {
    Some(fs::canonicalize(path).unwrap_or_else(|_| path.to_path_buf()))
}

/// Union `other` into `policy`. Union only tightens: the result denies
/// everything `policy` denied plus everything `other` denies, and is strict
/// if either is. Deny and strictness are scope-free, so this ignores the
/// `[signing]` table; `merge` applies it by origin.
pub fn union(policy: &mut Policy, other: &Policy) {
    policy.strict |= other.strict;
    policy.deny.extend(other.deny.iter().cloned());
}

/// Merge one scope's policy into the chain: `union` for deny and
/// strictness, and the origin rule for signing trust. Only the machine
/// scope introduces a trusted set; a project or `--policy` file intersects
/// with it, so a working tree can drop keys but never vouch for its own.
/// A scope with no `[signing]` table leaves the set unchanged, and a
/// project or flag list seen before any machine declaration cannot
/// initialize it: trust stays unconfigured. Used by `tog audit
/// --policy` too, so the file handed to the gate can never loosen the
/// machine or project policy.
pub fn merge(policy: &mut Policy, other: &Policy, origin: SourceOrigin) {
    union(policy, other);
    match origin {
        SourceOrigin::Machine => {
            if let Some(declared) = &other.signing {
                policy.signing = Some(declared.clone());
            }
        }
        SourceOrigin::Project | SourceOrigin::Flag => {
            if let (Some(effective), Some(declared)) = (policy.signing.as_mut(), &other.signing) {
                signing::intersect(&mut effective.trusted, &declared.trusted);
            }
        }
        SourceOrigin::Env => {}
    }
}

/// Where one contributing policy came from. The serialized names
/// (`machine`, `project`, `flag`, `env`) are the stable strings
/// `tog audit --json` reports under `policy.sources`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SourceOrigin {
    /// `TOG_POLICY`, or `$HOME/.tog/policy.toml` when it is unset.
    Machine,
    /// An ancestor directory's `.tog/policy.toml`.
    Project,
    /// A file named by `tog audit --policy`. Other commands may also use
    /// this origin for their `--strict` flag; audit uses it only for the file.
    Flag,
    /// `TOG_STRICT=1`. Not a file: `path` is absent.
    Env,
}

impl SourceOrigin {
    /// The same lowercase name the serializer writes; a unit test pins the
    /// two together so the report's contract cannot drift.
    pub fn as_str(self) -> &'static str {
        match self {
            SourceOrigin::Machine => "machine",
            SourceOrigin::Project => "project",
            SourceOrigin::Flag => "flag",
            SourceOrigin::Env => "env",
        }
    }
}

impl std::fmt::Display for SourceOrigin {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// One policy that contributed to a merged `Policy`, and what it said.
/// `union` is silent about provenance, so a report that only shows the
/// merged deny set cannot say which file asked for a denial; this is that
/// missing half.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PolicySource {
    pub origin: SourceOrigin,
    /// The file that was read, absent for strictness sources.
    pub path: Option<PathBuf>,
    pub strict: bool,
    pub deny: BTreeSet<String>,
    /// The `[signing] trusted` list this scope declared: `None` when the
    /// file has no `[signing]` table, `Some` (possibly empty) when it does.
    /// Shown per scope so a key the machine does not trust is visible in
    /// the project list that named it.
    pub trusted: Option<KeySet>,
}

impl PolicySource {
    /// The entry for a policy read from `path`, including one merged in
    /// from outside the chain (`tog audit --policy`).
    pub fn from_file(origin: SourceOrigin, path: &Path, policy: &Policy) -> Self {
        Self {
            origin,
            path: Some(path.to_path_buf()),
            strict: policy.strict,
            deny: policy.deny.clone(),
            trusted: policy
                .signing
                .as_ref()
                .map(|signing| signing.trusted.clone()),
        }
    }
}

/// Load the machine and project policies, unioning all deny entries.
pub fn load(project_dir: &Path, cli_strict: bool) -> io::Result<Policy> {
    Ok(load_with_sources(project_dir, cli_strict)?.0)
}

/// `load`, plus every policy that contributed, in merge order. One loading
/// algorithm serves both: `load` is this with the provenance discarded.
/// Callers that pass `cli_strict=true` (currently the sync command for its
/// strict switch) can produce a `flag` source; audit passes `false` and adds
/// its separately parsed policy file as a source.
pub fn load_with_sources(
    project_dir: &Path,
    cli_strict: bool,
) -> io::Result<(Policy, Vec<PolicySource>)> {
    let mut policy = Policy::default();
    let mut sources = Vec::new();
    let machine_path = if let Some(path) = std::env::var_os("TOG_POLICY") {
        let path = PathBuf::from(path);
        merge_file(
            &mut policy,
            &mut sources,
            &path,
            true,
            SourceOrigin::Machine,
        )?;
        path_identity(&path)
    } else if let Some(home) = std::env::var_os("HOME") {
        let path = PathBuf::from(home).join(".tog/policy.toml");
        let loaded = merge_file(
            &mut policy,
            &mut sources,
            &path,
            false,
            SourceOrigin::Machine,
        )?;
        loaded.then(|| path_identity(&path)).flatten()
    } else {
        None
    };
    // Every ancestor's project policy applies (union only tightens), so a
    // workspace-root policy governs builds started in a member directory
    // without tog having to know each ecosystem's rooting rule.
    for dir in project_dir.ancestors() {
        let path = dir.join(".tog/policy.toml");
        if machine_path
            .as_ref()
            .is_some_and(|machine| path_identity(&path).as_ref() == Some(machine))
        {
            continue;
        }
        merge_file(
            &mut policy,
            &mut sources,
            &path,
            false,
            SourceOrigin::Project,
        )?;
    }
    let env_strict = std::env::var("TOG_STRICT").as_deref() == Ok("1");
    policy.strict |= cli_strict || env_strict;
    if cli_strict {
        sources.push(PolicySource {
            origin: SourceOrigin::Flag,
            path: None,
            strict: true,
            deny: BTreeSet::new(),
            trusted: None,
        });
    }
    if env_strict {
        sources.push(PolicySource {
            origin: SourceOrigin::Env,
            path: None,
            strict: true,
            deny: BTreeSet::new(),
            trusted: None,
        });
    }
    Ok((policy, sources))
}

/// Initialize the process policy. Repeated calls keep the first loaded policy.
pub fn init(project_dir: &Path, cli_strict: bool) -> io::Result<()> {
    if POLICY.get().is_none() {
        let _ = POLICY.set(load(project_dir, cli_strict)?);
    }
    Ok(())
}

fn current() -> &'static Policy {
    POLICY.get_or_init(Policy::default)
}

/// Whether `policy` refuses an exception of `kind`.
pub fn denied(policy: &Policy, kind: &str) -> bool {
    policy.strict || policy.deny.contains(kind)
}

pub fn record_with(policy: &Policy, kind: &str, subject: &str, detail: &str) -> io::Result<()> {
    with_frames(|frames| {
        let Some(frame) = frames.last_mut() else {
            return Err(io::Error::other(
                "exception recorded outside any attribution",
            ));
        };
        // Records belong to the thread that opened the innermost frame. A
        // worker thread recording into another realization's frame would be
        // claimed by that realization's closure.
        if frame.owner != std::thread::current().id() {
            return Err(io::Error::other(format!(
                "exception {kind} recorded from a thread that does not own the {} attribution",
                frame.ecosystem
            )));
        }
        if denied(policy, kind) {
            return Err(io::Error::new(
                io::ErrorKind::PermissionDenied,
                format!(
                    "policy denies {kind}: {subject}: {detail} (see .tog/policy.toml / TOG_STRICT)"
                ),
            ));
        }
        eprintln!("tog: exception {kind}: {subject}: {detail}");
        frame.exceptions.push(Exception {
            kind: kind.into(),
            subject: subject.into(),
            detail: detail.into(),
        });
        Ok(())
    })
}

pub fn record(kind: &str, subject: &str, detail: &str) -> io::Result<()> {
    record_with(current(), kind, subject, detail)
}

fn format_exception_list(exceptions: &[Exception]) -> String {
    exceptions
        .iter()
        .map(|exception| {
            format!(
                "{}: {}: {}",
                exception.kind, exception.subject, exception.detail
            )
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// A value that owns one frame in the process-global attribution stack.
#[must_use = "an attribution must be held across the realization it owns"]
#[derive(Debug)]
pub struct Attribution {
    id: u64,
    ecosystem: String,
    active: bool,
}

impl Attribution {
    /// Open a realization frame. A different thread may not open over the
    /// current innermost frame because records are process-global.
    pub fn open(ecosystem: &str) -> io::Result<Self> {
        let owner = std::thread::current().id();
        with_frames(|frames| {
            if let Some(frame) = frames.last() {
                if frame.owner != owner {
                    return Err(io::Error::new(
                        io::ErrorKind::WouldBlock,
                        format!(
                            "another thread owns the innermost attribution for {}; {ecosystem} cannot open",
                            frame.ecosystem
                        ),
                    ));
                }
            }
            let id = NEXT_FRAME_ID.fetch_add(1, Ordering::Relaxed);
            frames.push(Frame {
                id,
                owner,
                ecosystem: ecosystem.to_string(),
                exceptions: Vec::new(),
                claimed: false,
                published: false,
            });
            Ok(Self {
                id,
                ecosystem: ecosystem.to_string(),
                active: true,
            })
        })
    }

    /// Open a child realization owned by this token's thread. Records while
    /// it is open belong to the child and cannot be claimed by the parent.
    pub fn nested(&mut self, ecosystem: &str) -> io::Result<Self> {
        let owner = std::thread::current().id();
        with_frames(|frames| {
            let Some(parent) = frames.last() else {
                return Err(io::Error::other(
                    "cannot nest attribution without an open frame",
                ));
            };
            if parent.id != self.id {
                return Err(io::Error::other(
                    "cannot nest attribution while another child frame is open",
                ));
            }
            if parent.owner != owner {
                return Err(io::Error::new(
                    io::ErrorKind::WouldBlock,
                    "cannot nest attribution from another thread",
                ));
            }
            let id = NEXT_FRAME_ID.fetch_add(1, Ordering::Relaxed);
            frames.push(Frame {
                id,
                owner,
                ecosystem: ecosystem.to_string(),
                exceptions: Vec::new(),
                claimed: false,
                published: false,
            });
            Ok(Self {
                id,
                ecosystem: ecosystem.to_string(),
                active: true,
            })
        })
    }

    pub fn ecosystem(&self) -> &str {
        &self.ecosystem
    }

    /// The exceptions recorded into this frame so far, without claiming
    /// them. For diagnostics and tests; publication goes through `claim`.
    pub fn recorded(&self) -> Vec<Exception> {
        with_frames(|frames| {
            frames
                .iter()
                .find(|frame| frame.id == self.id)
                .map(|frame| frame.exceptions.clone())
                .unwrap_or_default()
        })
    }

    /// Claim the innermost frame for one closure. Only the comforter writer
    /// calls this at the publication boundary; a claimed frame must then be
    /// published or it cannot finish.
    pub(crate) fn claim(&mut self, ecosystem: &str) -> io::Result<Vec<Exception>> {
        with_frames(|frames| {
            let Some(frame) = frames.last_mut() else {
                return Err(io::Error::other(
                    "closure publication outside any attribution",
                ));
            };
            if frame.id != self.id {
                return Err(io::Error::other(
                    "cannot claim attribution while a child frame is open",
                ));
            }
            if ecosystem != self.ecosystem || ecosystem != frame.ecosystem {
                return Err(io::Error::other(format!(
                    "attribution ecosystem mismatch: token is {}, closure is {ecosystem}",
                    self.ecosystem
                )));
            }
            if frame.claimed {
                return Err(io::Error::other(format!(
                    "the {ecosystem} attribution was already claimed"
                )));
            }
            frame.claimed = true;
            Ok(std::mem::take(&mut frame.exceptions))
        })
    }

    /// Mark a successfully written closure. Claiming happens before the
    /// write, so a failed write loses the claimed exceptions with the frame.
    pub(crate) fn mark_published(&mut self) -> io::Result<()> {
        with_frames(|frames| {
            let Some(frame) = frames.last_mut() else {
                return Err(io::Error::other("attribution frame is no longer open"));
            };
            if frame.id != self.id || !frame.claimed {
                return Err(io::Error::other(
                    "attribution cannot be published before its closure is claimed",
                ));
            }
            frame.published = true;
            Ok(())
        })
    }

    pub fn finish(mut self, expect_publication: bool) -> io::Result<()> {
        let result = with_frames(|frames| {
            let Some(index) = frames.iter().position(|frame| frame.id == self.id) else {
                return Err(io::Error::other("attribution frame is no longer open"));
            };
            if index + 1 != frames.len() {
                let result = Err(io::Error::other(
                    "attribution cannot finish while a child frame is open",
                ));
                frames.remove(index);
                return result;
            }
            let frame = frames.last().expect("frame index is valid");
            let result = if frame.claimed && !frame.published {
                Err(io::Error::other(format!(
                    "{} realization claimed its exceptions but the closure write did not complete",
                    self.ecosystem
                )))
            } else if expect_publication && !frame.published {
                Err(io::Error::other(format!(
                    "{} realization reported success but published no closure",
                    self.ecosystem
                )))
            } else if !frame.exceptions.is_empty() {
                Err(io::Error::other(format!(
                    "{} realization ended with {} exception(s) never claimed by a closure: {}",
                    self.ecosystem,
                    frame.exceptions.len(),
                    format_exception_list(&frame.exceptions)
                )))
            } else {
                Ok(())
            };
            frames.pop();
            result
        });
        self.active = false;
        result
    }

    pub fn discard(mut self) {
        with_frames(|frames| {
            if let Some(index) = frames.iter().position(|frame| frame.id == self.id) {
                frames.remove(index);
            }
        });
        self.active = false;
    }
}

impl Drop for Attribution {
    fn drop(&mut self) {
        if !self.active {
            return;
        }
        // Error and panic cleanup. The success path must call finish or
        // discard explicitly, so it cannot silently bypass publication.
        with_frames(|frames| {
            if let Some(index) = frames.iter().position(|frame| frame.id == self.id) {
                frames.remove(index);
            }
        });
    }
}

#[cfg(test)]
pub(crate) fn pending() -> Vec<Exception> {
    with_frames(|frames| {
        frames
            .last()
            .map(|frame| frame.exceptions.clone())
            .unwrap_or_default()
    })
}

#[cfg(test)]
pub(crate) fn drain() -> Vec<Exception> {
    with_frames(|frames| {
        frames
            .last_mut()
            .map(|frame| std::mem::take(&mut frame.exceptions))
            .unwrap_or_default()
    })
}

#[cfg(test)]
pub(crate) fn clear() {
    with_frames(|frames| {
        if let Some(frame) = frames.last_mut() {
            frame.exceptions.clear();
        }
    });
}

/// Exceptions that change the bytes of the object being built.
pub fn object_exceptions() -> Vec<Exception> {
    with_frames(|frames| {
        frames.last().map_or_else(Vec::new, |frame| {
            frame
                .exceptions
                .iter()
                .filter(|e| {
                    matches!(
                        e.kind.as_str(),
                        FILE_COLLISION
                            | INSTALL_SCRIPT_FAILED
                            | GIT_DEPENDENCY
                            | UNATTESTED_CARGO_LOCK
                    )
                })
                .cloned()
                .collect()
        })
    })
}

/// Refuse a cached object when its recorded exceptions are denied now.
pub fn check_cached(store: &Store, id: &str) -> io::Result<()> {
    let activity = store.activity(crate::kernel::activity::ActivityMode::Shared)?;
    check_cached_with_activity(store, &activity, id)
}

pub fn check_cached_with_activity(
    store: &Store,
    activity: &crate::kernel::activity::StoreActivity,
    id: &str,
) -> io::Result<()> {
    store.require_activity(activity, "cached policy check")?;
    let exceptions = store.exceptions(id)?;
    check_exception_set(id, &exceptions)?;
    for exception in &exceptions {
        record(&exception.kind, &exception.subject, &exception.detail)?;
    }
    Ok(())
}

pub(crate) fn check_exception_set(id: &str, exceptions: &[Exception]) -> io::Result<()> {
    if exceptions.is_empty() {
        return Ok(());
    }
    let denied_kinds: Vec<&str> = exceptions
        .iter()
        .filter(|e| denied(current(), &e.kind))
        .map(|e| e.kind.as_str())
        .collect();
    if denied_kinds.is_empty() {
        return Ok(());
    }
    Err(io::Error::new(
        io::ErrorKind::PermissionDenied,
        format!(
            "cached object {id} carries exception(s): {}; tog sync --fresh will not help; rebuild the object under a permissive policy or fix the cause",
            denied_kinds.join(", ")
        ),
    ))
}

/// Tests that read or set `HOME` / `TOG_POLICY` hold this lock: the
/// environment is process-global, so a test that mutates it would otherwise
/// redirect a concurrent `load` (the same hazard as `store::STORE_ENV_LOCK`).
/// "Read" includes reading them indirectly: `audit` through `policy::load`,
/// `doctor` through `inspect`'s policy check, and the sandbox tests that
/// open or write under `$HOME`. The whole-crate guard order is
/// env -> supervision -> store -> attribution: see the comment on
/// `commands::sync`'s failed_tailor_sync test.
#[cfg(test)]
pub(crate) fn test_env_lock() -> std::sync::MutexGuard<'static, ()> {
    static LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());
    LOCK.lock().unwrap_or_else(|poisoned| poisoned.into_inner())
}

/// Tests that open an `Attribution` frame here, then start from an empty
/// pending list. The whole-crate guard order is env -> supervision ->
/// store -> attribution: see the comment on `commands::sync`'s
/// failed_tailor_sync test.
///
/// Every test that records or opens a token uses this same lock. The frame
/// stack itself remains the production implementation in test builds.
#[cfg(test)]
pub(crate) fn attribution_test_lock() -> std::sync::MutexGuard<'static, ()> {
    static LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());
    let guard = LOCK.lock().unwrap_or_else(|poisoned| poisoned.into_inner());
    clear();
    guard
}

#[cfg(test)]
pub(crate) fn exception_guard() -> std::sync::MutexGuard<'static, ()> {
    attribution_test_lock()
}

#[cfg(test)]
mod tests {
    use super::*;

    struct EnvVarGuard {
        name: &'static str,
        previous: Option<std::ffi::OsString>,
    }

    impl EnvVarGuard {
        fn set(name: &'static str, value: impl AsRef<std::ffi::OsStr>) -> Self {
            let guard = Self {
                name,
                previous: std::env::var_os(name),
            };
            std::env::set_var(name, value);
            guard
        }

        fn remove(name: &'static str) -> Self {
            let guard = Self {
                name,
                previous: std::env::var_os(name),
            };
            std::env::remove_var(name);
            guard
        }
    }

    impl Drop for EnvVarGuard {
        fn drop(&mut self) {
            match &self.previous {
                Some(value) => std::env::set_var(self.name, value),
                None => std::env::remove_var(self.name),
            }
        }
    }

    fn fixture_sources<'a>(sources: &'a [PolicySource], root: &Path) -> Vec<&'a PolicySource> {
        sources
            .iter()
            .filter(|source| {
                source
                    .path
                    .as_deref()
                    .is_some_and(|path| path.starts_with(root))
            })
            .collect()
    }

    #[test]
    fn parses_policy_and_rejects_unknown_keys() {
        let policy = toml::from_str::<Policy>(
            r#"strict = true
deny = ["git-dependency"]"#,
        )
        .unwrap();
        assert!(policy.strict);
        assert!(policy.deny.contains("git-dependency"));
        assert!(toml::from_str::<Policy>("wat = true").is_err());
        let error = parse_file(Path::new("policy.toml"), "deny = [\"typo\"]").unwrap_err();
        assert!(error.to_string().contains("valid kinds:"));
    }

    #[test]
    fn union_semantics_adds_all_deny_entries() {
        let mut merged = Policy::default();
        for text in [r#"deny = ["x"]"#, r#"deny = ["y"]"#] {
            let other = toml::from_str::<Policy>(text).unwrap();
            merged.strict |= other.strict;
            merged.deny.extend(other.deny);
        }
        assert!(denied(&merged, "x"));
        assert!(denied(&merged, "y"));
    }

    #[test]
    fn record_denied_and_allowed() {
        let _guard = exception_guard();
        let attribution = Attribution::open("test").unwrap();
        assert!(record_with(
            &Policy {
                strict: true,
                deny: BTreeSet::new(),
                signing: None,
            },
            "x",
            "s",
            "d"
        )
        .is_err());
        record_with(&Policy::default(), "x", "s", "d").unwrap();
        assert_eq!(drain().len(), 1);
        attribution.discard();
    }

    #[test]
    fn attribution_state_machine_is_explicit() {
        let _guard = attribution_test_lock();
        assert!(record_with(&Policy::default(), "x", "s", "d").is_err());
        let mut parent = Attribution::open("cargo").unwrap();
        record_with(&Policy::default(), "x", "parent", "d").unwrap();
        let mut child = parent.nested("node").unwrap();
        record_with(&Policy::default(), "y", "child", "d").unwrap();
        assert!(parent
            .claim("cargo")
            .unwrap_err()
            .to_string()
            .contains("child"));
        assert!(child.claim("cargo").is_err());
        assert_eq!(child.claim("node").unwrap().len(), 1);
        child.mark_published().unwrap();
        child.finish(true).unwrap();
        assert_eq!(parent.claim("cargo").unwrap().len(), 1);
        parent.mark_published().unwrap();
        parent.finish(true).unwrap();
    }

    #[test]
    fn finish_requires_publication_and_discard_drops_a_frame() {
        let _guard = attribution_test_lock();
        let attribution = Attribution::open("python").unwrap();
        let error = attribution.finish(true).unwrap_err();
        assert!(error.to_string().contains("published no closure"));
        let attribution = Attribution::open("dependency-edit").unwrap();
        record_with(&Policy::default(), "x", "s", "d").unwrap();
        attribution.discard();
        let next = Attribution::open("node").unwrap();
        next.discard();
    }

    #[test]
    fn finish_reports_exceptions_that_no_closure_claimed() {
        let _guard = attribution_test_lock();
        let attribution = Attribution::open("python").unwrap();
        record_with(&Policy::default(), "x", "s", "d").unwrap();
        let error = attribution.finish(false).unwrap_err();
        assert!(error.to_string().contains("x: s: d"));
        Attribution::open("node").unwrap().discard();
    }

    #[test]
    fn dropping_an_attribution_discards_its_frame() {
        let _guard = attribution_test_lock();
        {
            let _attribution = Attribution::open("python").unwrap();
            record_with(&Policy::default(), "x", "s", "d").unwrap();
        }
        assert!(pending().is_empty());
        Attribution::open("node").unwrap().discard();
    }

    #[test]
    fn wrong_ecosystem_and_second_claim_are_rejected() {
        let _guard = attribution_test_lock();
        let mut attribution = Attribution::open("python").unwrap();
        assert!(attribution.claim("node").is_err());
        assert!(attribution.claim("python").unwrap().is_empty());
        attribution.mark_published().unwrap();
        assert!(attribution.claim("python").is_err());
        attribution.finish(true).unwrap();
    }

    #[test]
    fn a_second_thread_cannot_open_over_the_innermost_frame() {
        let _guard = attribution_test_lock();
        let (opened_tx, opened_rx) = std::sync::mpsc::channel::<()>();
        let (release_tx, release_rx) = std::sync::mpsc::channel::<()>();
        let owner = std::thread::spawn(move || {
            let scope = Attribution::open("python").unwrap();
            opened_tx.send(()).unwrap();
            release_rx.recv().unwrap();
            drop(scope);
        });
        opened_rx.recv().unwrap();
        let error = Attribution::open("node").unwrap_err();
        assert_eq!(error.kind(), io::ErrorKind::WouldBlock);
        release_tx.send(()).unwrap();
        owner.join().unwrap();
        Attribution::open("node").unwrap().discard();
    }

    #[test]
    fn drain_clears() {
        let _guard = exception_guard();
        let attribution = Attribution::open("test").unwrap();
        record_with(&Policy::default(), "x", "s", "d").unwrap();
        assert_eq!(drain().len(), 1);
        assert!(drain().is_empty());
        attribution.discard();
    }

    #[test]
    fn a_second_thread_cannot_record_into_the_innermost_frame() {
        let _guard = exception_guard();
        let attribution = Attribution::open("thread-owner").unwrap();
        let error =
            std::thread::spawn(|| record_with(&Policy::default(), "thread-shared", "s", "d"))
                .join()
                .unwrap()
                .unwrap_err();
        assert!(error.to_string().contains("does not own"), "{error}");
        assert!(pending().is_empty());
        assert!(attribution.recorded().is_empty());
        attribution.discard();
    }

    #[test]
    fn a_claimed_frame_cannot_finish_without_publication() {
        let _guard = attribution_test_lock();
        let mut attribution = Attribution::open("node").unwrap();
        record_with(&Policy::default(), "x", "s", "d").unwrap();
        assert_eq!(attribution.recorded().len(), 1);
        assert_eq!(attribution.claim("node").unwrap().len(), 1);
        let error = attribution.finish(false).unwrap_err();
        assert!(error.to_string().contains("did not complete"), "{error}");
        assert!(pending().is_empty());
        Attribution::open("python").unwrap().discard();
    }

    #[test]
    fn origin_strings_are_lowercase_and_match_the_serialized_name() {
        for origin in [
            SourceOrigin::Machine,
            SourceOrigin::Project,
            SourceOrigin::Flag,
            SourceOrigin::Env,
        ] {
            let serialized = serde_json::to_string(&origin).unwrap();
            assert_eq!(serialized, format!("\"{}\"", origin.as_str()));
            assert_eq!(origin.as_str(), origin.as_str().to_lowercase());
        }
    }

    #[test]
    fn load_with_sources_attributes_each_deny_to_the_file_that_asked_for_it() {
        let root = std::env::temp_dir().join(format!(
            "tog-policy-sources-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        let home = root.join("home");
        let parent = root.join("workspace");
        let project = parent.join("member");
        fs::create_dir_all(home.join(".tog")).unwrap();
        fs::create_dir_all(parent.join(".tog")).unwrap();
        fs::create_dir_all(project.join(".tog")).unwrap();
        fs::write(
            home.join(".tog/policy.toml"),
            "deny = [\"git-dependency\"]\n",
        )
        .unwrap();
        fs::write(
            project.join(".tog/policy.toml"),
            "strict = true\ndeny = [\"file-collision\"]\n",
        )
        .unwrap();
        fs::write(
            parent.join(".tog/policy.toml"),
            "deny = [\"weak-integrity\"]\n",
        )
        .unwrap();
        let _env = test_env_lock();
        let _home = EnvVarGuard::set("HOME", home.as_os_str());
        let _policy = EnvVarGuard::remove("TOG_POLICY");
        let (merged, sources) = load_with_sources(&project, false).unwrap();
        let from_load = load(&project, false).unwrap();
        // Ancestors above the temp root belong to the machine running the
        // test (it may have its own policy there); only the files this test
        // wrote are asserted on, and they must be exactly these three in
        // merge order: machine, the project dir, then upward.
        let ours = fixture_sources(&sources, &root);
        let expected = [
            (
                SourceOrigin::Machine,
                home.join(".tog/policy.toml"),
                false,
                GIT_DEPENDENCY,
            ),
            (
                SourceOrigin::Project,
                project.join(".tog/policy.toml"),
                true,
                FILE_COLLISION,
            ),
            (
                SourceOrigin::Project,
                parent.join(".tog/policy.toml"),
                false,
                WEAK_INTEGRITY,
            ),
        ];
        assert_eq!(ours.len(), expected.len(), "{sources:?}");
        for (source, (origin, path, strict, kind)) in ours.iter().zip(expected) {
            assert_eq!(source.origin, origin);
            assert_eq!(source.path.as_deref(), Some(path.as_path()));
            assert_eq!(source.strict, strict);
            assert_eq!(source.deny, BTreeSet::from([kind.to_string()]));
        }
        // The provenance is additive: the merged policy is what `load`
        // already returned.
        assert_eq!(merged.strict, from_load.strict);
        assert_eq!(merged.deny, from_load.deny);
        assert!(merged.strict);
        assert!(merged.deny.contains(GIT_DEPENDENCY));
        assert!(merged.deny.contains(FILE_COLLISION));
        assert!(merged.deny.contains(WEAK_INTEGRITY));
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn strict_without_a_file_is_recorded_as_the_flag_source() {
        let root = std::env::temp_dir().join(format!(
            "tog-policy-strict-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        fs::create_dir_all(&root).unwrap();
        let _env = test_env_lock();
        let _home = EnvVarGuard::set("HOME", root.as_os_str());
        let _policy = EnvVarGuard::remove("TOG_POLICY");
        let _strict = EnvVarGuard::remove("TOG_STRICT");
        let (policy, sources) = load_with_sources(&root, true).unwrap();
        assert!(policy.strict);
        let flags: Vec<&PolicySource> = sources
            .iter()
            .filter(|source| source.origin == SourceOrigin::Flag && source.path.is_none())
            .collect();
        assert_eq!(flags.len(), 1, "{sources:?}");
        let flag = flags[0];
        assert_eq!(flag.origin, SourceOrigin::Flag);
        assert!(flag.path.is_none());
        assert!(flag.strict);
        assert!(flag.deny.is_empty());
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn load_with_sources_does_not_duplicate_a_machine_policy_under_home() {
        let root = std::env::temp_dir().join(format!(
            "tog-policy-home-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        let home = root.join("home");
        let project = home.join("project");
        let machine = home.join(".tog/policy.toml");
        fs::create_dir_all(home.join(".tog")).unwrap();
        fs::create_dir_all(&project).unwrap();
        fs::write(&machine, "deny = [\"git-dependency\"]\n").unwrap();

        let _env = test_env_lock();
        let _home = EnvVarGuard::set("HOME", home.as_os_str());
        let _policy = EnvVarGuard::remove("TOG_POLICY");
        let _strict = EnvVarGuard::remove("TOG_STRICT");

        let (merged, sources) = load_with_sources(&project, false).unwrap();
        assert!(merged.deny.contains(GIT_DEPENDENCY));
        let ours = fixture_sources(&sources, &root);
        assert_eq!(ours.len(), 1, "{sources:?}");
        assert_eq!(ours[0].origin, SourceOrigin::Machine);
        assert_eq!(ours[0].path.as_deref(), Some(machine.as_path()));

        let project_policy = project.join(".tog/policy.toml");
        fs::create_dir_all(project_policy.parent().unwrap()).unwrap();
        fs::write(&project_policy, "deny = [\"weak-integrity\"]\n").unwrap();
        let (merged, sources) = load_with_sources(&project, false).unwrap();
        assert!(merged.deny.contains(GIT_DEPENDENCY));
        assert!(merged.deny.contains(WEAK_INTEGRITY));
        let ours = fixture_sources(&sources, &root);
        assert_eq!(ours.len(), 2, "{sources:?}");
        assert_eq!(
            ours.iter().map(|source| source.origin).collect::<Vec<_>>(),
            vec![SourceOrigin::Machine, SourceOrigin::Project]
        );
        assert_eq!(ours[0].path.as_deref(), Some(machine.as_path()));
        assert_eq!(ours[1].path.as_deref(), Some(project_policy.as_path()));
        let _ = fs::remove_dir_all(root);
    }

    #[cfg(unix)]
    #[test]
    fn load_with_sources_does_not_duplicate_a_hard_linked_machine_policy() {
        let root = std::env::temp_dir().join(format!(
            "tog-policy-hard-link-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        let home = root.join("home");
        let project = root.join("project");
        let machine = home.join(".tog/policy.toml");
        let project_policy = project.join(".tog/policy.toml");
        fs::create_dir_all(home.join(".tog")).unwrap();
        fs::create_dir_all(project_policy.parent().unwrap()).unwrap();
        fs::write(&machine, "deny = [\"git-dependency\"]\n").unwrap();
        fs::hard_link(&machine, &project_policy).unwrap();

        let _env = test_env_lock();
        let _home = EnvVarGuard::set("HOME", home.as_os_str());
        let _policy = EnvVarGuard::remove("TOG_POLICY");
        let _strict = EnvVarGuard::remove("TOG_STRICT");

        let (merged, sources) = load_with_sources(&project, false).unwrap();

        assert!(merged.deny.contains(GIT_DEPENDENCY));
        let ours = fixture_sources(&sources, &root);
        assert_eq!(ours.len(), 1, "{sources:?}");
        assert_eq!(ours[0].origin, SourceOrigin::Machine);
        assert_eq!(ours[0].path.as_deref(), Some(machine.as_path()));
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn strict_environment_and_flag_are_recorded_as_separate_sources() {
        let root = std::env::temp_dir().join(format!(
            "tog-policy-strict-env-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        fs::create_dir_all(&root).unwrap();
        let _env = test_env_lock();
        let _home = EnvVarGuard::set("HOME", root.as_os_str());
        let _policy = EnvVarGuard::remove("TOG_POLICY");
        let _strict = EnvVarGuard::set("TOG_STRICT", "1");

        let (policy, env_sources) = load_with_sources(&root, false).unwrap();
        assert!(policy.strict);
        let pathless: Vec<&PolicySource> = env_sources
            .iter()
            .filter(|source| source.path.is_none())
            .collect();
        assert_eq!(
            pathless
                .iter()
                .map(|source| source.origin)
                .collect::<Vec<_>>(),
            vec![SourceOrigin::Env]
        );
        assert!(pathless[0].path.is_none());

        let (_, both_sources) = load_with_sources(&root, true).unwrap();
        let pathless: Vec<&PolicySource> = both_sources
            .iter()
            .filter(|source| source.path.is_none())
            .collect();
        assert_eq!(
            pathless
                .iter()
                .map(|source| source.origin)
                .collect::<Vec<_>>(),
            vec![SourceOrigin::Flag, SourceOrigin::Env]
        );
        assert!(pathless.iter().all(|source| source.path.is_none()));
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn loads_user_and_project_policy_union_from_files() {
        let root = std::env::temp_dir().join(format!(
            "tog-policy-test-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        let home = root.join("home");
        let project = root.join("project");
        fs::create_dir_all(home.join(".tog")).unwrap();
        fs::create_dir_all(project.join(".tog")).unwrap();
        fs::write(
            home.join(".tog/policy.toml"),
            "deny = [\"git-dependency\"]\n",
        )
        .unwrap();
        fs::write(
            project.join(".tog/policy.toml"),
            "strict = true\ndeny = [\"file-collision\"]\n",
        )
        .unwrap();
        let _env = test_env_lock();
        let _home = EnvVarGuard::set("HOME", home.as_os_str());
        let _policy = EnvVarGuard::remove("TOG_POLICY");
        let loaded = load(&project, false).unwrap();
        // Ancestor rule: a workspace member inherits the root's policy.
        let member = project.join("crates/member");
        fs::create_dir_all(&member).unwrap();
        let from_member = load(&member, false).unwrap();
        assert!(loaded.strict);
        assert!(loaded.deny.contains(FILE_COLLISION));
        assert!(loaded.deny.contains(GIT_DEPENDENCY));
        let _ = fs::remove_dir_all(root);
        assert!(from_member.strict);
        assert!(from_member.deny.contains("file-collision"));
        assert!(from_member.deny.contains("git-dependency"));
    }

    fn key(byte: u8) -> signing::PublicKey {
        signing::PublicKey::from_hex(&hex::encode([byte; 32])).unwrap()
    }

    fn keys(bytes: &[u8]) -> KeySet {
        bytes.iter().copied().map(key).collect()
    }

    fn trusted_policy(set: &KeySet) -> Policy {
        Policy {
            signing: Some(Signing {
                trusted: set.clone(),
            }),
            ..Policy::default()
        }
    }

    #[test]
    fn signing_table_parses_keys_and_refuses_malformed_entries() {
        let path = Path::new("policy.toml");
        let lower = key(0xab).to_string();
        let upper = lower.replace("ed25519:", "").to_uppercase();
        let policy = parse_file(
            path,
            &format!("[signing]\ntrusted = [\"{lower}\", \"ed25519:{upper}\"]\n"),
        )
        .unwrap();
        let signing = policy.signing.as_ref().unwrap();
        assert_eq!(
            signing.trusted,
            keys(&[0xab]),
            "case-insensitive, deduplicated"
        );
        assert!(!policy.strict);
        assert!(policy.deny.is_empty());
        // Explicitly empty is a declared state, distinct from absent.
        let empty = parse_file(path, "[signing]\ntrusted = []\n").unwrap();
        assert_eq!(empty.signing, Some(Signing::default()));
        let absent = parse_file(path, "deny = []\n").unwrap();
        assert_eq!(absent.signing, None);
        // Deny and strict still parse beside the table.
        let both = parse_file(
            path,
            &format!("strict = true\ndeny = [\"git-dependency\"]\n\n[signing]\ntrusted = [\"{lower}\"]\n"),
        )
        .unwrap();
        assert!(both.strict);
        assert!(both.deny.contains(GIT_DEPENDENCY));
        assert_eq!(both.signing.unwrap().trusted, keys(&[0xab]));
        for (text, what) in [
            ("[signing]\n", "a table that declares nothing"),
            ("[signing]\ntrusted = [\"nope\"]\n", "not a key"),
            (
                "[signing]\ntrusted = [\"ed25519:abcd\"]\n",
                "too short",
            ),
            (
                "[signing]\ntrusted = [\"rsa:0000000000000000000000000000000000000000000000000000000000000000\"]\n",
                "another algorithm",
            ),
            (
                "[signing]\ntrusted = [\"ED25519:0000000000000000000000000000000000000000000000000000000000000000\"]\n",
                "an uppercase prefix",
            ),
            ("[signing]\ntrusted = []\nextra = 1\n", "an unknown signing field"),
            ("[signing]\ntrusted = \"ed25519:00\"\n", "a scalar instead of a list"),
            ("signing = 1\n", "a scalar table"),
            ("[signing.trusted]\n", "a nested table"),
        ] {
            let error = parse_file(path, text).unwrap_err();
            assert_eq!(error.kind(), io::ErrorKind::InvalidData, "{what}");
            assert!(
                error.to_string().starts_with("parse policy.toml"),
                "{what}: {error}"
            );
        }
        // The rendered form is the policy syntax, lowercase.
        assert_eq!(
            toml::to_string(&policy).unwrap(),
            format!("strict = false\ndeny = []\n\n[signing]\ntrusted = [\"{lower}\"]\n")
        );
    }

    #[test]
    fn machine_scope_introduces_trust_and_lower_scopes_only_narrow() {
        let mut chain = Policy::default();
        // A project or flag list seen while trust is unconfigured cannot
        // initialize it.
        merge(
            &mut chain,
            &trusted_policy(&keys(&[1])),
            SourceOrigin::Project,
        );
        assert_eq!(chain.signing, None);
        merge(&mut chain, &trusted_policy(&keys(&[1])), SourceOrigin::Flag);
        assert_eq!(chain.signing, None);
        // The machine scope introduces it.
        merge(
            &mut chain,
            &trusted_policy(&keys(&[1, 2, 3])),
            SourceOrigin::Machine,
        );
        assert_eq!(chain.signing.as_ref().unwrap().trusted, keys(&[1, 2, 3]));
        // A scope with no table leaves the set unchanged.
        merge(&mut chain, &Policy::default(), SourceOrigin::Project);
        merge(&mut chain, &Policy::default(), SourceOrigin::Flag);
        assert_eq!(chain.signing.as_ref().unwrap().trusted, keys(&[1, 2, 3]));
        // A project list intersects: it drops keys, never adds them.
        merge(
            &mut chain,
            &trusted_policy(&keys(&[2, 3, 4])),
            SourceOrigin::Project,
        );
        assert_eq!(chain.signing.as_ref().unwrap().trusted, keys(&[2, 3]));
        // So does the --policy file.
        merge(
            &mut chain,
            &trusted_policy(&keys(&[3, 5])),
            SourceOrigin::Flag,
        );
        assert_eq!(chain.signing.as_ref().unwrap().trusted, keys(&[3]));
        // Deny and strict still union alongside.
        merge(
            &mut chain,
            &Policy {
                strict: true,
                deny: [GIT_DEPENDENCY.to_string()].into_iter().collect(),
                signing: None,
            },
            SourceOrigin::Flag,
        );
        assert!(chain.strict);
        assert!(chain.deny.contains(GIT_DEPENDENCY));
        assert_eq!(chain.signing.as_ref().unwrap().trusted, keys(&[3]));
        // An intersection can empty the set; that is a decision, not an
        // unconfigured state.
        merge(
            &mut chain,
            &trusted_policy(&keys(&[9])),
            SourceOrigin::Project,
        );
        assert_eq!(chain.signing, Some(Signing::default()));
        // An explicitly empty machine list is the same decision.
        let mut nobody = Policy::default();
        merge(
            &mut nobody,
            &trusted_policy(&KeySet::new()),
            SourceOrigin::Machine,
        );
        assert_eq!(nobody.signing, Some(Signing::default()));
        merge(
            &mut nobody,
            &trusted_policy(&keys(&[1])),
            SourceOrigin::Project,
        );
        assert_eq!(nobody.signing, Some(Signing::default()));
        // `union` on its own never touches trust in either direction.
        let mut plain = Policy::default();
        union(&mut plain, &trusted_policy(&keys(&[1])));
        assert_eq!(plain.signing, None);
        let mut kept = trusted_policy(&keys(&[1, 2]));
        union(&mut kept, &trusted_policy(&keys(&[3])));
        assert_eq!(kept.signing.unwrap().trusted, keys(&[1, 2]));
    }

    #[test]
    fn load_with_sources_records_each_scopes_trusted_list() {
        let root = std::env::temp_dir().join(format!(
            "tog-policy-signing-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        let home = root.join("home");
        let project = root.join("project");
        fs::create_dir_all(home.join(".tog")).unwrap();
        fs::create_dir_all(project.join(".tog")).unwrap();
        let toml_list = |bytes: &[u8]| {
            let entries: Vec<String> = bytes.iter().map(|b| format!("\"{}\"", key(*b))).collect();
            format!("[signing]\ntrusted = [{}]\n", entries.join(", "))
        };
        fs::write(home.join(".tog/policy.toml"), toml_list(&[1, 2])).unwrap();
        fs::write(
            project.join(".tog/policy.toml"),
            format!("deny = [\"git-dependency\"]\n{}", toml_list(&[2, 3])),
        )
        .unwrap();
        let _env = test_env_lock();
        let _home = EnvVarGuard::set("HOME", home.as_os_str());
        let _policy = EnvVarGuard::remove("TOG_POLICY");
        let _strict = EnvVarGuard::remove("TOG_STRICT");
        let (policy, sources) = load_with_sources(&project, true).unwrap();
        assert_eq!(policy.signing.as_ref().unwrap().trusted, keys(&[2]));
        assert!(policy.deny.contains(GIT_DEPENDENCY));
        let fixture = fixture_sources(&sources, &root);
        assert_eq!(fixture.len(), 2);
        assert_eq!(fixture[0].origin, SourceOrigin::Machine);
        assert_eq!(fixture[0].trusted, Some(keys(&[1, 2])));
        assert_eq!(fixture[1].origin, SourceOrigin::Project);
        assert_eq!(fixture[1].trusted, Some(keys(&[2, 3])));
        // The strictness flag source declares no list.
        let flag = sources
            .iter()
            .find(|source| source.origin == SourceOrigin::Flag)
            .unwrap();
        assert_eq!(flag.trusted, None);
        // Without a machine declaration the project list is recorded but
        // trust stays unconfigured.
        fs::write(home.join(".tog/policy.toml"), "deny = []\n").unwrap();
        let (policy, sources) = load_with_sources(&project, false).unwrap();
        assert_eq!(policy.signing, None);
        let fixture = fixture_sources(&sources, &root);
        assert_eq!(fixture[0].trusted, None);
        assert_eq!(fixture[1].trusted, Some(keys(&[2, 3])));
        // An explicitly empty machine list is recorded as `Some([])`.
        fs::write(home.join(".tog/policy.toml"), "[signing]\ntrusted = []\n").unwrap();
        let (policy, sources) = load_with_sources(&project, false).unwrap();
        assert_eq!(policy.signing, Some(Signing::default()));
        assert_eq!(
            fixture_sources(&sources, &root)[0].trusted,
            Some(KeySet::new())
        );
        let _ = fs::remove_dir_all(root);
    }
}
