//! Shell completions, generated from the command table.

#[cfg(test)]
use super::parse::takes_sync_flags;
use super::parse::{
    all_command_words, command_flags, help_words, option_spellings, GLOBAL_FLAGS, SETUP_FLAGS,
};
use super::spec::listed;
use super::Shell;

/// The one-liner every shell uses to read script names out of package.json.
/// Deliberately a sed/grep pipeline: completion must not need jq or node.
const SCRIPTS_PIPELINE: &str = r#"sed -n '/"scripts"[[:space:]]*:/,/}/p' package.json | grep -oE '^[[:space:]]*"[^"]+"[[:space:]]*:' | tr -d ' \t":'"#;

/// `source_extensions` are the extensions `tog <file>` runs (`py`, `js`),
/// which the command layer reads from the tailors: a first word completes
/// to a command, a package.json script, or a file with one of them.
pub fn completions(shell: Shell, source_extensions: &[&str]) -> String {
    match shell {
        Shell::Bash => bash_completions(source_extensions),
        Shell::Zsh => zsh_completions(source_extensions),
        Shell::Fish => fish_completions(source_extensions),
    }
}

fn bash_completions(source_extensions: &[&str]) -> String {
    let mut out = String::from(
        "# bash completion for tog — generated by 'tog completions bash'\n\
         _tog_scripts() {\n    [[ -f package.json ]] || return 0\n    ",
    );
    out.push_str(SCRIPTS_PIPELINE);
    out.push_str(
        "\n}\n\n_tog() {\n    local cur cmd=\"\" i\n    cur=\"${COMP_WORDS[COMP_CWORD]}\"\n    \
         for ((i = 1; i < COMP_CWORD; i++)); do\n        case \"${COMP_WORDS[i]}\" in\n            \
         -C|--directory) ((i++)) ;;\n            -*) ;;\n            *) cmd=\"${COMP_WORDS[i]}\"; break ;;\n        \
         esac\n    done\n    if [[ -z \"$cmd\" ]]; then\n        if [[ \"$cur\" == -* ]]; then\n            ",
    );
    // `--frozen` and `--strict` are in both lists; offer each word once.
    let setup_only: Vec<&str> = SETUP_FLAGS
        .iter()
        .copied()
        .filter(|flag| !GLOBAL_FLAGS.contains(flag))
        .collect();
    out.push_str(&format!(
        "COMPREPLY=( $(compgen -W \"{} {}\" -- \"$cur\") )\n",
        GLOBAL_FLAGS.join(" "),
        setup_only.join(" ")
    ));
    out.push_str(&format!(
        "        else\n            COMPREPLY=( $(compgen -W \"{} $(_tog_scripts)\" -- \"$cur\") )\n            \
         compopt -o filenames 2>/dev/null\n            \
         mapfile -t -O \"${{#COMPREPLY[@]}}\" COMPREPLY < <(compgen -d -- \"$cur\"; for ext in {}; do \
         compgen -f -X \"!*.$ext\" -- \"$cur\"; done)\n        fi\n        return\n    fi\n    case \"$cmd\" in\n",
        all_command_words().join(" "),
        source_extensions.join(" ")
    ));
    for spec in listed() {
        let mut words: Vec<&str> = spec.words.to_vec();
        words.extend(command_flags(spec));
        let pattern = spec.name;
        match spec.name {
            "run" => out.push_str(
                "        run)\n            if [[ $i -eq $((COMP_CWORD - 1)) ]]; then\n                \
                 COMPREPLY=( $(compgen -W \"$(_tog_scripts)\" -c -- \"$cur\") )\n            else\n                \
                 COMPREPLY=( $(compgen -f -- \"$cur\") )\n            fi ;;\n",
            ),
            "build" => out.push_str(&format!(
                "        build)\n            if [[ $i -eq $((COMP_CWORD - 1)) ]]; then\n                \
                 COMPREPLY=( $(compgen -W \"{}\" -- \"$cur\") )\n            else\n                \
                 COMPREPLY=( $(compgen -f -- \"$cur\") )\n            fi ;;\n",
                words.join(" ")
            )),
            _ => out.push_str(&format!(
                "        {pattern}) COMPREPLY=( $(compgen -W \"{}\" -- \"$cur\") ) ;;\n",
                words.join(" ")
            )),
        }
    }
    out.push_str(&format!(
        "        help) COMPREPLY=( $(compgen -W \"{}\" -- \"$cur\") ) ;;\n        *) COMPREPLY=() ;;\n    esac\n}}\n\ncomplete -F _tog tog\n",
        help_words().join(" ")
    ));
    out
}

fn zsh_quote(text: &str) -> String {
    text.replace('\'', "'\\''")
        .replace(':', "\\:")
        .replace('[', "\\[")
        .replace(']', "\\]")
}

fn zsh_completions(source_extensions: &[&str]) -> String {
    let mut out = String::from(
        "#compdef tog\n# zsh completion for tog — generated by 'tog completions zsh'\n\n\
         _tog_scripts() {\n    [[ -f package.json ]] || return 1\n    local -a scripts\n    scripts=(${(f)\"$(",
    );
    out.push_str(SCRIPTS_PIPELINE);
    out.push_str(")\"})\n    (( ${#scripts} )) && _describe -t scripts 'package.json script' scripts\n}\n\n_tog() {\n    local -a commands\n    commands=(\n");
    for spec in listed() {
        out.push_str(&format!(
            "        '{}:{}'\n",
            spec.name,
            zsh_quote(spec.summary)
        ));
    }
    out.push_str("        'help:show help for a command'\n        'version:print the version'\n    )\n    local curcontext=\"$curcontext\" state line\n    _arguments -C \\\n        '(-C --directory)'{-C,--directory}'[run as if started in <dir>]:directory:_files -/' \\\n        '(-q --quiet)'{-q,--quiet}'[no narration]' \\\n        '(-v --verbose)'{-v,--verbose}'[show every decision and subprocess]' \\\n        '--no-color[plain output]' \\\n        '(-h --help)'{-h,--help}'[print help]' \\\n        '(-V --version)'{-V,--version}'[print the version]' \\\n        '--frozen[CI: check the locks are current without writing them]' \\\n        '--fresh[rebuild .venv / node_modules from scratch]' \\\n        '--strict[refuse every policy exception]' \\\n        '*--resolution-record[also judge these signed resolution records]:path:_files' \\\n        '1: :->command' \\\n        '*:: :->args'\n    case $state in\n        command)\n            _describe -t commands 'tog command' commands\n            _tog_scripts\n");
    out.push_str(&format!(
        "            _files -g '*.({})'\n",
        source_extensions.join("|")
    ));
    out.push_str("            ;;\n        args)\n            case $words[1] in\n");
    for spec in listed() {
        let pattern = spec.name;
        if spec.name == "run" {
            out.push_str("                run)\n                    if (( CURRENT == 2 )); then\n                        _tog_scripts\n                        _command_names -e\n                    else\n                        _files\n                    fi\n                    ;;\n");
            continue;
        }
        let mut specs: Vec<String> = spec
            .options
            .iter()
            .flat_map(|(flag, description)| {
                option_spellings(flag)
                    .map(move |spelling| format!("'{spelling}[{}]'", zsh_quote(description)))
            })
            .collect();
        if !spec.words.is_empty() {
            specs.push(format!("'1:word:({})'", spec.words.join(" ")));
        }
        if spec.name == "build" || spec.name == "gc" {
            specs.push("'*:file:_files'".to_string());
        }
        out.push_str(&format!(
            "                {pattern})\n                    _arguments {}\n                    ;;\n",
            specs.join(" ")
        ));
    }
    out.push_str(&format!(
        "                help)\n                    _values 'command' {}\n                    ;;\n                *)\n                    _files\n                    ;;\n            esac\n            ;;\n    esac\n}}\n\n_tog \"$@\"\n",
        help_words().join(" ")
    ));
    out
}

fn fish_quote(text: &str) -> String {
    text.replace('\\', "\\\\").replace('\'', "\\'")
}

fn fish_completions(source_extensions: &[&str]) -> String {
    let mut out = String::from(
        "# fish completion for tog — generated by 'tog completions fish'\n\
         function __tog_scripts\n    test -f package.json; or return\n    ",
    );
    out.push_str(SCRIPTS_PIPELINE);
    out.push_str("\nend\n\ncomplete -c tog -f\n");
    let globals: &[(&str, &str, &str, bool)] = &[
        ("C", "directory", "run as if started in <dir>", true),
        ("q", "quiet", "no narration", false),
        ("v", "verbose", "show every decision and subprocess", false),
        ("", "no-color", "plain output", false),
        ("h", "help", "print help", false),
        ("V", "version", "print the version", false),
        (
            "",
            "frozen",
            "CI: check the locks are current without writing them",
            false,
        ),
        (
            "",
            "fresh",
            "rebuild .venv / node_modules from scratch",
            false,
        ),
        ("", "strict", "refuse every policy exception", false),
        (
            "",
            "resolution-record",
            "also judge these signed resolution records",
            true,
        ),
    ];
    for (short, long, description, takes_value) in globals {
        let mut line = String::from("complete -c tog -n '__fish_use_subcommand'");
        if !short.is_empty() {
            line.push_str(&format!(" -s {short}"));
        }
        line.push_str(&format!(" -l {long}"));
        if *takes_value && *long == "directory" {
            line.push_str(" -r -a '(__fish_complete_directories)'");
        } else if *takes_value {
            line.push_str(" -r -F");
        }
        line.push_str(&format!(" -d '{}'\n", fish_quote(description)));
        out.push_str(&line);
    }
    for spec in listed() {
        out.push_str(&format!(
            "complete -c tog -n '__fish_use_subcommand' -a {} -d '{}'\n",
            spec.name,
            fish_quote(spec.summary)
        ));
    }
    out.push_str(
        "complete -c tog -n '__fish_use_subcommand' -a help -d 'show help for a command'\n",
    );
    out.push_str("complete -c tog -n '__fish_use_subcommand' -a version -d 'print the version'\n");
    out.push_str("complete -c tog -n '__fish_use_subcommand' -a '(__tog_scripts)' -d 'package.json script'\n");
    for extension in source_extensions {
        out.push_str(&format!(
            "complete -c tog -n '__fish_use_subcommand' -a '(__fish_complete_suffix .{extension})' -d 'source file'\n"
        ));
    }
    for spec in listed() {
        let seen = spec.name;
        for (flag, description) in spec.options {
            for spelling in option_spellings(flag) {
                let (kind, name) = if let Some(long) = spelling.strip_prefix("--") {
                    ("-l", long)
                } else {
                    ("-s", &spelling[1..])
                };
                let value = if flag.contains('<') { " -r" } else { "" };
                out.push_str(&format!(
                    "complete -c tog -n '__fish_seen_subcommand_from {seen}' {kind} {name}{value} -d '{}'\n",
                    fish_quote(description)
                ));
            }
        }
        if !spec.words.is_empty() {
            out.push_str(&format!(
                "complete -c tog -n '__fish_seen_subcommand_from {seen}' -a '{}'\n",
                spec.words.join(" ")
            ));
        }
        if spec.name == "run" {
            out.push_str("complete -c tog -n '__fish_seen_subcommand_from run' -a '(__tog_scripts)' -d 'package.json script'\n");
            out.push_str("complete -c tog -n '__fish_seen_subcommand_from run' -a '(__fish_complete_command)'\n");
        }
        if spec.name == "build" || spec.name == "gc" {
            out.push_str(&format!(
                "complete -c tog -n '__fish_seen_subcommand_from {seen}' -F\n"
            ));
        }
    }
    out.push_str(&format!(
        "complete -c tog -n '__fish_seen_subcommand_from help' -a '{}'\n",
        help_words().join(" ")
    ));
    out
}

#[cfg(test)]
mod tests {
    const TEST_EXTENSIONS: &[&str] = &["py", "js"];
    use super::*;

    /// The words one shell offers after `verb`: its bash `case` arm, its
    /// zsh `_arguments` arm, or its fish `__fish_seen_subcommand_from`
    /// lines, split into tokens with the quoting and zsh's `[description]`
    /// and `(word list)` syntax taken off.
    fn verb_tokens(shell: Shell, script: &str, verb: &str) -> Vec<String> {
        let block: Vec<&str> = match shell {
            Shell::Bash => {
                let case = format!("        {verb}) ");
                let multi = format!("        {verb})");
                let mut lines = script
                    .lines()
                    .skip_while(|line| !line.starts_with(&case) && *line != multi);
                let first = lines
                    .next()
                    .unwrap_or_else(|| panic!("bash has no {verb} arm"));
                let mut block = vec![first];
                if !first.ends_with(";;") {
                    block.extend(lines.take_while(|line| !line.ends_with(";;")));
                }
                block
            }
            Shell::Zsh => {
                let case = format!("                {verb})");
                let mut lines = script.lines().skip_while(|line| *line != case);
                assert!(lines.next().is_some(), "zsh has no {verb} arm");
                lines.take_while(|line| line.trim() != ";;").collect()
            }
            Shell::Fish => {
                let seen = format!("__fish_seen_subcommand_from {verb}'");
                script.lines().filter(|line| line.contains(&seen)).collect()
            }
        };
        block
            .iter()
            .flat_map(|line| line.split(|c: char| c.is_whitespace() || "'\"()[".contains(c)))
            .filter(|token| !token.is_empty())
            .map(str::to_string)
            .collect()
    }

    /// Each verb's own completion offers its own options and words. A flag
    /// or word offered only by some other verb does not count: the check
    /// reads the verb's arm, never the whole script.
    #[test]
    fn completions_cover_every_command_and_option() {
        for shell in [Shell::Bash, Shell::Zsh, Shell::Fish] {
            let script = completions(shell, TEST_EXTENSIONS);
            for spec in listed() {
                // The verb itself completes at the top level.
                let top = match shell {
                    Shell::Bash => format!(" {} ", spec.name),
                    Shell::Zsh => format!("        '{}:", spec.name),
                    Shell::Fish => format!("'__fish_use_subcommand' -a {} -d", spec.name),
                };
                let offered = script.lines().any(|line| match shell {
                    // The one word list that mixes verbs and script names.
                    Shell::Bash => {
                        line.contains("compgen -W")
                            && line.contains("$(_tog_scripts)")
                            && line.replace('"', " ").contains(&top)
                    }
                    _ => line.contains(&top),
                });
                assert!(offered, "{shell:?} does not offer {}", spec.name);
                // `run` completes a script or a program name, then files:
                // what follows it belongs to that program, not to tog.
                if spec.name == "run" {
                    continue;
                }
                let tokens = verb_tokens(shell, &script, spec.name);
                for flag in command_flags(spec) {
                    // fish spells `--json` as `-l json` and `-o` as `-s o`.
                    let offered = match (shell, flag.strip_prefix("--")) {
                        (Shell::Fish, Some(long)) => tokens
                            .windows(2)
                            .any(|pair| pair[0] == "-l" && pair[1] == long),
                        (Shell::Fish, None) => tokens
                            .windows(2)
                            .any(|pair| pair[0] == "-s" && pair[1] == flag[1..]),
                        _ => tokens.iter().any(|token| token == flag),
                    };
                    assert!(offered, "{shell:?} {} lacks {flag}: {tokens:?}", spec.name);
                }
                for word in spec.words {
                    assert!(
                        tokens.iter().any(|token| token == word),
                        "{shell:?} {} lacks {word}: {tokens:?}",
                        spec.name
                    );
                }
            }
            // The bare form's flags complete at the top level; its hidden
            // name and aliases are never offered.
            for flag in SETUP_FLAGS {
                assert!(script.contains(&flag[2..]), "{shell:?} lacks {flag}");
            }
            assert!(script.contains("inputs"), "{shell:?} lacks 'help inputs'");
            assert!(
                script.contains("package.json"),
                "{shell:?} lacks script completion"
            );
        }
        // The bare form's hidden name and aliases are never offered.
        for word in ["sync", "install", "i"] {
            assert!(!all_command_words().contains(&word), "offers '{word}'");
            assert!(!help_words().contains(&word), "help offers '{word}'");
        }
        assert!(completions(Shell::Bash, TEST_EXTENSIONS).ends_with("complete -F _tog tog\n"));
        assert!(completions(Shell::Zsh, TEST_EXTENSIONS).starts_with("#compdef tog\n"));
        assert!(completions(Shell::Fish, TEST_EXTENSIONS).contains("complete -c tog -f\n"));
        assert_eq!(zsh_quote("a:b [c]"), "a\\:b \\[c\\]");
        assert_eq!(fish_quote("it's"), "it\\'s");
    }

    /// `add`, `remove` and `update` refuse `--frozen` (they exist to write
    /// the lock), so does `x` (it has no lock to check), and a verb that
    /// never syncs refuses both `--frozen` and
    /// `--strict`, so no shell offers a refused flag after its verb. Global
    /// options complete only ahead of the verb, where the verb is not yet
    /// known; after it each shell offers the command's own options alone.
    #[test]
    fn completions_never_offer_a_refused_sync_flag_after_the_verb() {
        let bash = completions(Shell::Bash, TEST_EXTENSIONS);
        let zsh = completions(Shell::Zsh, TEST_EXTENSIONS);
        let fish = completions(Shell::Fish, TEST_EXTENSIONS);
        let refusals = listed().flat_map(|spec| {
            let flags: &[&str] = match spec.name {
                "add" | "remove" | "update" | "x" | "attest" => &["frozen"],
                name if !takes_sync_flags(name) => &["frozen", "strict"],
                _ => &[],
            };
            flags.iter().map(move |flag| (spec.name, *flag))
        });
        let mut checked = 0;
        for (verb, flag) in refusals {
            checked += 1;
            let spelled = format!("--{flag}");
            let case = format!("        {verb}) ");
            let line = bash.lines().find(|line| line.starts_with(&case)).unwrap();
            assert!(!line.contains(&spelled), "bash {verb}: {line}");
            let case = format!("                {verb})");
            let mut lines = zsh.lines().skip_while(|line| *line != case);
            let line = lines.nth(1).unwrap();
            assert!(line.contains("_arguments"), "zsh {verb}: {line}");
            assert!(!line.contains(&spelled), "zsh {verb}: {line}");
            let seen = format!("__fish_seen_subcommand_from {verb}'");
            let long = format!("-l {flag}");
            assert!(
                !fish
                    .lines()
                    .any(|line| line.contains(&seen) && line.contains(&long)),
                "fish {verb} offers {spelled}"
            );
        }
        // Three dependency verbs plus `x`, and both flags for every verb
        // that never syncs: a table that lost them would pass the loop
        // vacuously.
        assert!(checked > 4 + 2 * 5, "{checked}");
    }
}
