//! Catalog documents (kernel layer): the checked-in data file one
//! ecosystem's shipped catalog is read from, instead of hand-written rows.
//!
//! A document is the release bundles of [`super::Catalog`] spelled as TOML,
//! plus the release an unconstrained project gets (`default`). The files
//! are generated by `tools/catalog.py`, which fetches each publisher's
//! checksum source and verifies every row before writing it; the binary
//! embeds them with `include_str!` and parses them here, once per process.
//! The same shape is what a refreshed, fetched release catalog would carry, so
//! the shipped document is the first snapshot rather than a separate format.
//!
//! The canonical spelling is exactly what [`Document::render`] writes: one
//! release table per bundle, newest primary version first, one line per
//! component and per artifact row. The generator writes the same bytes, so a
//! test can hold every shipped file to `render(parse(file)) == file` and a
//! hand edit in any other spelling is caught.

#[cfg(test)]
use super::qualified;
use super::{invalid, parse_qualified, ArtifactRow, Bundle, Catalog, Component};
use crate::kernel::platform::Platform;
use serde::Deserialize;
use std::io;
use std::sync::OnceLock;

/// The document grammar version `schema` must name.
pub const SCHEMA: u32 = 1;

/// One ecosystem's shipped releases and its default, as parsed.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Document {
    pub ecosystem: String,
    pub primary: Vec<String>,
    /// The release key an unconstrained project gets. Adding a newer release
    /// never moves it; changing it is its own deliberate edit.
    pub default: String,
    pub bundles: Vec<Bundle>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct RawDocument {
    schema: u32,
    ecosystem: String,
    primary: Vec<String>,
    default: String,
    #[serde(default)]
    release: Vec<RawRelease>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct RawRelease {
    key: String,
    revision: Option<u32>,
    components: Vec<RawComponent>,
    artifacts: Vec<RawArtifact>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct RawComponent {
    name: String,
    version: String,
    embedded_in: Option<String>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct RawArtifact {
    platform: String,
    component: String,
    provider: String,
    build: String,
    recipe: String,
    url: String,
    digest: String,
}

impl Document {
    /// Parse and validate a catalog document: known schema, supported
    /// platforms, algorithm-qualified digests, and everything
    /// [`Catalog::new`] checks, including that `default` names a release
    /// complete on every supported platform.
    pub fn parse(text: &str) -> io::Result<Document> {
        let raw: RawDocument =
            toml::from_str(text).map_err(|error| invalid(format!("catalog document: {error}")))?;
        if raw.schema != SCHEMA {
            return Err(invalid(format!(
                "catalog document for {}: schema {} is not {SCHEMA}; upgrade tog",
                raw.ecosystem, raw.schema
            )));
        }
        let ecosystem = raw.ecosystem;
        let mut bundles = Vec::with_capacity(raw.release.len());
        for release in raw.release {
            let bad =
                |what: String| invalid(format!("{ecosystem} catalog: {}: {what}", release.key));
            let components = release
                .components
                .into_iter()
                .map(|c| Component {
                    name: c.name,
                    version: c.version,
                    embedded_in: c.embedded_in,
                })
                .collect();
            let mut artifacts = Vec::with_capacity(release.artifacts.len());
            for row in release.artifacts {
                let platform = Platform::from_triple(&row.platform)
                    .ok_or_else(|| bad(format!("unsupported platform {:?}", row.platform)))?;
                let digest = parse_qualified(&row.digest)
                    .map_err(|error| bad(format!("{}: {error}", row.component)))?;
                artifacts.push(ArtifactRow {
                    platform,
                    component: row.component,
                    provider: row.provider,
                    build: row.build,
                    recipe: row.recipe,
                    url: row.url,
                    digest,
                });
            }
            bundles.push(Bundle {
                release: release.key,
                revision: release.revision,
                primary: raw.primary.clone(),
                components,
                artifacts,
            });
        }
        let document = Document {
            ecosystem,
            primary: raw.primary,
            default: raw.default,
            bundles,
        };
        document.catalog()?;
        Ok(document)
    }

    /// The validated catalog this document describes, its default set.
    pub fn catalog(&self) -> io::Result<Catalog> {
        Catalog::new(&self.ecosystem, self.bundles.clone())?.with_default(&self.default)
    }

    #[cfg(test)]
    /// The canonical spelling: the bytes `tools/catalog.py` writes for the
    /// same releases. Releases are ordered newest primary version first
    /// (ties keep document order), components keep bundle order, and
    /// artifact rows follow the components, then the platform triple.
    pub fn render(&self) -> io::Result<String> {
        let mut ordered: Vec<(Vec<super::Version>, &Bundle)> = self
            .bundles
            .iter()
            .map(|bundle| Ok((bundle.primary_versions()?, bundle)))
            .collect::<io::Result<_>>()?;
        ordered.sort_by(|a, b| b.0.cmp(&a.0));
        let mut out = String::new();
        out.push_str(&format!(
            "# The shipped {eco} toolchain catalog. Generated and verified by\n\
             # `python3 tools/catalog.py {eco}`: regenerate it, do not edit it by hand.\n\
             # Rows are append-only; `default` is what a project with no pin gets.\n",
            eco = self.ecosystem
        ));
        out.push_str(&format!("schema = {SCHEMA}\n"));
        out.push_str(&format!("ecosystem = {}\n", quote(&self.ecosystem)));
        out.push_str(&format!(
            "primary = [{}]\n",
            self.primary
                .iter()
                .map(|p| quote(p))
                .collect::<Vec<_>>()
                .join(", ")
        ));
        out.push_str(&format!("default = {}\n", quote(&self.default)));
        for (_, bundle) in ordered {
            out.push_str("\n[[release]]\n");
            out.push_str(&format!("key = {}\n", quote(&bundle.release)));
            if let Some(revision) = bundle.revision {
                out.push_str(&format!("revision = {revision}\n"));
            }
            out.push_str("components = [\n");
            for c in &bundle.components {
                out.push_str(&format!(
                    "  {{ name = {}, version = {}",
                    quote(&c.name),
                    quote(&c.version)
                ));
                if let Some(parent) = &c.embedded_in {
                    out.push_str(&format!(", embedded_in = {}", quote(parent)));
                }
                out.push_str(" },\n");
            }
            out.push_str("]\nartifacts = [\n");
            // Rows follow the component list, then the platform triple.
            let position = |name: &str| {
                bundle
                    .components
                    .iter()
                    .position(|c| c.name == name)
                    .unwrap_or(usize::MAX)
            };
            let mut rows: Vec<&ArtifactRow> = bundle.artifacts.iter().collect();
            rows.sort_by(|a, b| {
                (position(&a.component), a.platform.triple())
                    .cmp(&(position(&b.component), b.platform.triple()))
            });
            for row in rows {
                out.push_str(&format!(
                    "  {{ platform = {}, component = {}, provider = {}, build = {}, recipe = {}, url = {}, digest = {} }},\n",
                    quote(row.platform.triple()),
                    quote(&row.component),
                    quote(&row.provider),
                    quote(&row.build),
                    quote(&row.recipe),
                    quote(&row.url),
                    quote(&qualified(&row.digest)),
                ));
            }
            out.push_str("]\n");
        }
        Ok(out)
    }
}

#[cfg(test)]
/// A TOML basic string. Catalog fields are URLs, versions and hex, so only
/// the two characters TOML reserves need escaping; anything else a
/// generator emitted would fail [`Document::parse`] or the endpoint policy.
fn quote(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for ch in text.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            _ => out.push(ch),
        }
    }
    out.push('"');
    out
}

/// A document compiled into the binary, parsed and validated on first use.
/// A tailor declares one as a `static` over `include_str!`, so every caller
/// in the process shares one parse and one validated [`Catalog`].
pub struct Shipped {
    text: &'static str,
    parsed: OnceLock<Result<(Document, Catalog), String>>,
}

impl Shipped {
    pub const fn new(text: &'static str) -> Shipped {
        Shipped {
            text,
            parsed: OnceLock::new(),
        }
    }

    fn parsed(&'static self) -> io::Result<&'static (Document, Catalog)> {
        self.parsed
            .get_or_init(|| {
                let document = Document::parse(self.text).map_err(|e| e.to_string())?;
                let catalog = document.catalog().map_err(|e| e.to_string())?;
                Ok((document, catalog))
            })
            .as_ref()
            .map_err(|message| invalid(message.clone()))
    }

    /// The document, for callers that read rows by field.
    pub fn document(&'static self) -> io::Result<&'static Document> {
        Ok(&self.parsed()?.0)
    }

    /// The validated catalog, default set.
    pub fn catalog(&'static self) -> io::Result<Catalog> {
        Ok(self.parsed()?.1.clone())
    }

    /// The default release, as the document spells it.
    pub fn default_bundle(&'static self) -> io::Result<&'static Bundle> {
        let document = self.document()?;
        document
            .bundles
            .iter()
            .find(|bundle| bundle.release == document.default)
            .ok_or_else(|| {
                invalid(format!(
                    "{} catalog: no default release",
                    document.ecosystem
                ))
            })
    }

    /// The default release's row for one component on one platform: what a
    /// project with no pin realizes there.
    pub fn default_row(
        &'static self,
        platform: Platform,
        component: &str,
    ) -> io::Result<&'static ArtifactRow> {
        let bundle = self.default_bundle()?;
        bundle
            .artifact(platform, component)
            .ok_or_else(|| crate::kernel::platform::no_pin(component, platform))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const DOC: &str = "\
# The shipped go toolchain catalog. Generated and verified by
# `python3 tools/catalog.py go`: regenerate it, do not edit it by hand.
# Rows are append-only; `default` is what a project with no pin gets.
schema = 1
ecosystem = \"go\"
primary = [\"go\"]
default = \"go-1.2.0\"

[[release]]
key = \"go-1.3.0\"
components = [
  { name = \"go\", version = \"1.3.0\" },
  { name = \"std\", version = \"1.3.0\", embedded_in = \"go\" },
]
artifacts = [
  { platform = \"aarch64-apple-darwin\", component = \"go\", provider = \"go.dev\", build = \"1.3.0\", recipe = \"go-toolchain/1\", url = \"https://go.dev/dl/a3\", digest = \"sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\" },
  { platform = \"x86_64-unknown-linux-gnu\", component = \"go\", provider = \"go.dev\", build = \"1.3.0\", recipe = \"go-toolchain/1\", url = \"https://go.dev/dl/l3\", digest = \"sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\" },
]

[[release]]
key = \"go-1.2.0\"
revision = 2
components = [
  { name = \"go\", version = \"1.2.0\" },
]
artifacts = [
  { platform = \"aarch64-apple-darwin\", component = \"go\", provider = \"go.dev\", build = \"1.2.0\", recipe = \"go-toolchain/1\", url = \"https://go.dev/dl/a2\", digest = \"sha512:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc\" },
  { platform = \"x86_64-unknown-linux-gnu\", component = \"go\", provider = \"go.dev\", build = \"1.2.0\", recipe = \"go-toolchain/1\", url = \"https://go.dev/dl/l2\", digest = \"sha256:dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd\" },
]
";

    #[test]
    fn a_document_parses_into_the_catalog_and_renders_back_byte_for_byte() {
        let document = Document::parse(DOC).unwrap();
        assert_eq!(document.ecosystem, "go");
        assert_eq!(document.default, "go-1.2.0");
        assert_eq!(document.bundles.len(), 2);
        let newer = &document.bundles[0];
        assert_eq!(newer.primary, ["go"]);
        assert_eq!(
            newer.component("std").unwrap().embedded_in.as_deref(),
            Some("go")
        );
        assert_eq!(document.bundles[1].revision, Some(2));
        assert_eq!(
            qualified(&document.bundles[1].artifacts[0].digest),
            format!("sha512:{}", "c".repeat(128))
        );
        assert_eq!(document.render().unwrap(), DOC);
        // Render orders newest first whatever order the bundles are in.
        let mut reversed = document.clone();
        reversed.bundles.reverse();
        assert_eq!(reversed.render().unwrap(), DOC);
    }

    #[test]
    fn the_default_is_not_the_newest_release() {
        let catalog = Document::parse(DOC).unwrap().catalog().unwrap();
        assert_eq!(catalog.default_release().unwrap().release, "go-1.2.0");
        let shipped = crate::kernel::toolchain::shipped(&catalog).unwrap();
        assert_eq!(shipped.bundle.release, "go-1.2.0");
        // An explicit request still reaches the newer release.
        let exact = crate::kernel::toolchain::Request::exact("go", "1.3.0").unwrap();
        assert_eq!(catalog.select(&exact).unwrap().release, "go-1.3.0");
    }

    #[test]
    fn malformed_documents_are_refused_with_the_reason() {
        let refuse = |text: String, want: &str| {
            let error = Document::parse(&text).unwrap_err().to_string();
            assert!(error.contains(want), "{want}: {error}");
        };
        refuse(DOC.replace("schema = 1", "schema = 2"), "schema 2 is not 1");
        refuse(
            DOC.replace("default = \"go-1.2.0\"", "default = \"go-9\""),
            "default release go-9 is not in the catalog",
        );
        refuse(
            DOC.replacen("aarch64-apple-darwin", "x86_64-apple-darwin", 1),
            "unsupported platform \"x86_64-apple-darwin\"",
        );
        refuse(DOC.replacen("sha256:", "md5:", 1), "unsupported digest");
        refuse(DOC.replacen("sha256:a", "sha256:z", 1), "malformed sha256");
        refuse(
            DOC.replace("schema = 1\n", "schema = 1\nextra = 1\n"),
            "unknown field",
        );
        refuse(
            DOC.replacen("key = \"go-1.2.0\"", "key = \"go-1.3.0\"", 1),
            "duplicate release key",
        );
        // A default must be complete on every platform, or no host could
        // realize what an unpinned project gets.
        let darwin_only = DOC.replace(
            "  { platform = \"x86_64-unknown-linux-gnu\", component = \"go\", provider = \"go.dev\", build = \"1.2.0\", recipe = \"go-toolchain/1\", url = \"https://go.dev/dl/l2\", digest = \"sha256:dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd\" },\n",
            "",
        );
        refuse(darwin_only, "default release go-1.2.0 is not complete");
    }
}
