use blanket::{
    cargo, dotnet, elixir, gc, golang, npm, npm_lock_import, platform::Platform, policy, project,
    pypi, pyselect, python, ruby, sbom, store, types,
};

use std::io;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::exit;

const PLANNER_SCHEMA: &str = "python-planner/3";

const USAGE: &str = "\
blanket — universal realization & environment kernel (python + node + cargo)

USAGE:
  blanket sync [--fresh] [--strict]  realize + project env(s) from lockfiles
                          (--fresh rebuilds the projection, dropping caches)
  blanket plan            print the locked plan(s) as JSON
  blanket build [eco] [args...]  sandboxed, network-denied build (cargo | go;
                          inferred when only one is present)
  blanket run <cmd...>    run a command inside the projected environment(s)
  blanket run dev/test    run the package.json script inside the projected env
                          (script wins over a same-named PATH executable)
  blanket sbom [--output <file>]  CycloneDX 1.5 SBOM from the synced closures
  blanket gc [--dry-run] [--keep-days N] [--project] [--collect-legacy]
                          [--register <dir>...]
                          collect unreferenced objects and cached artifacts
  blanket store path      print the store root
  blanket store roots     list registered project roots

Project inputs (either or both):
  requirements.txt or pyproject.toml
                          python deps; ranged files are auto-locked via uv
                          into requirements.lock.txt (hash-pinned)
  .python-version         optional; otherwise select from project constraints (default: CPython 3.12.14)
  package-lock.json       npm lockfile v2/v3
  pnpm-lock.yaml          pnpm lockfile v9 (v6 importer shape also accepted)
  yarn.lock               Yarn classic v1 lockfile
  Cargo.toml/Cargo.lock   Rust deps; missing Cargo.lock is generated by store Cargo
  go.mod/go.sum           Go deps; closure computed by the store Go toolchain
  Gemfile/Gemfile.lock    Ruby gems; missing lock resolved by store bundler
  mix.exs/mix.lock        Elixir hex deps; missing lock resolved by store mix
  *.csproj + packages.lock.json  .NET NuGet deps (lock made mandatory)
";

fn planner_input_hash(
    platform: Platform,
    python_version: &str,
    text: &str,
    glibc: pypi::Glibc,
) -> String {
    use sha2::{Digest, Sha256};
    let glibc_input = if matches!(platform, Platform::X86_64UnknownLinuxGnu) {
        format!("\0{}.{}", glibc.0, glibc.1)
    } else {
        String::new()
    };
    hex::encode(Sha256::digest(
        format!(
            "{PLANNER_SCHEMA}\x00{python_version}\x00{text}\x00{}{glibc_input}",
            platform.triple(),
        )
        .as_bytes(),
    ))
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let Some(command) = args.first().map(String::as_str) else {
        eprint!("{USAGE}");
        exit(2);
    };
    let supported = matches!(command, "sync" | "plan" | "build" | "run" | "sbom" | "gc")
        || (command == "store"
            && matches!(args.get(1).map(String::as_str), Some("path") | Some("roots")));
    if !supported {
        eprint!("{USAGE}");
        exit(2);
    }
    // Maintenance commands do not need host-platform validation. In
    // particular, GC must remain usable when inspecting a copied store on a
    // host that cannot realize its objects.
    if command == "gc" {
        let code = run_gc(&args[1..])
            .map(|_| 0)
            .unwrap_or_else(|e| {
                eprintln!("blanket: error: {e}");
                1
            });
        exit(code);
    }
    if command == "store" && args.get(1).map(String::as_str) == Some("roots") {
        let code = run_store_roots(&args[2..])
            .map(|_| 0)
            .unwrap_or_else(|e| {
                eprintln!("blanket: error: {e}");
                1
            });
        exit(code);
    }
    // Help and usage return above without host validation; real subcommands
    // validate once before any store-touching work.
    let platform = match Platform::host() {
        Ok(platform) => platform,
        Err(error) => {
            eprintln!("blanket: error: {error}");
            exit(1);
        }
    };
    let code = match args.first().map(String::as_str) {
        Some("sync") => run_sync(
            platform,
            args.iter().any(|a| a == "--fresh"),
            args.iter().any(|a| a == "--strict"),
        ),
        Some("plan") => run_plan(platform),
        Some("build") => run_build(platform, &args[1..]),
        Some("run") => run_run(platform, &args[1..]),
        Some("sbom") => run_sbom(&args[1..]),
        Some("store") if args.get(1).map(String::as_str) == Some("path") => {
            store::Store::open().map(|s| println!("{}", s.root.display()))
        }
        _ => {
            eprint!("{USAGE}");
            exit(2);
        }
    }
    .map(|_| 0)
    .unwrap_or_else(|e| {
        eprintln!("blanket: error: {e}");
        1
    });
    exit(code);
}

fn run_sbom(args: &[String]) -> io::Result<()> {
    let doc = sbom::generate(&project_dir())?;
    let text = serde_json::to_string_pretty(&doc)?;
    match args.first().map(String::as_str) {
        Some("--output") => {
            let path = args
                .get(1)
                .ok_or_else(|| io::Error::other("--output needs a file path"))?;
            std::fs::write(path, text + "\n")?;
            eprintln!("blanket: SBOM written to {path}");
            Ok(())
        }
        Some(other) => Err(io::Error::other(format!("unknown sbom argument: {other}"))),
        None => {
            println!("{text}");
            Ok(())
        }
    }
}

fn run_store_roots(args: &[String]) -> io::Result<()> {
    if !args.is_empty() {
        return Err(io::Error::other("store roots takes no arguments"));
    }
    for root in store::Store::open()?.roots()? {
        println!("{}", root.path.display());
    }
    Ok(())
}

fn run_gc(args: &[String]) -> io::Result<()> {
    let mut options = gc::Options::default();
    let mut register = Vec::new();
    let mut index = 0;
    while index < args.len() {
        match args[index].as_str() {
            "--dry-run" => options.dry_run = true,
            "--project" => options.project = true,
            "--collect-legacy" => options.collect_legacy = true,
            "--register" => {
                index += 1;
                let first = index;
                while index < args.len() && !args[index].starts_with("--") {
                    register.push(PathBuf::from(&args[index]));
                    index += 1;
                }
                if first == index {
                    return Err(io::Error::new(
                        io::ErrorKind::InvalidInput,
                        "--register needs at least one project directory",
                    ));
                }
                continue;
            }
            value if value.starts_with("--register=") => {
                let path = &value["--register=".len()..];
                if path.is_empty() {
                    return Err(io::Error::new(
                        io::ErrorKind::InvalidInput,
                        "--register needs a project directory",
                    ));
                }
                register.push(PathBuf::from(path));
            }
            "--keep-days" => {
                index += 1;
                let value = args.get(index).ok_or_else(|| {
                    io::Error::new(io::ErrorKind::InvalidInput, "--keep-days needs N")
                })?;
                options.keep_days = value.parse().map_err(|_| {
                    io::Error::new(io::ErrorKind::InvalidInput, "--keep-days expects an integer")
                })?;
            }
            value if value.starts_with("--keep-days=") => {
                options.keep_days = value["--keep-days=".len()..].parse().map_err(|_| {
                    io::Error::new(io::ErrorKind::InvalidInput, "--keep-days expects an integer")
                })?;
            }
            other => {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    format!("unknown gc argument: {other}"),
                ));
            }
        }
        index += 1;
    }
    let store = store::Store::open()?;
    let mut stdout = io::stdout().lock();
    for project in register {
        let entry = store.register_root(&project)?;
        writeln!(stdout, "blanket: registered root {}", entry.path.display())?;
    }
    let report = gc::collect(&store, options, &mut stdout)?;
    let verb = if options.dry_run { "would free" } else { "freed" };
    writeln!(
        stdout,
        "blanket: gc {verb} {} MB ({} objects, {} cached artifacts)",
        report.freed_bytes / (1024 * 1024),
        report.objects,
        report.cached_artifacts
    )?;
    Ok(())
}

fn project_dir() -> PathBuf {
    std::env::current_dir().expect("cwd")
}

/// Implicit detection for sync/plan: cargo joins the party only when the
/// invocation dir is itself a Cargo package (workspace members included).
/// Without this gate, running blanket in any project nested under an
/// unrelated Cargo workspace would silently project into that parent tree.
fn is_cargo_here(dir: &Path) -> bool {
    dir.join("Cargo.toml").is_file() || dir.join("Cargo.lock").is_file()
}

struct CargoInputs {
    root: PathBuf,
    rust_obj: PathBuf,
    plan: cargo::CargoPlan,
    lock_digest: String,
}

/// Workspace rooting is delegated to the pinned Cargo itself
/// (`locate-project --workspace`): an ancestor-walk for Cargo.lock picks an
/// unrelated outer lock when independent packages nest (Sol review, repro'd).
fn locate_cargo_root(rust_obj: &Path, cwd: &Path) -> io::Result<PathBuf> {
    let out = std::process::Command::new(rust_obj.join("bin/cargo"))
        .args([
            "locate-project",
            "--workspace",
            "--message-format",
            "plain",
            "--offline",
        ])
        .current_dir(cwd)
        .env_remove("RUSTUP_HOME")
        .env_remove("RUSTUP_TOOLCHAIN")
        .output()
        .map_err(|e| io::Error::new(e.kind(), format!("run store cargo locate-project: {e}")))?;
    if !out.status.success() {
        return Err(io::Error::other(format!(
            "cargo locate-project failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        )));
    }
    let manifest = PathBuf::from(String::from_utf8_lossy(&out.stdout).trim());
    manifest
        .parent()
        .map(Path::to_path_buf)
        .ok_or_else(|| io::Error::other("cargo locate-project returned no manifest path"))
}

fn load_cargo_inputs(
    platform: Platform,
    cwd: &Path,
    store: &store::Store,
) -> io::Result<CargoInputs> {
    let rust_version = cargo::resolve_toolchain(platform, cwd)?;
    let rust_obj = cargo::ensure_rust_for(store, platform, rust_version)?;
    let root = locate_cargo_root(&rust_obj, cwd)?;
    if !root.join("Cargo.lock").is_file() {
        ensure_cargo_lock(&root, &rust_obj)?;
    }
    let lock = std::fs::read_to_string(root.join("Cargo.lock"))?;
    let plan = cargo::plan_cargo(&lock, rust_version)?;
    Ok(CargoInputs {
        root,
        rust_obj,
        plan,
        lock_digest: cargo::lock_digest(&lock),
    })
}

fn ensure_cargo_lock(root: &Path, rust_obj: &Path) -> io::Result<()> {
    eprintln!(
        "blanket: no Cargo.lock; generating it with the store Rust toolchain \
         (network allowed, unsandboxed)..."
    );
    let status = std::process::Command::new(rust_obj.join("bin/cargo"))
        .arg("generate-lockfile")
        .current_dir(root)
        .env("CARGO_NET_OFFLINE", "false")
        .env_remove("RUSTUP_HOME")
        .env_remove("RUSTUP_TOOLCHAIN")
        .status()
        .map_err(|e| {
            io::Error::new(
                e.kind(),
                format!(
                    "could not run store Cargo to generate Cargo.lock: {e}; \
                     use `blanket sync` after fixing the project or network"
                ),
            )
        })?;
    if !status.success() {
        return Err(io::Error::other(
            "store Cargo generate-lockfile failed; check the project manifest and network",
        ));
    }
    Ok(())
}

/// Plan from project inputs. Planning hits PyPI, so successful plans are
/// cached in .blanket/plan.json keyed by a hash of the inputs; an unchanged
/// lock replans offline and instantly.
fn read_plan(
    platform: Platform,
    dir: &Path,
    selection: &pyselect::PythonSelection,
) -> io::Result<types::Plan> {
    let req_path = dir.join("requirements.txt");
    let (input, source) = if req_path.is_file() {
        (
            "requirements.txt".to_string(),
            std::fs::read_to_string(&req_path)
                .map_err(|e| io::Error::new(e.kind(), format!("{}: {e}", req_path.display())))?,
        )
    } else {
        let pyproject = dir.join("pyproject.toml");
        let source = std::fs::read_to_string(&pyproject)
            .map_err(|e| io::Error::new(e.kind(), format!("{}: {e}", pyproject.display())))?;
        let value: toml::Value = toml::from_str(&source).map_err(|e| {
            io::Error::new(
                io::ErrorKind::InvalidData,
                format!("{}: {e}", pyproject.display()),
            )
        })?;
        let has_dependencies = value
            .get("project")
            .and_then(toml::Value::as_table)
            .and_then(|project| project.get("dependencies"))
            .and_then(toml::Value::as_array)
            .is_some();
        if !has_dependencies {
            return Err(no_inputs());
        }
        ("pyproject.toml".to_string(), source)
    };
    record_skippable_specs(&input, &source)?;
    // The caller selected the interpreter once; planning, realization and
    // the closure all use that same selection even if project files change
    // underneath a running sync.
    let pin = selection.pin;

    let text = if input == "pyproject.toml" {
        locked_requirements(platform, dir, &input, &source, pin.version)?
    } else if is_fully_pinned(&source) {
        match pypi::parse_requirements(&source) {
            Ok(_) => source,
            Err(e) if e.kind() == io::ErrorKind::PermissionDenied => return Err(e),
            Err(e) => {
                eprintln!(
                    "blanket: requirements.txt is pinned but not directly \
                     consumable ({e}); re-locking for this platform with uv..."
                );
                locked_requirements(platform, dir, &input, &source, pin.version)?
            }
        }
    } else {
        locked_requirements(platform, dir, &input, &source, pin.version)?
    };

    // These are project-local .blanket caches, not store identities; one
    // re-plan after moving a project between platforms is acceptable.
    let glibc = if matches!(platform, Platform::X86_64UnknownLinuxGnu) {
        pypi::host_glibc()?
    } else {
        pypi::Glibc(0, 0)
    };
    let input_hash = planner_input_hash(platform, pin.version, &text, glibc);
    let cache_path = dir.join(".blanket/plan.json");
    if let Ok(cached) = std::fs::read_to_string(&cache_path) {
        if let Ok(v) = serde_json::from_str::<serde_json::Value>(&cached) {
            if v["input_hash"] == input_hash.as_str() {
                if let Ok(plan) = serde_json::from_value(v["plan"].clone()) {
                    return Ok(plan);
                }
            }
        }
    }

    let plan = pypi::plan_python(platform, &text, pin.version)?;
    std::fs::create_dir_all(dir.join(".blanket"))?;
    std::fs::write(
        &cache_path,
        serde_json::to_vec_pretty(&serde_json::json!({
            "input_hash": input_hash,
            "plan": plan,
        }))?,
    )?;
    Ok(plan)
}

fn record_skippable_specs(input: &str, source: &str) -> io::Result<()> {
    record_skippable_specs_with(input, source, policy::record)
}

fn record_skippable_specs_with<F>(
    input: &str,
    source: &str,
    mut record: F,
) -> io::Result<()>
where
    F: FnMut(&str, &str, &str) -> io::Result<()>,
{
    let specs: Vec<String> = if input == "requirements.txt" {
        pypi::skippable_specs(source)
    } else {
        let value: toml::Value = toml::from_str(source).map_err(|e| {
            io::Error::new(io::ErrorKind::InvalidData, format!("pyproject.toml: {e}"))
        })?;
        value
            .get("project")
            .and_then(toml::Value::as_table)
            .and_then(|project| project.get("dependencies"))
            .and_then(toml::Value::as_array)
            .into_iter()
            .flatten()
            .filter_map(toml::Value::as_str)
            .filter(|spec| pypi::is_skippable_spec(spec))
            .map(str::to_string)
            .collect()
    };
    for spec in specs {
        record(
            policy::REQUIREMENT_SKIPPED,
            &spec,
            "project-local or direct reference is not a locked registry package",
        )?;
    }
    Ok(())
}

/// Every non-comment logical line (after backslash continuations) carries a
/// --hash= option. That is the shape `uv pip compile --generate-hashes`
/// emits and the only shape the planner accepts directly.
fn is_fully_pinned(text: &str) -> bool {
    let mut logical = String::new();
    let mut any = false;
    for raw in text.lines().chain(std::iter::once("")) {
        if let Some(stripped) = raw.strip_suffix('\\') {
            logical.push_str(stripped);
            continue;
        }
        logical.push_str(raw);
        let line = logical.trim();
        let line = match line.find(" #") {
            Some(i) => line[..i].trim(),
            None => line,
        };
        if !line.is_empty() && !line.starts_with('#') {
            any = true;
            let spec = line
                .split_whitespace()
                .filter(|token| !token.starts_with("--hash="))
                .collect::<Vec<_>>()
                .join(" ");
            if pypi::is_skippable_spec(&spec) {
                logical.clear();
                continue;
            }
            if !line.contains("--hash=") {
                return false;
            }
        }
        logical.clear();
    }
    any
}

/// Resolve ranged requirements to a hash-pinned lock via uv, cached in
/// requirements.lock.txt and regenerated when the source input changes.
fn locked_requirements(
    platform: Platform,
    dir: &Path,
    input: &str,
    source: &str,
    pyver: &str,
) -> io::Result<String> {
    let lock_path = dir.join("requirements.lock.txt");
    let stamp_path = dir.join(".blanket/lock-source.hash");
    let source_hash = lock_source_hash(pyver, source);
    if let (Ok(stamp), Ok(lock)) = (
        std::fs::read_to_string(&stamp_path),
        std::fs::read_to_string(&lock_path),
    ) {
        if stamp.trim() == source_hash {
            return Ok(lock);
        }
    }
    eprintln!("blanket: {input} is not hash-pinned; resolving with the store uv...");
    // Store-pinned uv, not host uv: a bare machine needs only blanket.
    let uv = python::ensure_uv_for(&store::Store::open()?, platform)?.join("uv");
    let status = std::process::Command::new(&uv)
        .args(["pip", "compile", input, "--generate-hashes", "--quiet"])
        .args(["--python-version", pyver])
        .args(["-o", "requirements.lock.txt"])
        .current_dir(dir)
        .status()
        .map_err(|e| io::Error::new(e.kind(), format!("run store uv ({}): {e}", uv.display())))?;
    if !status.success() {
        return Err(io::Error::other("uv pip compile failed"));
    }
    std::fs::create_dir_all(dir.join(".blanket"))?;
    std::fs::write(&stamp_path, &source_hash)?;
    std::fs::read_to_string(&lock_path)
}

/// Stamp deciding whether `uv pip compile` must re-run. Deliberately NOT
/// platform-qualified: `.blanket/lock-source.hash` is per-machine state and
/// the format is byte-identical to the pre-port one, so existing darwin
/// stamps stay valid after the Linux port (platform lives in
/// `planner_input_hash`, which keys the plan cache).
fn lock_source_hash(pyver: &str, source: &str) -> String {
    use sha2::{Digest, Sha256};
    hex::encode(Sha256::digest(format!("{pyver}\x00{source}").as_bytes()))
}

fn run_plan(platform: Platform) -> io::Result<()> {
    let dir = project_dir();
    policy::init(&dir, false)?;
    ensure_npm_lock(platform, &dir)?;
    let mut any = false;
    if has_python_input(&dir)? {
        let selection = select_python_for(platform, &dir)?;
        let plan = read_plan(platform, &dir, &selection)?;
        println!("{}", serde_json::to_string_pretty(&plan)?);
        any = true;
    }
    if let Some(plan) = load_npm_plan(platform, &dir)? {
        let v: Vec<_> = plan
            .packages
            .iter()
            .map(|p| {
                serde_json::json!({"path": p.path, "version": p.version,
                                   "url": p.url, "integrity": p.integrity})
            })
            .collect();
        println!(
            "{}",
            serde_json::to_string_pretty(&serde_json::json!({
                "ecosystem": "node", "node_version": plan.node_version,
                "lock_source": plan.lock_source, "packages": v
            }))?
        );
        any = true;
    }
    if is_cargo_here(&dir) {
        let store = store::Store::open()?;
        let inputs = load_cargo_inputs(platform, &dir, &store)?;
        println!("{}", serde_json::to_string_pretty(&inputs.plan)?);
        any = true;
    }
    if dir.join("go.mod").is_file() {
        let store = store::Store::open()?;
        let inputs = load_go_inputs(platform, &dir, &store)?;
        println!("{}", serde_json::to_string_pretty(&inputs.plan)?);
        any = true;
    }
    if dir.join("Gemfile").is_file() {
        let store = store::Store::open()?;
        let ruby_obj = ruby::ensure_ruby_for(&store, platform)?;
        let (plan, _) = ruby::plan_ruby(&store, &dir, &ruby_obj)?;
        println!("{}", serde_json::to_string_pretty(&plan)?);
        any = true;
    }
    if dir.join("mix.exs").is_file() {
        let store = store::Store::open()?;
        let beam = elixir::ensure_beam_for(&store, platform)?;
        let (plan, _) = elixir::plan_elixir(&store, &dir, &beam)?;
        println!("{}", serde_json::to_string_pretty(&plan)?);
        any = true;
    }
    if dotnet::has_marker(&dir)? {
        // Preflight before SDK realization: a broken layout should fail
        // loudly here, not after a toolchain download.
        dotnet::preflight(&dir)?;
        let store = store::Store::open()?;
        let sdk = dotnet::ensure_sdk_for(&store, platform)?;
        let (plan, _) = dotnet::plan_dotnet(&store, &dir, &sdk)?;
        println!("{}", serde_json::to_string_pretty(&plan)?);
        any = true;
    }
    if !any {
        return Err(no_inputs());
    }
    Ok(())
}

/// One interpreter selection per command, shared by planning, realization and
/// the closure so they can never disagree.
fn select_python_for(platform: Platform, dir: &Path) -> io::Result<pyselect::PythonSelection> {
    let selection =
        pyselect::select_python_with_inputs(platform, &pyselect::collect_project_inputs(dir)?)?;
    selection.emit_warnings();
    Ok(selection)
}

fn no_inputs() -> io::Error {
    io::Error::new(
        io::ErrorKind::NotFound,
        "nothing to sync here (need requirements.txt, pyproject.toml with [project].dependencies, package-lock.json, pnpm-lock.yaml, yarn.lock, Cargo.toml, or go.mod)",
    )
}

fn has_python_input(dir: &Path) -> io::Result<bool> {
    if dir.join("requirements.txt").is_file() {
        return Ok(true);
    }
    let path = dir.join("pyproject.toml");
    if !path.is_file() {
        return Ok(false);
    }
    let text = std::fs::read_to_string(&path)?;
    let value: toml::Value = toml::from_str(&text).map_err(|e| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("{}: {e}", path.display()),
        )
    })?;
    Ok(value
        .get("project")
        .and_then(toml::Value::as_table)
        .and_then(|project| project.get("dependencies"))
        .and_then(toml::Value::as_array)
        .is_some())
}

struct GoInputs {
    go_obj: PathBuf,
    plan: golang::GoPlan,
    gosum_sha256: String,
}

fn load_go_inputs(
    platform: Platform,
    dir: &Path,
    store: &store::Store,
) -> io::Result<GoInputs> {
    let go_obj = golang::ensure_go_for(store, platform)?;
    let plan = golang::plan_go(store, platform, dir, &go_obj)?;
    let gosum = std::fs::read_to_string(dir.join("go.sum")).unwrap_or_default();
    use sha2::{Digest, Sha256};
    Ok(GoInputs {
        go_obj,
        plan,
        gosum_sha256: hex::encode(Sha256::digest(gosum.as_bytes())),
    })
}

/// A package.json without a package-lock.json (bun/yarn/pnpm projects):
/// delegate lock generation to npm, mirroring the uv flow for Python.
/// Resolution is the ecosystem's job; realization is blanket's.
fn ensure_npm_lock(platform: Platform, dir: &Path) -> io::Result<()> {
    if !dir.join("package.json").exists()
        || dir.join("package-lock.json").exists()
        || dir.join("pnpm-lock.yaml").exists()
        || dir.join("yarn.lock").exists()
    {
        return Ok(());
    }
    for other in ["bun.lock", "bun.lockb"] {
        if dir.join(other).exists() {
            eprintln!(
                "blanket: note: {other} found; generating package-lock.json via npm \
                 (versions resolve fresh — they may differ from {other})"
            );
            break;
        }
    }
    eprintln!("blanket: no package-lock.json; resolving with the store npm...");
    // Store node's bundled npm, not host npm: a bare machine needs only
    // blanket. npm-cli's shebang is `env node`, so the store bin leads PATH.
    let node = npm::ensure_node_for(&store::Store::open()?, platform)?;
    let path = format!(
        "{}:{}",
        node.join("bin").display(),
        std::env::var("PATH").unwrap_or_default()
    );
    let status = std::process::Command::new(node.join("bin/npm"))
        .args([
            "install",
            "--package-lock-only",
            "--ignore-scripts",
            "--silent",
        ])
        .current_dir(dir)
        .env("PATH", path)
        .status()
        .map_err(|e| {
            io::Error::new(
                e.kind(),
                format!("run store npm ({}/bin/npm): {e}", node.display()),
            )
        })?;
    if !status.success() {
        return Err(io::Error::other("npm install --package-lock-only failed"));
    }
    Ok(())
}

fn preflight_sync(platform: Platform, dir: &Path) -> io::Result<()> {
    if [
        "package.json",
        "package-lock.json",
        "pnpm-lock.yaml",
        "yarn.lock",
    ]
    .iter()
    .any(|name| dir.join(name).is_file())
    {
        npm::preflight(platform)?;
    }
    if has_python_input(dir)? {
        let selection = pyselect::select_python_with_inputs(
            platform,
            &pyselect::collect_project_inputs(dir)?,
        )?;
        python::preflight(platform, selection.pin.version)?;
    }
    if dir.join("go.mod").is_file() {
        golang::preflight_platform(platform)?;
    }
    if dir.join("Gemfile").is_file() {
        ruby::preflight_platform(platform)?;
    }
    if dir.join("mix.exs").is_file() {
        elixir::preflight_platform(platform)?;
    }
    if dotnet::has_marker(dir)? {
        dotnet::preflight_platform(platform)?;
    }
    if is_cargo_here(dir) {
        cargo::preflight_platform(platform)?;
    }
    Ok(())
}

fn run_sync(platform: Platform, fresh: bool, strict: bool) -> io::Result<()> {
    let dir = project_dir();
    policy::init(&dir, strict)?;
    preflight_sync(platform, &dir)?;
    let store = store::Store::open()?;
    ensure_npm_lock(platform, &dir)?;
    let mut any = false;
    if has_python_input(&dir)? {
        let selection = select_python_for(platform, &dir)?;
        let plan = read_plan(platform, &dir, &selection)?;
        let env = project::realize_env(&store, platform, &plan)?;
        project::project_env_with_selection(&dir, &env, &plan, &selection)?;
        eprintln!("synced: .venv -> {}", env.display());
        any = true;
    }
    if let Some(plan) = load_npm_plan(platform, &dir)? {
        let mut config = npm::BlanketConfig::default();
        if plan.lock_source == "package-lock.json" {
            let lock = std::fs::read_to_string(dir.join("package-lock.json"))?;
            if let Ok(pkg) = std::fs::read_to_string(dir.join("package.json")) {
                npm::check_lock_freshness(&pkg, &lock)?;
                config = npm::parse_blanket_config(&pkg)?;
            }
        } else if let Ok(pkg) = std::fs::read_to_string(dir.join("package.json")) {
            config = npm::parse_blanket_config(&pkg)?;
        }
        let env = npm::realize_node_env(&store, platform, &plan, &config.artifacts)?;
        npm::project_node_env(&dir, &env, platform, &plan, &config.mutable_packages, fresh)?;
        eprintln!("synced: node_modules -> {}", env.display());
        any = true;
    }
    if dir.join("go.mod").is_file() {
        let inputs = load_go_inputs(platform, &dir, &store)?;
        let modcache = golang::realize_modcache(&store, platform, &inputs.plan, &inputs.go_obj)?;
        golang::project_go_env(
            &dir,
            &inputs.go_obj,
            &modcache,
            &inputs.plan,
            &inputs.gosum_sha256,
        )?;
        eprintln!("synced: go modcache -> {}", modcache.display());
        any = true;
    }
    if dir.join("Gemfile").is_file() {
        let ruby_obj = ruby::ensure_ruby_for(&store, platform)?;
        let (plan, lock_sha256) = ruby::plan_ruby(&store, &dir, &ruby_obj)?;
        let gems = ruby::realize_gems(&store, platform, &plan, &ruby_obj)?;
        ruby::project_ruby_env(&dir, &ruby_obj, &gems, &plan, &lock_sha256)?;
        eprintln!("synced: gems -> {}", gems.display());
        any = true;
    }
    if dir.join("mix.exs").is_file() {
        let beam = elixir::ensure_beam_for(&store, platform)?;
        let (plan, lock_sha256) = elixir::plan_elixir(&store, &dir, &beam)?;
        let deps = elixir::realize_deps(&store, platform, &plan, &beam)?;
        let projection =
            elixir::project_elixir_env(platform, &dir, &beam, &deps, &plan, &lock_sha256, fresh)?;
        eprintln!("synced: hex deps -> {}", projection.display());
        any = true;
    }
    if dotnet::has_marker(&dir)? {
        dotnet::preflight(&dir)?;
        let sdk = dotnet::ensure_sdk_for(&store, platform)?;
        let (plan, lock_sha256) = dotnet::plan_dotnet(&store, &dir, &sdk)?;
        let packages = dotnet::realize_packages(&store, platform, &plan, &sdk, &dir)?;
        dotnet::project_dotnet_env(&dir, &sdk, &packages, &plan, &lock_sha256)?;
        eprintln!("synced: nuget packages -> {}", packages.display());
        any = true;
    }
    if is_cargo_here(&dir) {
        let inputs = load_cargo_inputs(platform, &dir, &store)?;
        let rust_obj = &inputs.rust_obj;
        let vendor_obj = cargo::realize_vendor(&store, &inputs.plan)?;
        if fresh {
            let cargo_home = inputs.root.join(".blanket/cargo-home");
            if std::fs::symlink_metadata(&cargo_home).is_ok() {
                store::remove_tree(&cargo_home)?;
            }
        }
        cargo::project_cargo_env(
            &inputs.root,
            rust_obj,
            &vendor_obj,
            &inputs.plan,
            &inputs.lock_digest,
        )?;
        eprintln!("synced: cargo env -> {}", vendor_obj.display());
        any = true;
    }
    if !any {
        return Err(no_inputs());
    }
    print_exception_summary(&dir)?;
    Ok(())
}

fn load_npm_plan(platform: Platform, dir: &Path) -> io::Result<Option<npm::NpmPlan>> {
    if dir.join("package-lock.json").is_file() {
        return Ok(Some(npm::plan_npm(
            platform,
            &std::fs::read_to_string(dir.join("package-lock.json"))?,
        )?));
    }
    if dir.join("pnpm-lock.yaml").is_file() {
        return Ok(Some(npm_lock_import::plan_pnpm(
            platform,
            &std::fs::read_to_string(dir.join("pnpm-lock.yaml"))?,
            dir,
        )?));
    }
    if dir.join("yarn.lock").is_file() {
        let package = std::fs::read_to_string(dir.join("package.json"))?;
        return Ok(Some(npm_lock_import::plan_yarn(
            platform,
            &std::fs::read_to_string(dir.join("yarn.lock"))?,
            &package,
            dir,
        )?));
    }
    Ok(None)
}

fn print_exception_summary(project_dir: &Path) -> io::Result<()> {
    let dir = project_dir.join(".blanket/closures");
    let mut total = 0;
    if let Ok(entries) = std::fs::read_dir(dir) {
        for entry in entries.flatten() {
            if !entry.file_name().to_string_lossy().ends_with(".json") {
                continue;
            }
            let text = match std::fs::read_to_string(entry.path()) {
                Ok(text) => text,
                Err(_) => continue,
            };
            let value: serde_json::Value = match serde_json::from_str(&text) {
                Ok(value) => value,
                Err(_) => continue,
            };
            total += value["body"]["exceptions"].as_array().map_or(0, Vec::len);
        }
    }
    if total > 0 {
        eprintln!(
            "blanket: {total} exception(s) recorded in .blanket/closures/*.json — \
             `blanket sync --strict` to refuse them"
        );
    }
    Ok(())
}

/// `blanket build [ecosystem] [args...]`: explicit ecosystem, or inferred
/// when exactly one build-capable ecosystem is present (Sol review 4).
fn run_build(platform: Platform, args: &[String]) -> io::Result<()> {
    let cwd = project_dir();
    let (eco, rest): (&str, &[String]) = match args.first().map(String::as_str) {
        Some("cargo") => ("cargo", &args[1..]),
        Some("go") => ("go", &args[1..]),
        Some("elixir") => ("elixir", &args[1..]),
        Some("dotnet") => ("dotnet", &args[1..]),
        _ => {
            let mut present = Vec::new();
            if cwd.ancestors().any(is_cargo_here) {
                present.push("cargo");
            }
            if cwd.ancestors().any(|d| d.join("go.mod").is_file()) {
                present.push("go");
            }
            if cwd.ancestors().any(|d| d.join("mix.exs").is_file()) {
                present.push("elixir");
            }
            if dotnet::has_marker(&cwd)? {
                present.push("dotnet");
            }
            match present.as_slice() {
                [one] => (*one, args),
                [] => {
                    return Err(io::Error::new(
                        io::ErrorKind::NotFound,
                        "blanket build requires a Cargo.toml, go.mod, or mix.exs project",
                    ))
                }
                many => {
                    return Err(io::Error::new(
                        io::ErrorKind::InvalidInput,
                        format!(
                            "multiple build-capable ecosystems found ({}); specify one: \
                             `blanket build <ecosystem> ...`",
                            many.join(", ")
                        ),
                    ))
                }
            }
        }
    };
    let root = match eco {
        "cargo" => cwd
            .ancestors()
            .find(|dir| dir.join("Cargo.toml").is_file())
            .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "no Cargo.toml found from here upward"))?
            .to_path_buf(),
        "go" => cwd
            .ancestors()
            .find(|dir| dir.join("go.mod").is_file())
            .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "no go.mod found from here upward"))?
            .to_path_buf(),
        "elixir" => cwd
            .ancestors()
            .find(|dir| dir.join("mix.exs").is_file())
            .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "no mix.exs found from here upward"))?
            .to_path_buf(),
        _ => cwd.clone(),
    };
    policy::init(&root, false)?;
    let store = store::Store::open()?;
    match eco {
        "cargo" => {
            let inputs = load_cargo_inputs(platform, &cwd, &store)?;
            let vendor_obj = cargo::realize_vendor(&store, &inputs.plan)?;
            cargo::project_cargo_env(
                &inputs.root,
                &inputs.rust_obj,
                &vendor_obj,
                &inputs.plan,
                &inputs.lock_digest,
            )?;
            cargo::build_sandboxed(
                platform,
                &inputs.root,
                &inputs.rust_obj,
                &vendor_obj,
                rest,
            )
        }
        "go" => {
            let root = cwd
                .ancestors()
                .find(|d| d.join("go.mod").is_file())
                .ok_or_else(|| {
                    io::Error::new(io::ErrorKind::NotFound, "no go.mod found from here upward")
                })?
                .to_path_buf();
            let inputs = load_go_inputs(platform, &root, &store)?;
            let modcache = golang::realize_modcache(&store, platform, &inputs.plan, &inputs.go_obj)?;
            golang::project_go_env(
                &root,
                &inputs.go_obj,
                &modcache,
                &inputs.plan,
                &inputs.gosum_sha256,
            )?;
            golang::build_sandboxed(platform, &root, &inputs.go_obj, &modcache, rest)
        }
        "elixir" => {
            let root = cwd
                .ancestors()
                .find(|d| d.join("mix.exs").is_file())
                .ok_or_else(|| {
                    io::Error::new(io::ErrorKind::NotFound, "no mix.exs found from here upward")
                })?
                .to_path_buf();
            let beam = elixir::ensure_beam_for(&store, platform)?;
            let (plan, lock_sha256) = elixir::plan_elixir(&store, &root, &beam)?;
            let deps = elixir::realize_deps(&store, platform, &plan, &beam)?;
            let projection =
                elixir::project_elixir_env(platform, &root, &beam, &deps, &plan, &lock_sha256, false)?;
            elixir::build_sandboxed(platform, &root, &beam, &projection, rest)
        }
        _ => {
            let sdk = dotnet::ensure_sdk_for(&store, platform)?;
            let (plan, lock_sha256) = dotnet::plan_dotnet(&store, &cwd, &sdk)?;
            let packages = dotnet::realize_packages(&store, platform, &plan, &sdk, &cwd)?;
            dotnet::project_dotnet_env(&cwd, &sdk, &packages, &plan, &lock_sha256)?;
            dotnet::build_sandboxed(platform, &cwd, &sdk, &packages, rest)
        }
    }
}

/// Nearest ancestor that is a blanket projection: every tailor writes
/// `.blanket/closures/<eco>.json`, so that directory is the proof. A plain
/// `node_modules` or `.venv` in a subdirectory (a docs site, a vendored
/// tool) is NOT a projection and must not stop the walk-up (Sol, task
/// runner review).
fn projected_root(cwd: &Path) -> PathBuf {
    cwd.ancestors()
        .find(|d| d.join(".blanket/closures").is_dir())
        .unwrap_or(cwd)
        .to_path_buf()
}

fn refuse_dotnet_script(has_dotnet_closure: bool, script_resolved: bool) -> bool {
    has_dotnet_closure && script_resolved
}

fn run_run(platform: Platform, cmd: &[String]) -> io::Result<()> {
    if cmd.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "run: no command given",
        ));
    }
    // Walk up from cwd to the nearest projected root, so `blanket run`
    // works from workspace subdirectories like npm run does.
    let cwd = project_dir();
    let dir = projected_root(&cwd);
    let venv = dir.join(".venv");
    let nm = dir.join("node_modules");
    let cargo_home = dir.join(".blanket/cargo-home");
    let node_projected = std::fs::symlink_metadata(&nm)
        .map(|md| md.file_type().is_symlink())
        .unwrap_or(false)
        && std::fs::symlink_metadata(dir.join(".blanket/closures/node.json")).is_ok();
    let nearest_nm = if node_projected {
        let forest_root = nm
            .canonicalize()
            .ok()
            .and_then(|path| path.parent().map(Path::to_path_buf));
        cwd.ancestors()
            .take_while(|path| path.starts_with(&dir))
            .map(|path| path.join("node_modules"))
            .find(|path| {
                std::fs::symlink_metadata(path)
                    .map(|md| md.file_type().is_symlink())
                    .unwrap_or(false)
                    && forest_root
                        .as_ref()
                        .and_then(|root| path.canonicalize().ok().map(|path| path.starts_with(root)))
                        .unwrap_or(false)
            })
            .unwrap_or_else(|| nm.clone())
    } else {
        nm.clone()
    };
    let package_json = if node_projected {
        project::read_closure(&dir, "node")?;
        let path = dir.join("package.json");
        if std::fs::symlink_metadata(&path).is_ok() {
            Some((path.canonicalize()?, std::fs::read_to_string(path)?))
        } else {
            None
        }
    } else {
        None
    };
    let script_steps = package_json
        .as_ref()
        .map(|(_, json)| npm::script_commands_from_package(json, &cmd[0], &cmd[1..]))
        .transpose()?
        .flatten();
    let package_metadata = if script_steps.is_some() {
        let (_, json) = package_json
            .as_ref()
            .expect("script steps require package.json");
        let package: serde_json::Value = serde_json::from_str(json).map_err(|e| {
            io::Error::new(io::ErrorKind::InvalidInput, format!("package.json: {e}"))
        })?;
        Some((
            package["name"].as_str().map(str::to_string),
            package["version"].as_str().map(str::to_string),
        ))
    } else {
        None
    };
    if refuse_dotnet_script(
        std::fs::symlink_metadata(dir.join(".blanket/closures/dotnet.json")).is_ok(),
        script_steps.is_some(),
    ) {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "package.json scripts are not run under a .NET projection (MSBuild belongs in the sandbox: use `blanket build dotnet`)",
        ));
    }
    let mut prefix: Vec<String> = Vec::new();
    let mut command = std::process::Command::new(&cmd[0]);
    command.args(&cmd[1..]);
    if venv.exists() {
        prefix.push(venv.join("bin").to_string_lossy().into_owned());
        command.env("VIRTUAL_ENV", &venv);
        command.env("PYTHONDONTWRITEBYTECODE", "1"); // site-packages is read-only
    }
    if nm.exists() {
        prefix.push(nearest_nm.join(".bin").to_string_lossy().into_owned());
        if nearest_nm != nm {
            prefix.push(nm.join(".bin").to_string_lossy().into_owned());
        }
        // Node toolchain from the store (cache hit after sync).
        let store = store::Store::open()?;
        let node = npm::ensure_node_for(&store, platform)?;
        prefix.push(node.join("bin").to_string_lossy().into_owned());
    }
    if cargo_home.exists() {
        let store = store::Store::open()?;
        let closure = project::read_closure(&dir, "cargo")?;
        // Store-contained resolution: a project-editable closure must never
        // inject arbitrary executable paths (Sol review 5).
        let rust_obj = project::closure_object(&store, &closure, "rust_object", "bin/rustc")?;
        prefix.push(cargo_home.join("bin").to_string_lossy().into_owned());
        prefix.push(rust_obj.join("bin").to_string_lossy().into_owned());
        command.env("CARGO_HOME", cargo_home.canonicalize()?);
        command.env_remove("RUSTUP_HOME");
        command.env_remove("RUSTUP_TOOLCHAIN");
    }
    if dir.join(".blanket/closures/go.json").exists() {
        let store = store::Store::open()?;
        let closure = project::read_closure(&dir, "go")?;
        let go_obj = project::closure_object(&store, &closure, "go_object", "bin/go")?;
        let modcache = project::closure_object(&store, &closure, "modcache_object", "")?;
        prefix.push(go_obj.join("bin").to_string_lossy().into_owned());
        for (k, v) in golang::go_env(&go_obj, &modcache, true) {
            if v.is_empty() {
                command.env_remove(&k);
            } else {
                command.env(&k, &v);
            }
        }
    }
    if dir.join(".blanket/closures/ruby.json").exists() {
        let store = store::Store::open()?;
        let closure = project::read_closure(&dir, "ruby")?;
        let ruby_obj = project::closure_object(&store, &closure, "ruby_object", "bin/ruby")?;
        let gems_obj = project::closure_object(&store, &closure, "gems_object", "")?;
        // Ruby FIRST, then gem binstubs (a gem exe must never shadow ruby).
        prefix.push(ruby_obj.join("bin").to_string_lossy().into_owned());
        prefix.push(gems_obj.join("bin").to_string_lossy().into_owned());
        let (prefixes, remove, set) = ruby::run_env(&dir, &gems_obj);
        blanket::sandbox::force_env(&mut command, &prefixes, &remove, &set);
    }
    if dir.join(".blanket/closures/elixir.json").exists() {
        let store = store::Store::open()?;
        let closure = project::read_closure(&dir, "elixir")?;
        let beam = project::closure_object(&store, &closure, "beam_object", "elixir/bin/mix")?;
        // The deps projection is a writable clone OUTSIDE the store; verify
        // it lives under the blanket home and matches the recorded deps id.
        let deps_obj = project::closure_object(&store, &closure, "deps_object", "")?;
        // Never trust the recorded projection path: reconstruct the ONE
        // expected forest path from canonical project + deps id and require
        // exact canonical equality (Sol: lexical checks admitted foreign
        // forests, dot-dot tricks, and symlinked dirs).
        let projection = elixir::expected_projection(&store, &dir, &deps_obj)?;
        let recorded = closure["deps_projection"].as_str().map(PathBuf::from);
        if recorded.as_deref().and_then(|p| p.canonicalize().ok()) != Some(projection.clone())
            || !projection.is_dir()
        {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                "elixir closure projection is not the expected forest path; \
                 run `blanket sync` first",
            ));
        }
        prefix.push(beam.join("elixir/bin").to_string_lossy().into_owned());
        prefix.push(beam.join("otp/bin").to_string_lossy().into_owned());
        let scratch = std::env::temp_dir().join(format!("blanket-mix-run-{}", std::process::id()));
        std::fs::create_dir_all(&scratch)?;
        let (prefixes, remove, set) =
            elixir::run_env(
                &beam,
                &projection,
                &elixir::build_root(platform, &dir)?,
                &scratch,
            )?;
        blanket::sandbox::force_env(&mut command, &prefixes, &remove, &set);
    }
    if dir.join(".blanket/closures/dotnet.json").exists() {
        // This prevents accidental unsandboxed builds, not deliberate bypasses
        // through wrappers such as `sh -c`; during realization and build,
        // blanket never evaluates project code outside its sandbox. Missing-lock
        // lock generation is the explicit host-side exception.
        if let Some(reason) = dotnet::refused_run_command(cmd) {
            return Err(io::Error::new(io::ErrorKind::InvalidInput, reason));
        }
        let store = store::Store::open()?;
        let closure = project::read_closure(&dir, "dotnet")?;
        let sdk = project::closure_object(&store, &closure, "sdk_object", "dotnet")?;
        let packages = project::closure_object(&store, &closure, "packages_object", "")?;
        prefix.push(sdk.to_string_lossy().into_owned());
        let scratch = std::env::temp_dir().join(format!("blanket-dn-run-{}", std::process::id()));
        std::fs::create_dir_all(&scratch)?;
        let (prefixes, remove, set) = dotnet::run_env(&sdk, &packages, &scratch);
        blanket::sandbox::force_env(&mut command, &prefixes, &remove, &set);
    }
    if prefix.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::NotFound,
            "no environment projected here; run `blanket sync` first",
        ));
    }
    let path = std::env::var("PATH").unwrap_or_default();
    prefix.push(path);
    command.env("PATH", prefix.join(":"));
    if let Some(steps) = script_steps {
        let ((package_json_path, _), (package_name, package_version)) = package_json
            .as_ref()
            .zip(package_metadata)
            .expect("script steps require package metadata");
        let envs: Vec<_> = command
            .get_envs()
            .map(|(key, value)| (key.to_os_string(), value.map(|value| value.to_os_string())))
            .collect();
        let npm_envs: Vec<_> = std::env::vars_os()
            .map(|(key, _)| key)
            .chain(envs.iter().map(|(key, _)| key.clone()))
            .filter(|key| key.to_string_lossy().starts_with("npm_"))
            .collect();
        for (event, script) in steps {
            eprintln!("blanket: > {event}: {script}");
            let mut step = std::process::Command::new("/bin/sh");
            step.arg("-c").arg(script).current_dir(&dir);
            for (key, value) in &envs {
                match value {
                    Some(value) => {
                        step.env(key, value);
                    }
                    None => {
                        step.env_remove(key);
                    }
                }
            }
            for key in &npm_envs {
                step.env_remove(key);
            }
            step.env("npm_lifecycle_event", &event);
            if let Some(name) = &package_name {
                step.env("npm_package_name", name);
            }
            if let Some(version) = &package_version {
                step.env("npm_package_version", version);
            }
            step.env("npm_package_json", package_json_path);
            step.env("INIT_CWD", &cwd);
            let status = step
                .status()
                .map_err(|e| io::Error::new(e.kind(), format!("run npm script {event}: {e}")))?;
            if !status.success() {
                use std::os::unix::process::ExitStatusExt;
                exit(
                    status
                        .code()
                        .or_else(|| status.signal().map(|signal| 128 + signal))
                        .unwrap_or(1),
                );
            }
        }
        return Ok(());
    }
    use std::os::unix::process::CommandExt;
    let err = command.exec(); // only returns on failure
    Err(err)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    struct TempDir(PathBuf);

    impl TempDir {
        fn new() -> Self {
            let path = std::env::temp_dir().join(format!(
                "blanket-main-test-{}-{}",
                std::process::id(),
                SystemTime::now()
                    .duration_since(UNIX_EPOCH)
                    .unwrap()
                    .as_nanos()
            ));
            std::fs::create_dir_all(&path).unwrap();
            Self(path)
        }
    }

    impl Drop for TempDir {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.0);
        }
    }

    #[test]
    fn cargo_participation_requires_local_manifest() {
        let temp = TempDir::new();
        let nested = temp.0.join("outer/inner");
        std::fs::create_dir_all(&nested).unwrap();
        std::fs::write(temp.0.join("outer/Cargo.toml"), "[package]\nname=\"o\"\n").unwrap();
        // sync/plan only join in where the invocation dir itself is a package
        assert!(is_cargo_here(&temp.0.join("outer")));
        assert!(!is_cargo_here(&nested));
        std::fs::write(nested.join("Cargo.lock"), "version = 4\n").unwrap();
        assert!(is_cargo_here(&nested));
    }

    #[test]
    fn dotnet_run_guard_handles_options_and_msbuild_dll() {
        assert!(dotnet::refused_run_command(
            &["dotnet", "-d", "build"]
                .into_iter()
                .map(String::from)
                .collect::<Vec<_>>()
        )
        .is_some());
        assert!(dotnet::refused_run_command(
            &["dotnet", "msbuild"]
                .into_iter()
                .map(String::from)
                .collect::<Vec<_>>()
        )
        .is_some());
        assert!(dotnet::refused_run_command(
            &["dotnet", "exec", "/tmp/tools/MSBuild.dll"]
                .into_iter()
                .map(String::from)
                .collect::<Vec<_>>()
        )
        .is_some());
        assert!(dotnet::refused_run_command(
            &["dotnet", "exec", "app.dll"]
                .into_iter()
                .map(String::from)
                .collect::<Vec<_>>()
        )
        .is_none());
    }

    #[test]
    fn dotnet_projection_refuses_resolved_package_scripts() {
        assert!(refuse_dotnet_script(true, true));
        assert!(!refuse_dotnet_script(true, false));
        assert!(!refuse_dotnet_script(false, true));
    }

    #[test]
    fn projected_root_skips_plain_node_modules() {
        let t = TempDir::new();
        let root = t.0.join("proj");
        std::fs::create_dir_all(root.join(".blanket/closures")).unwrap();
        let sub = root.join("docs");
        std::fs::create_dir_all(sub.join("node_modules")).unwrap();
        assert_eq!(projected_root(&sub), root);
        assert_eq!(projected_root(&root), root);
        let outside = t.0.join("elsewhere");
        std::fs::create_dir_all(&outside).unwrap();
        assert_eq!(projected_root(&outside), outside);
    }

    #[test]
    fn cache_key_builders_track_independent_inputs() {
        let source = "six==1.17.0\n";
        let darwin_plan = planner_input_hash(
            Platform::Aarch64AppleDarwin,
            "3.12.14",
            source,
            pypi::Glibc(0, 0),
        );
        let linux_plan = planner_input_hash(
            Platform::X86_64UnknownLinuxGnu,
            "3.12.14",
            source,
            pypi::Glibc(2, 43),
        );
        let linux_changed_glibc = planner_input_hash(
            Platform::X86_64UnknownLinuxGnu,
            "3.12.14",
            source,
            pypi::Glibc(2, 42),
        );
        let changed_plan = planner_input_hash(
            Platform::Aarch64AppleDarwin,
            "3.12.14",
            "six==1.17.0\n# changed",
            pypi::Glibc(0, 0),
        );
        assert_ne!(darwin_plan, changed_plan); // source only
        assert_ne!(darwin_plan, linux_plan); // platform only
        assert_ne!(linux_plan, linux_changed_glibc); // host glibc only
        assert_eq!(
            darwin_plan,
            planner_input_hash(
                Platform::Aarch64AppleDarwin,
                "3.12.14",
                source,
                pypi::Glibc(2, 43),
            )
        ); // neither
        assert_eq!(
            darwin_plan,
            "dc181496c6681389a89b3191dba44abdfe8efef8044e540777e7b62c91166411"
        );

        // The lock-source stamp is platform-free on purpose (see its doc):
        // this is main's exact format, so pre-port darwin stamps stay valid.
        let lock = lock_source_hash("3.12", source);
        let changed_lock = lock_source_hash("3.12", "six==1.17.0\n# changed");
        assert_ne!(lock, changed_lock); // source only
        assert_eq!(lock, lock_source_hash("3.12", source)); // same input
        {
            use sha2::{Digest, Sha256};
            assert_eq!(
                lock,
                hex::encode(Sha256::digest(format!("3.12\x00{source}").as_bytes()))
            );
        }
    }

    #[test]
    fn unconstrained_python_keeps_default_and_existing_cache_inputs() {
        let selection = pyselect::select_python(Platform::Aarch64AppleDarwin, &[]).unwrap();
        assert_eq!(selection.pin.version, "3.12.14");
        let source = "six==1.17.0\n";
        assert_eq!(
            planner_input_hash(
                Platform::Aarch64AppleDarwin,
                selection.pin.version,
                source,
                pypi::Glibc(0, 0),
            ),
            "dc181496c6681389a89b3191dba44abdfe8efef8044e540777e7b62c91166411"
        );
        assert_eq!(
            lock_source_hash(selection.pin.version, source),
            "2036e745694799536bfd9bee5ce7f4fbf3a1f621d96e8d54e632e4d0c2334c67"
        );
    }

    #[test]
    fn plan_skipped_requirement_is_strict_or_recorded_once() {
        let source = ".\n";
        let strict = policy::Policy {
            strict: true,
            ..policy::Policy::default()
        };
        let error = record_skippable_specs_with("requirements.txt", source, |kind, subject, detail| {
            policy::record_with(&strict, kind, subject, detail)
        })
        .unwrap_err();
        assert_eq!(error.kind(), io::ErrorKind::PermissionDenied);

        let mut recorded = Vec::new();
        record_skippable_specs_with("requirements.txt", source, |kind, subject, detail| {
            recorded.push((kind.to_string(), subject.to_string(), detail.to_string()));
            Ok(())
        })
        .unwrap();
        assert_eq!(recorded.len(), 1);
        assert!(pypi::parse_requirements(source).unwrap().is_empty());
    }
}
