use blanket::{cargo, npm, project, pypi, python, store, types};

use std::io;
use std::path::{Path, PathBuf};
use std::process::exit;

const USAGE: &str = "\
blanket — universal realization & environment kernel (python + node + cargo)

USAGE:
  blanket sync [--fresh]  realize + project env(s) from lockfiles
                          (--fresh rebuilds the projection, dropping caches)
  blanket plan            print the locked plan(s) as JSON
  blanket build [args...] build a Cargo project in the network-denied sandbox
  blanket run <cmd...>    run a command inside the projected environment(s)
  blanket store path      print the store root

Project inputs (either or both):
  requirements.txt        python deps; ranged files are auto-locked via uv
                          into requirements.lock.txt (hash-pinned)
  .python-version         optional; e.g. 3.12 (default: 3.12)
  package-lock.json       npm lockfile v2/v3 (npm install --package-lock-only)
  Cargo.toml/Cargo.lock   Rust deps; missing Cargo.lock is generated by store Cargo
";

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let code = match args.first().map(String::as_str) {
        Some("sync") => run_sync(args.iter().any(|a| a == "--fresh")),
        Some("plan") => run_plan(),
        Some("build") => run_build(&args[1..]),
        Some("run") => run_run(&args[1..]),
        Some("store") if args.get(1).map(String::as_str) == Some("path") => {
            store::Store::open().map(|s| println!("{}", s.root.display()))
        }
        _ => {
            eprint!("{USAGE}");
            exit(2);
        }
    }
    .map(|_| 0)
    .unwrap_or_else(|e| {
        eprintln!("blanket: error: {e}");
        1
    });
    exit(code);
}

fn project_dir() -> PathBuf {
    std::env::current_dir().expect("cwd")
}

/// Implicit detection for sync/plan: cargo joins the party only when the
/// invocation dir is itself a Cargo package (workspace members included).
/// Without this gate, running blanket in any project nested under an
/// unrelated Cargo workspace would silently project into that parent tree.
fn is_cargo_here(dir: &Path) -> bool {
    dir.join("Cargo.toml").is_file() || dir.join("Cargo.lock").is_file()
}

struct CargoInputs {
    root: PathBuf,
    rust_obj: PathBuf,
    plan: cargo::CargoPlan,
    lock_digest: String,
}

/// Workspace rooting is delegated to the pinned Cargo itself
/// (`locate-project --workspace`): an ancestor-walk for Cargo.lock picks an
/// unrelated outer lock when independent packages nest (Sol review, repro'd).
fn locate_cargo_root(rust_obj: &Path, cwd: &Path) -> io::Result<PathBuf> {
    let out = std::process::Command::new(rust_obj.join("bin/cargo"))
        .args(["locate-project", "--workspace", "--message-format", "plain", "--offline"])
        .current_dir(cwd)
        .env_remove("RUSTUP_HOME")
        .env_remove("RUSTUP_TOOLCHAIN")
        .output()
        .map_err(|e| io::Error::new(e.kind(), format!("run store cargo locate-project: {e}")))?;
    if !out.status.success() {
        return Err(io::Error::other(format!(
            "cargo locate-project failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        )));
    }
    let manifest = PathBuf::from(String::from_utf8_lossy(&out.stdout).trim());
    manifest
        .parent()
        .map(Path::to_path_buf)
        .ok_or_else(|| io::Error::other("cargo locate-project returned no manifest path"))
}

fn load_cargo_inputs(cwd: &Path, store: &store::Store) -> io::Result<CargoInputs> {
    let rust_version = cargo::resolve_toolchain(cwd)?;
    let rust_obj = cargo::ensure_rust(store, rust_version)?;
    let root = locate_cargo_root(&rust_obj, cwd)?;
    if !root.join("Cargo.lock").is_file() {
        ensure_cargo_lock(&root, &rust_obj)?;
    }
    let lock = std::fs::read_to_string(root.join("Cargo.lock"))?;
    let plan = cargo::plan_cargo(&lock, rust_version)?;
    Ok(CargoInputs {
        root,
        rust_obj,
        plan,
        lock_digest: cargo::lock_digest(&lock),
    })
}

fn ensure_cargo_lock(root: &Path, rust_obj: &Path) -> io::Result<()> {
    eprintln!(
        "blanket: no Cargo.lock; generating it with the store Rust toolchain \
         (network allowed, unsandboxed)..."
    );
    let status = std::process::Command::new(rust_obj.join("bin/cargo"))
        .arg("generate-lockfile")
        .current_dir(root)
        .env("CARGO_NET_OFFLINE", "false")
        .env_remove("RUSTUP_HOME")
        .env_remove("RUSTUP_TOOLCHAIN")
        .status()
        .map_err(|e| {
            io::Error::new(
                e.kind(),
                format!(
                    "could not run store Cargo to generate Cargo.lock: {e}; \
                     use `blanket sync` after fixing the project or network"
                ),
            )
        })?;
    if !status.success() {
        return Err(io::Error::other(
            "store Cargo generate-lockfile failed; check the project manifest and network",
        ));
    }
    Ok(())
}

/// Plan from project inputs. Planning hits PyPI, so successful plans are
/// cached in .blanket/plan.json keyed by a hash of the inputs; an unchanged
/// lock replans offline and instantly.
fn read_plan(dir: &Path) -> io::Result<types::Plan> {
    let req_path = dir.join("requirements.txt");
    let source = std::fs::read_to_string(&req_path).map_err(|e| {
        io::Error::new(e.kind(), format!("{}: {e}", req_path.display()))
    })?;
    let pyver = std::fs::read_to_string(dir.join(".python-version"))
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|_| "3.12".into());
    let pin = python::lookup(&pyver).ok_or_else(|| {
        io::Error::new(
            io::ErrorKind::NotFound,
            format!("no pinned CPython matching '{pyver}'"),
        )
    })?;

    // Real projects mostly carry ranged requirements, not hash-pinned ones.
    // Resolution is delegated to the ecosystem's own resolver (uv) — blanket
    // owns realization, not solving. The generated requirements.lock.txt is
    // regenerated whenever requirements.txt changes. A file that IS pinned
    // but uses features the direct parser rejects (environment markers,
    // extras — e.g. `uv pip compile --universal` output) is re-locked for
    // this platform the same way rather than hard-failing.
    let text = if is_fully_pinned(&source) {
        match pypi::parse_requirements(&source) {
            Ok(_) => source,
            Err(e) => {
                eprintln!(
                    "blanket: requirements.txt is pinned but not directly \
                     consumable ({e}); re-locking for this platform with uv..."
                );
                locked_requirements(dir, &source, pin.version)?
            }
        }
    } else {
        locked_requirements(dir, &source, pin.version)?
    };

    use sha2::{Digest, Sha256};
    // PLANNER_SCHEMA busts stale caches when planner semantics change.
    const PLANNER_SCHEMA: &str = "python-planner/2";
    let input_hash = hex::encode(Sha256::digest(
        format!("{PLANNER_SCHEMA}\x00{}\x00{}", pin.version, text).as_bytes(),
    ));
    let cache_path = dir.join(".blanket/plan.json");
    if let Ok(cached) = std::fs::read_to_string(&cache_path) {
        if let Ok(v) = serde_json::from_str::<serde_json::Value>(&cached) {
            if v["input_hash"] == input_hash.as_str() {
                if let Ok(plan) = serde_json::from_value(v["plan"].clone()) {
                    return Ok(plan);
                }
            }
        }
    }

    let plan = pypi::plan_python(&text, pin.version)?;
    std::fs::create_dir_all(dir.join(".blanket"))?;
    std::fs::write(
        &cache_path,
        serde_json::to_vec_pretty(&serde_json::json!({
            "input_hash": input_hash,
            "plan": plan,
        }))?,
    )?;
    Ok(plan)
}

/// Every non-comment logical line (after backslash continuations) carries a
/// --hash= option. That is the shape `uv pip compile --generate-hashes`
/// emits and the only shape the planner accepts directly.
fn is_fully_pinned(text: &str) -> bool {
    let mut logical = String::new();
    let mut any = false;
    for raw in text.lines().chain(std::iter::once("")) {
        if let Some(stripped) = raw.strip_suffix('\\') {
            logical.push_str(stripped);
            continue;
        }
        logical.push_str(raw);
        let line = logical.trim();
        let line = match line.find(" #") {
            Some(i) => line[..i].trim(),
            None => line,
        };
        if !line.is_empty() && !line.starts_with('#') {
            any = true;
            if !line.contains("--hash=") {
                return false;
            }
        }
        logical.clear();
    }
    any
}

/// Resolve ranged requirements to a hash-pinned lock via uv, cached in
/// requirements.lock.txt and regenerated when requirements.txt changes.
fn locked_requirements(dir: &Path, source: &str, pyver: &str) -> io::Result<String> {
    use sha2::{Digest, Sha256};
    let lock_path = dir.join("requirements.lock.txt");
    let stamp_path = dir.join(".blanket/lock-source.hash");
    let source_hash = hex::encode(Sha256::digest(format!("{pyver}\x00{source}").as_bytes()));
    if let (Ok(stamp), Ok(lock)) = (
        std::fs::read_to_string(&stamp_path),
        std::fs::read_to_string(&lock_path),
    ) {
        if stamp.trim() == source_hash {
            return Ok(lock);
        }
    }
    eprintln!("blanket: requirements.txt is not hash-pinned; resolving with the store uv...");
    // Store-pinned uv, not host uv: a bare machine needs only blanket.
    let uv = python::ensure_uv(&store::Store::open()?)?.join("uv");
    let status = std::process::Command::new(&uv)
        .args(["pip", "compile", "requirements.txt", "--generate-hashes", "--quiet"])
        .args(["--python-version", pyver])
        .args(["-o", "requirements.lock.txt"])
        .current_dir(dir)
        .status()
        .map_err(|e| {
            io::Error::new(e.kind(), format!("run store uv ({}): {e}", uv.display()))
        })?;
    if !status.success() {
        return Err(io::Error::other("uv pip compile failed"));
    }
    std::fs::create_dir_all(dir.join(".blanket"))?;
    std::fs::write(&stamp_path, &source_hash)?;
    std::fs::read_to_string(&lock_path)
}

fn run_plan() -> io::Result<()> {
    let dir = project_dir();
    ensure_npm_lock(&dir)?;
    let mut any = false;
    if dir.join("requirements.txt").exists() {
        let plan = read_plan(&dir)?;
        println!("{}", serde_json::to_string_pretty(&plan)?);
        any = true;
    }
    if dir.join("package-lock.json").exists() {
        let plan = npm::plan_npm(&std::fs::read_to_string(dir.join("package-lock.json"))?)?;
        let v: Vec<_> = plan
            .packages
            .iter()
            .map(|p| {
                serde_json::json!({"path": p.path, "version": p.version,
                                   "url": p.url, "integrity": p.integrity})
            })
            .collect();
        println!(
            "{}",
            serde_json::to_string_pretty(&serde_json::json!({
                "ecosystem": "node", "node_version": plan.node_version, "packages": v
            }))?
        );
        any = true;
    }
    if is_cargo_here(&dir) {
        let store = store::Store::open()?;
        let inputs = load_cargo_inputs(&dir, &store)?;
        println!("{}", serde_json::to_string_pretty(&inputs.plan)?);
        any = true;
    }
    if !any {
        return Err(no_inputs());
    }
    Ok(())
}

fn no_inputs() -> io::Error {
    io::Error::new(
        io::ErrorKind::NotFound,
        "nothing to sync here (need requirements.txt, package-lock.json, or Cargo.toml)",
    )
}

/// A package.json without a package-lock.json (bun/yarn/pnpm projects):
/// delegate lock generation to npm, mirroring the uv flow for Python.
/// Resolution is the ecosystem's job; realization is blanket's.
fn ensure_npm_lock(dir: &Path) -> io::Result<()> {
    if !dir.join("package.json").exists() || dir.join("package-lock.json").exists() {
        return Ok(());
    }
    for other in ["bun.lock", "bun.lockb", "yarn.lock", "pnpm-lock.yaml"] {
        if dir.join(other).exists() {
            eprintln!(
                "blanket: note: {other} found; generating package-lock.json via npm \
                 (versions resolve fresh — they may differ from {other})"
            );
            break;
        }
    }
    eprintln!("blanket: no package-lock.json; resolving with the store npm...");
    // Store node's bundled npm, not host npm: a bare machine needs only
    // blanket. npm-cli's shebang is `env node`, so the store bin leads PATH.
    let node = npm::ensure_node(&store::Store::open()?)?;
    let path = format!(
        "{}:{}",
        node.join("bin").display(),
        std::env::var("PATH").unwrap_or_default()
    );
    let status = std::process::Command::new(node.join("bin/npm"))
        .args(["install", "--package-lock-only", "--ignore-scripts", "--silent"])
        .current_dir(dir)
        .env("PATH", path)
        .status()
        .map_err(|e| {
            io::Error::new(e.kind(), format!("run store npm ({}/bin/npm): {e}", node.display()))
        })?;
    if !status.success() {
        return Err(io::Error::other("npm install --package-lock-only failed"));
    }
    Ok(())
}

fn run_sync(fresh: bool) -> io::Result<()> {
    let dir = project_dir();
    let store = store::Store::open()?;
    ensure_npm_lock(&dir)?;
    let mut any = false;
    if dir.join("requirements.txt").exists() {
        let plan = read_plan(&dir)?;
        let env = project::realize_env(&store, &plan)?;
        project::project_env(&dir, &env, &plan)?;
        eprintln!("synced: .venv -> {}", env.display());
        any = true;
    }
    if dir.join("package-lock.json").exists() {
        let lock = std::fs::read_to_string(dir.join("package-lock.json"))?;
        let mut config = npm::BlanketConfig::default();
        if let Ok(pkg) = std::fs::read_to_string(dir.join("package.json")) {
            npm::check_lock_freshness(&pkg, &lock)?;
            config = npm::parse_blanket_config(&pkg)?;
        }
        let plan = npm::plan_npm(&lock)?;
        let env = npm::realize_node_env(&store, &plan, &config.artifacts)?;
        npm::project_node_env(&dir, &env, &plan, &config.mutable_packages, fresh)?;
        eprintln!("synced: node_modules -> {}", env.display());
        any = true;
    }
    if is_cargo_here(&dir) {
        let inputs = load_cargo_inputs(&dir, &store)?;
        let rust_obj = &inputs.rust_obj;
        let vendor_obj = cargo::realize_vendor(&store, &inputs.plan)?;
        if fresh {
            let cargo_home = inputs.root.join(".blanket/cargo-home");
            if std::fs::symlink_metadata(&cargo_home).is_ok() {
                store::remove_tree(&cargo_home)?;
            }
        }
        cargo::project_cargo_env(
            &inputs.root,
            rust_obj,
            &vendor_obj,
            &inputs.plan,
            &inputs.lock_digest,
        )?;
        eprintln!("synced: cargo env -> {}", vendor_obj.display());
        any = true;
    }
    if !any {
        return Err(no_inputs());
    }
    Ok(())
}

fn run_build(args: &[String]) -> io::Result<()> {
    let cwd = project_dir();
    // Explicit cargo command: manifest discovery walks up, like cargo's own.
    if !cwd.ancestors().any(is_cargo_here) {
        return Err(io::Error::new(
            io::ErrorKind::NotFound,
            "blanket build requires a Cargo.toml; run it from a Cargo project",
        ));
    }
    let store = store::Store::open()?;
    let inputs = load_cargo_inputs(&cwd, &store)?;
    let vendor_obj = cargo::realize_vendor(&store, &inputs.plan)?;
    cargo::project_cargo_env(
        &inputs.root,
        &inputs.rust_obj,
        &vendor_obj,
        &inputs.plan,
        &inputs.lock_digest,
    )?;
    cargo::build_sandboxed(&inputs.root, &inputs.rust_obj, &vendor_obj, args)
}

fn run_run(cmd: &[String]) -> io::Result<()> {
    if cmd.is_empty() {
        return Err(io::Error::new(io::ErrorKind::InvalidInput, "run: no command given"));
    }
    // Walk up from cwd to the nearest projected root, so `blanket run`
    // works from workspace subdirectories like npm run does.
    let cwd = project_dir();
    let dir = cwd
        .ancestors()
        .find(|d| {
            d.join(".venv").exists()
                || d.join("node_modules").exists()
                || d.join(".blanket/cargo-home").exists()
        })
        .unwrap_or(&cwd)
        .to_path_buf();
    let venv = dir.join(".venv");
    let nm = dir.join("node_modules");
    let cargo_home = dir.join(".blanket/cargo-home");
    let mut prefix: Vec<String> = Vec::new();
    let mut command = std::process::Command::new(&cmd[0]);
    command.args(&cmd[1..]);
    if venv.exists() {
        prefix.push(venv.join("bin").to_string_lossy().into_owned());
        command.env("VIRTUAL_ENV", &venv);
        command.env("PYTHONDONTWRITEBYTECODE", "1"); // site-packages is read-only
    }
    if nm.exists() {
        prefix.push(nm.join(".bin").to_string_lossy().into_owned());
        // Node toolchain from the store (cache hit after sync).
        let store = store::Store::open()?;
        let node = npm::ensure_node(&store)?;
        prefix.push(node.join("bin").to_string_lossy().into_owned());
    }
    if cargo_home.exists() {
        let closure = project::read_closure(&dir, "cargo")?;
        let rust_obj = closure["rust_object"]["path"]
            .as_str()
            .map(PathBuf::from)
            .filter(|path| path.is_absolute() && path.join("bin/rustc").is_file())
            .ok_or_else(|| {
                io::Error::new(
                    io::ErrorKind::InvalidData,
                    "cargo closure has no valid Rust object; run `blanket sync` first",
                )
            })?;
        prefix.push(cargo_home.join("bin").to_string_lossy().into_owned());
        prefix.push(rust_obj.join("bin").to_string_lossy().into_owned());
        command.env("CARGO_HOME", cargo_home.canonicalize()?);
        command.env_remove("RUSTUP_HOME");
        command.env_remove("RUSTUP_TOOLCHAIN");
    }
    if prefix.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::NotFound,
            "no environment projected here; run `blanket sync` first",
        ));
    }
    let path = std::env::var("PATH").unwrap_or_default();
    prefix.push(path);
    use std::os::unix::process::CommandExt;
    let err = command.env("PATH", prefix.join(":")).exec(); // only returns on failure
    Err(err)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    struct TempDir(PathBuf);

    impl TempDir {
        fn new() -> Self {
            let path = std::env::temp_dir().join(format!(
                "blanket-main-test-{}-{}",
                std::process::id(),
                SystemTime::now()
                    .duration_since(UNIX_EPOCH).unwrap().as_nanos()
            ));
            std::fs::create_dir_all(&path).unwrap();
            Self(path)
        }
    }

    impl Drop for TempDir {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.0);
        }
    }

    #[test]
    fn cargo_participation_requires_local_manifest() {
        let temp = TempDir::new();
        let nested = temp.0.join("outer/inner");
        std::fs::create_dir_all(&nested).unwrap();
        std::fs::write(temp.0.join("outer/Cargo.toml"), "[package]\nname=\"o\"\n").unwrap();
        // sync/plan only join in where the invocation dir itself is a package
        assert!(is_cargo_here(&temp.0.join("outer")));
        assert!(!is_cargo_here(&nested));
        std::fs::write(nested.join("Cargo.lock"), "version = 4\n").unwrap();
        assert!(is_cargo_here(&nested));
    }
}
